const std = @import("std");
const mem = std.mem;
const process = std.process;
const Build = std.Build;

const host_os = @import("builtin").os.tag;

fn getToolchainPath(b: *Build) []const u8 {
    return b.graph.environ_map.get("OO_PS4_TOOLCHAIN") orelse
        @panic("Toolchain environment variable OO_PS4_TOOLCHAIN isn't set, please set it.");
}

pub fn build(b: *std.Build) !void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const is_orbis_build = target.result.os.tag == .ps4;

    const use_pic = b.option(bool, "pic", "Produce Position Independent Code") orelse
        is_orbis_build;

    const upstream = b.dependency("upstream", .{});

    if (is_orbis_build) {
        const upstream_musl = try b.dependencyLazy("musl", .{});

        const libc = b.addLibrary(.{
            .name = "musl",
            .linkage = .static,
            .root_module = b.createModule(.{
                .target = target,
                .optimize = optimize,
                .link_libc = false,
                .pic = use_pic,
            }),
        });

        const MUSL_CFLAGS = .{
            "-std=c99",
            "-ffreestanding",
            "-nostdlib",
            "-nodefaultlibs",
            "-D_XOPEN_SOURCE=700",
            "-DPS4",
            "-DPS4_LIBKERNEL_SYS",
        };

        libc.root_module.addIncludePath(upstream_musl.path("arch/ps4"));
        libc.root_module.addIncludePath(upstream_musl.path("arch/generic"));
        libc.root_module.addIncludePath(b.path("musl/include"));
        libc.root_module.addIncludePath(upstream_musl.path("src/include"));
        libc.root_module.addIncludePath(b.path("musl/src/internal"));
        libc.root_module.addIncludePath(upstream_musl.path("src/internal"));
        libc.root_module.addIncludePath(upstream_musl.path("include"));
        libc.root_module.addIncludePath(upstream.path("include"));

        libc.root_module.addCSourceFiles(.{
            .root = upstream_musl.path("crt/ps4"),
            .flags = &MUSL_CFLAGS,
            .files = &.{
                "crt1.c",
            },
            .language = .c,
        });
        libc.root_module.addCSourceFiles(.{
            .root = upstream_musl.path("crt/ps4"),
            .flags = &MUSL_CFLAGS,
            .files = &.{
                "crti.s",
                "crtn.s",
            },
            .language = .assembly,
        });
        libc.root_module.addCSourceFiles(.{
            .root = upstream_musl.path("src"),
            .flags = &MUSL_CFLAGS,
            .files = MUSL_SRC_FILES,
            .language = .c,
        });

        libc.installHeadersDirectory(upstream_musl.path("include"), "", .{});
        libc.installHeadersDirectory(upstream_musl.path("arch/generic/bits"), "bits", .{});
        libc.installHeadersDirectory(upstream_musl.path("arch/ps4/bits"), "bits", .{});
        libc.installHeadersDirectory(b.path("musl/include"), "", .{});
        libc.installHeadersDirectory(upstream.path("include"), "", .{});

        b.installArtifact(libc);
    }

    const maybe_sys_lib_wf = if (!is_orbis_build) null else blk: {
        const sys_lib_wf = b.addNamedWriteFiles("sys_libs");
        for (SYSTEM_LIBRARIES) |lib_name| {
            try buildSystemLibraryStub(sys_lib_wf, b, lib_name, target);
        }
        break :blk sys_lib_wf;
    };

    const mod_orbis = b.addModule("orbis", .{
        .root_source_file = b.path("src/root.zig"),
        .target = target,
        .optimize = optimize,
        .pic = use_pic,
    });
    if (maybe_sys_lib_wf) |sys_lib_wf| {
        mod_orbis.addSystemIncludePath(sys_lib_wf.getDirectory());
    }

    //
    // tests
    //
    const tests_all = b.addTest(.{
        .name = "test-orbis",
        .root_module = mod_orbis,
    });
    const run_tests_all = b.addRunArtifact(tests_all);
    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_tests_all.step);

    //
    // check stage for ZLS
    //
    const step_check = b.step("check", "Check if the project compiles");
    const check_exe = b.addExecutable(.{
        .name = "check-orbis",
        .root_module = mod_orbis,
    });
    step_check.dependOn(&check_exe.step);
}

const DEFAULT_EBOOT_PATH = "eboot.bin";
const DEFAULT_GP4_PATH = "pkg.gp4";
const DEFAULT_SFO_PATH = "sce_sys/param.sfo";

pub const CreateFselfOptions = struct {
    out_sub_path: []const u8 = DEFAULT_EBOOT_PATH,
    paid: ?[]const u8 = "0x3800000000000011",
};

fn panicUnsupported() noreturn {
    std.debug.panic("Your operating system {t} is not supported by OpenOrbis' Toolchain", .{host_os});
}

pub fn createFself(
    b: *Build,
    exe: *Build.Step.Compile,
    options: CreateFselfOptions,
) Build.LazyPath {
    std.debug.assert(exe.kind == .exe);

    const toolchain_path = getToolchainPath(b);
    const mkfself_path = b.fmt(switch (host_os) {
        .linux => "{s}/bin/linux/create-fself",
        .macos => "{s}/bin/macos/create-fself",
        .windows => "{s}/bin/windows/create-fself.exe",
        else => panicUnsupported(),
    }, .{toolchain_path});

    const eboot_cmd = b.addSystemCommand(&.{mkfself_path});
    eboot_cmd.addPrefixedFileArg("-in=", exe.getEmittedBin());
    const eboot_file = eboot_cmd.addPrefixedOutputFileArg("-eboot=", options.out_sub_path);
    if (options.paid) |paid| {
        eboot_cmd.addArgs(&.{ "--paid", paid });
    }
    eboot_cmd.addArgs(&.{ "--library-path", b.fmt("{s}/lib", .{toolchain_path}) });

    // fself depends on elf
    eboot_cmd.step.dependOn(&exe.step);

    return eboot_file;
}

pub fn createSfo(
    b: *Build,
    orbis_dep: *Build.Dependency,
    manifest_path: Build.LazyPath,
    out_sub_path: []const u8,
) Build.LazyPath {
    const dep_orbpack = orbis_dep.builder.dependency("orbpack", .{});
    const exe_orbpack = dep_orbpack.artifact("orbpack");

    const sfo_cmd = b.addRunArtifact(exe_orbpack);
    sfo_cmd.addArgs(&.{ "sfo", "build" });
    sfo_cmd.addFileArg(manifest_path);
    return sfo_cmd.addOutputFileArg(out_sub_path);
}

pub const CreateGp4Options = struct {
    eboot_path: []const u8 = DEFAULT_EBOOT_PATH,
    sfo_path: []const u8 = DEFAULT_SFO_PATH,
    out_path: []const u8 = DEFAULT_GP4_PATH,
};

pub fn createGp4(
    b: *Build,
    content_id: []const u8,
    assets: []const []const u8,
    options: CreateGp4Options,
) !Build.LazyPath {
    const toolchain_path = getToolchainPath(b);
    const mkgp4_path = b.fmt(switch (host_os) {
        .linux => "{s}/bin/linux/create-gp4",
        .macos => "{s}/bin/macos/create-gp4",
        .windows => "{s}/bin/windows/create-gp4.exe",
        else => panicUnsupported(),
    }, .{toolchain_path});

    const gp4_cmd = b.addSystemCommand(&.{mkgp4_path});
    gp4_cmd.addArg("-out");
    const gp4_file = gp4_cmd.addOutputFileArg(options.out_path);
    gp4_cmd.addArg(b.fmt("--content-id={s}", .{content_id}));
    gp4_cmd.addArg("--files");

    // add relative paths to gp4 file,
    // argument must be manually put in quotes or else create-gp4 won't work properly
    var files_buf = std.ArrayList(u8).empty;
    for (assets) |asset| {
        try files_buf.appendSlice(b.allocator, asset);
        try files_buf.append(b.allocator, ' ');
    }
    try files_buf.appendSlice(b.allocator, options.eboot_path);
    try files_buf.append(b.allocator, ' ');
    try files_buf.appendSlice(b.allocator, options.sfo_path);

    const gp4_args_files = try files_buf.toOwnedSlice(b.allocator);
    defer b.allocator.free(gp4_args_files);
    gp4_cmd.addArg(gp4_args_files);

    return gp4_file;
}

pub const SetupPkgArguments = struct {
    eboot_file: Build.LazyPath,
    gp4_file: Build.LazyPath,
    sfo_file: Build.LazyPath,
};

pub fn setupPkg(
    b: *Build,
    assets: []const []const u8,
    args: SetupPkgArguments,
) *Build.Step.WriteFile {
    const wf = b.addWriteFiles();

    // copy pkg.gp4 to working directory
    _ = wf.addCopyFile(args.gp4_file, DEFAULT_GP4_PATH);

    // setup assets in cache directory
    for (assets) |asset| {
        _ = wf.addCopyFile(b.path(asset), asset);
    }
    // copy eboot to cache directory
    _ = wf.addCopyFile(args.eboot_file, DEFAULT_EBOOT_PATH);
    // copy param.sfo to cache directory
    _ = wf.addCopyFile(args.sfo_file, DEFAULT_SFO_PATH);

    return wf;
}

pub fn createPkg(b: *Build, wf: *Build.Step.WriteFile) *Build.Step.Run {
    const toolchain_path = getToolchainPath(b);
    const pkgtool_path = b.fmt(switch (host_os) {
        .linux => "{s}/bin/linux/PkgTool.Core",
        .macos => "{s}/bin/macos/PkgTool.Core",
        .windows => "{s}/bin/windows/PkgTool.exe",
        else => panicUnsupported(),
    }, .{toolchain_path});

    const gp4_file_work = wf.getDirectory().path(b, DEFAULT_GP4_PATH);

    const pkg_cmd = b.addSystemCommand(&.{ pkgtool_path, "pkg_build" });
    pkg_cmd.addFileArg(gp4_file_work);
    pkg_cmd.addDirectoryArg(wf.getDirectory());

    return pkg_cmd;
}

fn buildSystemLibraryStub(
    wf: *std.Build.Step.WriteFile,
    b: *std.Build,
    name: []const u8,
    target: std.Build.ResolvedTarget,
) !void {
    const stub_lib = b.addLibrary(.{
        .name = name,
        .linkage = .dynamic,
        .root_module = b.createModule(.{
            .target = target,
            .optimize = .debug, // use .debug for faster compilation
            .link_libc = false,
            .link_libcpp = false,
            .sanitize_c = .off,
            .sanitize_thread = false,
            .pic = true,
            .valgrind = false,
            .no_builtin = true,
        }),
    });

    stub_lib.root_module.addCSourceFile(.{
        .file = b.path(b.fmt("lib_stubs/lib{s}.c", .{name})),
        .flags = &.{
            "-ffreestanding",
            "-fvisibility-dllexport=keep",
            "-fvisibility-nodllstorageclass=keep",
        },
        .language = .c,
    });

    _ = wf.addCopyFile(stub_lib.getEmittedBin(), b.fmt("lib{s}.so", .{name}));
}

// build system shared library stubs.
// C# DLLs/PRXs were deliberately ignored ignored
const SYSTEM_LIBRARIES: []const []const u8 = &.{
    "NativeExtensions",
    "ReactNative.Modules.Vsh",
    "SceAbstractDailymotion",
    "SceAbstractFacebook",
    "SceAbstractLocal",
    "SceAbstractStorage",
    "SceAbstractTwitter",
    "SceAbstractYoutube",
    "SceAjm",
    "SceAppContent",
    "SceAppContentIro",
    "SceAppContentPft",
    "SceAppContentSc",
    "SceAppInstUtil",
    "SceAppMessaging",
    "SceAt9Enc",
    "SceAudio3d",
    "SceAudioDeviceControl",
    "SceAudioIn",
    "SceAudioOut",
    "SceAudioOutDeviceService",
    "SceAudioOutSparkControl",
    "SceAudiodec",
    "SceAudiodecCpu",
    "SceAudiodecCpuDdp",
    "SceAudiodecCpuDtsHdLbr",
    "SceAudiodecCpuHevag",
    "SceAudiodecCpuM4aac",
    "SceAutoMounterClient",
    "SceAvPlayer",
    "SceAvPlayerStreaming",
    "SceAvSetting",
    "SceAvSettingDebug",
    "SceAvcap",
    "SceBackupRestoreUtil",
    "SceBeisobmf",
    "SceBemp2sys",
    "SceBgft",
    "SceBluetoothHid",
    "SceCamera",
    "SceCdlgUtilServer",
    "SceCes",
    "SceClSysCallWrapper",
    "SceCommonDialog",
    "SceCompanionHttpd",
    "SceCompanionUtil",
    "SceComposite",
    "SceContentBinder",
    "SceContentDelete",
    "SceContentExport",
    "SceContentSearch",
    "SceConvertKeycode",
    "SceCoredump",
    "SceCoredump_debug",
    "SceCustomMusicCore",
    "SceCustomMusicService",
    "SceDataTransfer",
    "SceDbgAudioOut",
    "SceDbgKeyboard",
    "SceDbgPlayGo",
    "SceDbgVideoOut",
    "SceDepth",
    "SceDeviceService",
    "SceDiscId",
    "SceDiscMap",
    "SceDtcpIp",
    "SceEditMp4",
    "SceErrorDialog",
    "SceFacebook.Yoga",
    "SceFiber",
    "SceFios2",
    "SceFont",
    "SceFontFt",
    "SceFreeType",
    "SceFreeTypeHinter",
    "SceFreeTypeOptOl",
    "SceFreeTypeSubFunc",
    "SceGLSlimServerVSH",
    "SceGLSlimVSH",
    "SceGameCustomDataDialog",
    "SceGameCustomDataDialogCompat",
    "SceGameLiveStreaming",
    "SceGameLiveStreamingCompat",
    "SceGameLiveStreaming_debug",
    "SceGameLiveStreaming_direct_streaming",
    "SceGameUpdate",
    "SceGic",
    "SceGnmDebugModuleReset",
    "SceGnmDebugReset",
    "SceGnmDriver",
    "SceGnmDriverCompat",
    "SceGnmDriverResourceRegistration",
    "SceGnmGetGpuCoreClockFrequency",
    "SceGvMp4Parser",
    "SceHidControl",
    "SceHmd",
    "SceHmdDistortion",
    "SceHmdSetupDialog",
    "SceHttp",
    "SceHttp2",
    "SceHttpCache",
    "SceHubAppUtil",
    "SceIduUtil",
    "SceIme",
    "SceImeBackend",
    "SceImeDialog",
    "SceInjectedBundle",
    "SceInvitationDialog",
    "SceInvitationDialogCompat",
    "SceIpmi",
    "SceIpmiDbg",
    "SceJitBridge",
    "SceJpegDec",
    "SceJpegDec_jvm",
    "SceJpegEnc",
    "SceJpegParser",
    "SceJsc",
    "SceJson2",
    "SceKbEmulate",
    "SceKeyboard",
    "SceLibcInternal",
    "SceLibcInternalExt",
    "SceLibreSSL",
    "SceLibreSSl3",
    "SceLncUtil",
    "SceLoginDialog",
    "SceLoginService",
    "SceM4aacEnc",
    "SceManxWtf",
    "SceMbus",
    "SceMbusDebug",
    "SceMetadataReaderWriter",
    "SceMouse",
    "SceMove",
    "SceMoveTracker",
    "SceMsgDialog",
    "SceMusicCoreServerClient",
    "SceMusicCoreServerClientJsEx",
    "SceMusicPlayerService",
    "SceNet",
    "SceNetBwe",
    "SceNetCtl",
    "SceNetCtlAp",
    "SceNetCtlApDialog",
    "SceNetCtlApIpcInt",
    "SceNetCtlForNpToolkit",
    "SceNetCtlV6",
    "SceNetDebug",
    "SceNgs2",
    "SceNpAppLauncher",
    "SceNpAuth",
    "SceNpAuthCompat",
    "SceNpCommerce",
    "SceNpCommon",
    "SceNpCommonCompat",
    "SceNpEntitlementAccess",
    "SceNpFriendListDialog",
    "SceNpFriendListDialogCompat",
    "SceNpGameIntent",
    "SceNpGriefReport",
    "SceNpManager",
    "SceNpManagerCompat",
    "SceNpManagerForToolkit",
    "SceNpManagerIsPlusMember",
    "SceNpMatching2",
    "SceNpMatching2Compat",
    "SceNpPartner001",
    "SceNpParty",
    "SceNpPartyCompat",
    "SceNpProfileDialog",
    "SceNpProfileDialogCompat",
    "SceNpScore",
    "SceNpScoreCompat",
    "SceNpSessionSignaling",
    "SceNpSignaling",
    "SceNpSignalingCompat",
    "SceNpSns",
    "SceNpSnsDailymotionDialog",
    "SceNpSnsFacebookDialog",
    "SceNpSnsTwitch",
    "SceNpSnsTwitchDialog",
    "SceNpSnsYouTube",
    "SceNpSnsYouTubeDialog",
    "SceNpTrophy",
    "SceNpTus",
    "SceNpTusCompat",
    "SceNpUniversalDataSystem",
    "SceNpUtility",
    "SceNpUtilityCompat",
    "SceNpWebApi",
    "SceNpWebApi2",
    "SceNpWebApiCompat",
    "SceOpenPsId",
    "SceOpusCeltDec",
    "SceOpusCeltEnc",
    "SceOpusDec",
    "SceOpusSilkEnc",
    "SceOrbisCompat",
    "ScePad",
    "ScePadTracker",
    "ScePatchCheckerClient",
    "ScePigletv2VSH",
    "ScePlayGo",
    "ScePlayGoDialog",
    "ScePlayReady",
    "ScePlayReady2",
    "ScePlayerInvitationDialog",
    "ScePngDec",
    "ScePngDec_jvm",
    "ScePngEnc",
    "ScePosix",
    "ScePosixForWebKit",
    "ScePrecompiledShaders",
    "SceProfileCacheExternal",
    "ScePs2EmuMenuDialog",
    "ScePsm",
    "ScePsmKitSystem",
    "ScePsmUtil",
    "SceRandom",
    "SceRazorCpu",
    "SceRegMgr",
    "SceRemoteplay",
    "SceRnpsAppMgr",
    "SceRnpsInjectedBundle",
    "SceRnpsNKInjectedBundle",
    "SceRtc",
    "SceRudp",
    "SceSaveData",
    "SceSaveDataDialog",
    "SceScm",
    "SceScreenShot",
    "SceScreenShotDrc",
    "SceShareFactoryUtil",
    "SceSharePlay",
    "SceSharePlayCompat",
    "SceShareUtility",
    "SceShellCoreUtil",
    "SceSigninDialog",
    "SceSocialScreen",
    "SceSocialScreenDialog",
    "SceSpSysCallWrapper",
    "SceSrcUtl",
    "SceSsl",
    "SceSysCore",
    "SceSysUtil",
    "SceSysmodule",
    "SceSystemGesture",
    "SceSystemLogger",
    "SceSystemLogger2",
    "SceSystemService",
    "SceSystemServiceActivateHevc",
    "SceSystemServiceActivateHevcSoft",
    "SceSystemServiceActivateMpeg2",
    "SceSystemServiceAppLaunchLink",
    "SceSystemServiceClosedCaption",
    "SceSystemServiceDbg",
    "SceSystemServiceEyeToEyeDistance",
    "SceSystemServiceForShellCoreOnly",
    "SceSystemServicePartyVoice",
    "SceSystemServicePlatformPrivacy",
    "SceSystemServicePowerControl",
    "SceSystemServicePowerSaveLevel",
    "SceSystemServicePs2Emu",
    "SceSystemServicePsmKit",
    "SceSystemServiceStore",
    "SceSystemServiceSuspend",
    "SceSystemServiceTelemetry",
    "SceSystemServiceTournamentMlg",
    "SceSystemServiceUdsApp",
    "SceSystemServiceVideoServiceWebApp",
    "SceSystemServiceVideoToken",
    "SceSystemServiceVoiceRecognition",
    "SceSystemServiceWebApp",
    "SceSystemServiceWebBrowser",
    "SceSystemService_jvm",
    "SceSystemStateMgr",
    "SceTextToSpeech",
    "SceUlt",
    "SceUpdateService",
    "SceUsbStorage",
    "SceUsbStorageAux",
    "SceUsbStorageDialog",
    "SceUsbd",
    "SceUserService",
    "SceUserServiceForNpToolkit",
    "SceUserServiceForShellCore",
    "SceUserServiceRegisteredUserIdList",
    "SceVdecCore",
    "SceVdecSavc",
    "SceVdecSavc2",
    "SceVdecShevc",
    "SceVdecsw",
    "SceVdecwrap",
    "SceVideoCoreInterface",
    "SceVideoCoreServerInterface",
    "SceVideoDecoderArbitration",
    "SceVideoNativeExtEssential",
    "SceVideoOut",
    "SceVideoOutAniso",
    "SceVideoOutBaseMode4k",
    "SceVideoOutExtra",
    "SceVideoOutHdr",
    "SceVideoOutRawEdid",
    "SceVideoRecording",
    "SceVideodec",
    "SceVideodec2",
    "SceVnaInternal",
    "SceVoice",
    "SceVoiceQoS",
    "SceVrServiceDialog",
    "SceVrTracker",
    "SceVrTrackerDeviceRejection",
    "SceVrTrackerFourDeviceAllowed",
    "SceVrTrackerLiveCapture",
    "SceWeb",
    "SceWebBrowserDialog",
    "SceWebBrowserInjectedBundle",
    "SceWebCdlgInjectedBundle",
    "SceWkFontConfig",
    "SceXml",
    "SceZlib",
    "cairo",
    "curl",
    "fontconfig",
    "freetype",
    "harfbuzz",
    "icu",
    "kernel",
    "kernel_avlfmem",
    "kernel_cpumode",
    "kernel_cpumode_platform",
    "kernel_dmem_aliasing",
    "kernel_dmem_aliasing2",
    "kernel_dmem_aliasing2_for_dev",
    "kernel_exception",
    "kernel_jvm",
    "kernel_module_info",
    "kernel_module_load_check",
    "kernel_pre250mmap",
    "kernel_ps2emu",
    "kernel_psmkit",
    "kernel_qadisc",
    "kernel_sys",
    "kernel_sysc_se",
    "kernel_unity",
    "mono-btls-shared",
    "monosgen",
    "png16",
    "sceHmdReprojectionMultilayer",
    "sceNpEulaDialog",
};

const MUSL_SRC_FILES: []const []const u8 = &.{
    "aio/aio.c",
    "aio/aio_suspend.c",
    "aio/lio_listio.c",
    "complex/__cexp.c",
    "complex/__cexpf.c",
    "complex/cabs.c",
    "complex/cabsf.c",
    "complex/cabsl.c",
    "complex/cacos.c",
    "complex/cacosf.c",
    "complex/cacosh.c",
    "complex/cacoshf.c",
    "complex/cacoshl.c",
    "complex/cacosl.c",
    "complex/carg.c",
    "complex/cargf.c",
    "complex/cargl.c",
    "complex/casin.c",
    "complex/casinf.c",
    "complex/casinh.c",
    "complex/casinhf.c",
    "complex/casinhl.c",
    "complex/casinl.c",
    "complex/catan.c",
    "complex/catanf.c",
    "complex/catanh.c",
    "complex/catanhf.c",
    "complex/catanhl.c",
    "complex/catanl.c",
    "complex/ccos.c",
    "complex/ccosf.c",
    "complex/ccosh.c",
    "complex/ccoshf.c",
    "complex/ccoshl.c",
    "complex/ccosl.c",
    "complex/cexp.c",
    "complex/cexpf.c",
    "complex/cexpl.c",
    "complex/cimag.c",
    "complex/cimagf.c",
    "complex/cimagl.c",
    "complex/clog.c",
    "complex/clogf.c",
    "complex/clogl.c",
    "complex/conj.c",
    "complex/conjf.c",
    "complex/conjl.c",
    "complex/cpow.c",
    "complex/cpowf.c",
    "complex/cpowl.c",
    "complex/cproj.c",
    "complex/cprojf.c",
    "complex/cprojl.c",
    "complex/creal.c",
    "complex/crealf.c",
    "complex/creall.c",
    "complex/csin.c",
    "complex/csinf.c",
    "complex/csinh.c",
    "complex/csinhf.c",
    "complex/csinhl.c",
    "complex/csinl.c",
    "complex/csqrt.c",
    "complex/csqrtf.c",
    "complex/csqrtl.c",
    "complex/ctan.c",
    "complex/ctanf.c",
    "complex/ctanh.c",
    "complex/ctanhf.c",
    "complex/ctanhl.c",
    "complex/ctanl.c",
    "conf/confstr.c",
    "conf/fpathconf.c",
    "conf/legacy.c",
    "conf/pathconf.c",
    "crypt/crypt.c",
    "crypt/crypt_blowfish.c",
    "crypt/crypt_des.c",
    "crypt/crypt_md5.c",
    "crypt/crypt_r.c",
    "crypt/crypt_sha256.c",
    "crypt/crypt_sha512.c",
    "crypt/encrypt.c",
    "ctype/__ctype_b_loc.c",
    "ctype/__ctype_get_mb_cur_max.c",
    "ctype/__ctype_tolower_loc.c",
    "ctype/__ctype_toupper_loc.c",
    "ctype/isalnum.c",
    "ctype/isalpha.c",
    "ctype/isascii.c",
    "ctype/isblank.c",
    "ctype/iscntrl.c",
    "ctype/isdigit.c",
    "ctype/isgraph.c",
    "ctype/islower.c",
    "ctype/isprint.c",
    "ctype/ispunct.c",
    "ctype/isspace.c",
    "ctype/isupper.c",
    "ctype/iswalnum.c",
    "ctype/iswalpha.c",
    "ctype/iswblank.c",
    "ctype/iswcntrl.c",
    "ctype/iswctype.c",
    "ctype/iswdigit.c",
    "ctype/iswgraph.c",
    "ctype/iswlower.c",
    "ctype/iswprint.c",
    "ctype/iswpunct.c",
    "ctype/iswspace.c",
    "ctype/iswupper.c",
    "ctype/iswxdigit.c",
    "ctype/isxdigit.c",
    "ctype/toascii.c",
    "ctype/tolower.c",
    "ctype/toupper.c",
    "ctype/towctrans.c",
    "ctype/wcswidth.c",
    "ctype/wctrans.c",
    "ctype/wcwidth.c",
    "dirent/alphasort.c",
    "dirent/closedir.c",
    "dirent/dirfd.c",
    "dirent/fdopendir.c",
    "dirent/opendir.c",
    "dirent/readdir.c",
    "dirent/readdir_r.c",
    "dirent/rewinddir.c",
    "dirent/scandir.c",
    "dirent/seekdir.c",
    "dirent/telldir.c",
    "dirent/versionsort.c",
    "env/__environ.c",
    "env/__init_tls.c",
    "env/__libc_start_main.c",
    "env/__reset_tls.c",
    "env/__stack_chk_fail.c",
    "env/clearenv.c",
    "env/getenv.c",
    "env/putenv.c",
    "env/secure_getenv.c",
    "env/setenv.c",
    "env/unsetenv.c",
    "errno/__errno_location.c",
    "errno/strerror.c",
    "exit/_Exit.c",
    "exit/abort.c",
    "exit/assert.c",
    "exit/at_quick_exit.c",
    "exit/atexit.c",
    "exit/exit.c",
    "exit/quick_exit.c",
    "fcntl/creat.c",
    "fcntl/fcntl.c",
    "fcntl/open.c",
    "fcntl/openat.c",
    "fcntl/posix_fadvise.c",
    "fcntl/posix_fallocate.c",
    "fenv/__flt_rounds.c",
    "fenv/fegetexceptflag.c",
    "fenv/feholdexcept.c",
    "fenv/fenv.c",
    "fenv/fesetexceptflag.c",
    "fenv/fesetround.c",
    "fenv/feupdateenv.c",
    "internal/defsysinfo.c",
    "internal/floatscan.c",
    "internal/intscan.c",
    "internal/libc.c",
    "internal/procfdname.c",
    "internal/shgetc.c",
    "internal/syscall_ret.c",
    "internal/vdso.c",
    "internal/version.c",
    "ipc/ftok.c",
    "ipc/msgctl.c",
    "ipc/msgget.c",
    "ipc/msgrcv.c",
    "ipc/msgsnd.c",
    "ipc/semctl.c",
    "ipc/semget.c",
    "ipc/semop.c",
    "ipc/semtimedop.c",
    "ipc/shmat.c",
    "ipc/shmctl.c",
    "ipc/shmdt.c",
    "ipc/shmget.c",
    "ldso/__dlsym.c",
    "ldso/dl_iterate_phdr.c",
    "ldso/dladdr.c",
    "ldso/dlclose.c",
    "ldso/dlerror.c",
    "ldso/dlinfo.c",
    "ldso/dlopen.c",
    "ldso/dlsym.c",
    "ldso/tlsdesc.c",
    "legacy/cuserid.c",
    "legacy/daemon.c",
    "legacy/err.c",
    "legacy/euidaccess.c",
    "legacy/ftw.c",
    "legacy/futimes.c",
    "legacy/getdtablesize.c",
    "legacy/getloadavg.c",
    "legacy/getpagesize.c",
    "legacy/getpass.c",
    "legacy/getusershell.c",
    "legacy/isastream.c",
    "legacy/lutimes.c",
    "legacy/ulimit.c",
    "legacy/utmpx.c",
    "legacy/valloc.c",
    "linux/adjtime.c",
    "linux/adjtimex.c",
    "linux/arch_prctl.c",
    "linux/brk.c",
    "linux/cache.c",
    "linux/cap.c",
    "linux/chroot.c",
    "linux/clock_adjtime.c",
    "linux/clone.c",
    "linux/copy_file_range.c",
    "linux/epoll.c",
    "linux/eventfd.c",
    "linux/fallocate.c",
    "linux/fanotify.c",
    "linux/flock.c",
    "linux/getdents.c",
    "linux/getrandom.c",
    "linux/inotify.c",
    "linux/ioperm.c",
    "linux/iopl.c",
    "linux/klogctl.c",
    "linux/membarrier.c",
    "linux/memfd_create.c",
    "linux/mlock2.c",
    "linux/module.c",
    "linux/mount.c",
    "linux/name_to_handle_at.c",
    "linux/open_by_handle_at.c",
    "linux/personality.c",
    "linux/pivot_root.c",
    "linux/ppoll.c",
    "linux/prctl.c",
    "linux/prlimit.c",
    "linux/process_vm.c",
    "linux/ptrace.c",
    "linux/quotactl.c",
    "linux/readahead.c",
    "linux/reboot.c",
    "linux/remap_file_pages.c",
    "linux/sbrk.c",
    "linux/sendfile.c",
    "linux/setfsgid.c",
    "linux/setfsuid.c",
    "linux/setgroups.c",
    "linux/sethostname.c",
    "linux/setns.c",
    "linux/settimeofday.c",
    "linux/signalfd.c",
    "linux/splice.c",
    "linux/stime.c",
    "linux/swap.c",
    "linux/sync_file_range.c",
    "linux/syncfs.c",
    "linux/sysinfo.c",
    "linux/tee.c",
    "linux/timerfd.c",
    "linux/unshare.c",
    "linux/utimes.c",
    "linux/vhangup.c",
    "linux/vmsplice.c",
    "linux/wait3.c",
    "linux/wait4.c",
    "linux/xattr.c",
    "locale/__lctrans.c",
    "locale/__mo_lookup.c",
    "locale/bind_textdomain_codeset.c",
    "locale/c_locale.c",
    "locale/catclose.c",
    "locale/catgets.c",
    "locale/catopen.c",
    "locale/dcngettext.c",
    "locale/duplocale.c",
    "locale/freelocale.c",
    "locale/iconv.c",
    "locale/iconv_close.c",
    "locale/langinfo.c",
    "locale/locale_map.c",
    "locale/localeconv.c",
    "locale/newlocale.c",
    "locale/pleval.c",
    "locale/setlocale.c",
    "locale/strcoll.c",
    "locale/strfmon.c",
    "locale/strxfrm.c",
    "locale/textdomain.c",
    "locale/uselocale.c",
    "locale/wcscoll.c",
    "locale/wcsxfrm.c",
    "malloc/aligned_alloc.c",
    "malloc/expand_heap.c",
    "malloc/lite_malloc.c",
    "malloc/malloc.c",
    "malloc/malloc_usable_size.c",
    "malloc/memalign.c",
    "malloc/posix_memalign.c",
    "math/__cos.c",
    "math/__cosdf.c",
    "math/__cosl.c",
    "math/__expo2.c",
    "math/__expo2f.c",
    "math/__fpclassify.c",
    "math/__fpclassifyf.c",
    "math/__fpclassifyl.c",
    "math/__invtrigl.c",
    "math/__math_divzero.c",
    "math/__math_divzerof.c",
    "math/__math_invalid.c",
    "math/__math_invalidf.c",
    "math/__math_oflow.c",
    "math/__math_oflowf.c",
    "math/__math_uflow.c",
    "math/__math_uflowf.c",
    "math/__math_xflow.c",
    "math/__math_xflowf.c",
    "math/__polevll.c",
    "math/__rem_pio2.c",
    "math/__rem_pio2_large.c",
    "math/__rem_pio2f.c",
    "math/__rem_pio2l.c",
    "math/__signbit.c",
    "math/__signbitf.c",
    "math/__signbitl.c",
    "math/__sin.c",
    "math/__sindf.c",
    "math/__sinl.c",
    "math/__tan.c",
    "math/__tandf.c",
    "math/__tanl.c",
    "math/acos.c",
    "math/acosf.c",
    "math/acosh.c",
    "math/acoshf.c",
    "math/acoshl.c",
    "math/acosl.c",
    "math/asin.c",
    "math/asinf.c",
    "math/asinh.c",
    "math/asinhf.c",
    "math/asinhl.c",
    "math/asinl.c",
    "math/atan.c",
    "math/atan2.c",
    "math/atan2f.c",
    "math/atan2l.c",
    "math/atanf.c",
    "math/atanh.c",
    "math/atanhf.c",
    "math/atanhl.c",
    "math/atanl.c",
    "math/cbrt.c",
    "math/cbrtf.c",
    "math/cbrtl.c",
    "math/ceil.c",
    "math/ceilf.c",
    "math/ceill.c",
    "math/copysign.c",
    "math/copysignf.c",
    "math/copysignl.c",
    "math/cos.c",
    "math/cosf.c",
    "math/cosh.c",
    "math/coshf.c",
    "math/coshl.c",
    "math/cosl.c",
    "math/erf.c",
    "math/erff.c",
    "math/erfl.c",
    "math/exp.c",
    "math/exp10.c",
    "math/exp10f.c",
    "math/exp10l.c",
    "math/exp2.c",
    "math/exp2f.c",
    "math/exp2f_data.c",
    "math/exp2l.c",
    "math/exp_data.c",
    "math/expf.c",
    "math/expl.c",
    "math/expm1.c",
    "math/expm1f.c",
    "math/expm1l.c",
    "math/fabs.c",
    "math/fabsf.c",
    "math/fabsl.c",
    "math/fdim.c",
    "math/fdimf.c",
    "math/fdiml.c",
    "math/finite.c",
    "math/finitef.c",
    "math/floor.c",
    "math/floorf.c",
    "math/floorl.c",
    "math/fma.c",
    "math/fmaf.c",
    "math/fmal.c",
    "math/fmax.c",
    "math/fmaxf.c",
    "math/fmaxl.c",
    "math/fmin.c",
    "math/fminf.c",
    "math/fminl.c",
    "math/fmod.c",
    "math/fmodf.c",
    "math/fmodl.c",
    "math/frexp.c",
    "math/frexpf.c",
    "math/frexpl.c",
    "math/hypot.c",
    "math/hypotf.c",
    "math/hypotl.c",
    "math/i386/fabs.c",
    "math/i386/fabsf.c",
    "math/i386/fabsl.c",
    "math/i386/fmod.c",
    "math/i386/fmodf.c",
    "math/i386/fmodl.c",
    "math/i386/llrint.c",
    "math/i386/llrintf.c",
    "math/i386/llrintl.c",
    "math/i386/lrint.c",
    "math/i386/lrintf.c",
    "math/i386/lrintl.c",
    "math/i386/remainder.c",
    "math/i386/remainderf.c",
    "math/i386/remainderl.c",
    "math/i386/rint.c",
    "math/i386/rintf.c",
    "math/i386/rintl.c",
    "math/i386/sqrt.c",
    "math/i386/sqrtf.c",
    "math/i386/sqrtl.c",
    "math/ilogb.c",
    "math/ilogbf.c",
    "math/ilogbl.c",
    "math/j0.c",
    "math/j0f.c",
    "math/j1.c",
    "math/j1f.c",
    "math/jn.c",
    "math/jnf.c",
    "math/ldexp.c",
    "math/ldexpf.c",
    "math/ldexpl.c",
    "math/lgamma.c",
    "math/lgamma_r.c",
    "math/lgammaf.c",
    "math/lgammaf_r.c",
    "math/lgammal.c",
    "math/llrint.c",
    "math/llrintf.c",
    "math/llrintl.c",
    "math/llround.c",
    "math/llroundf.c",
    "math/llroundl.c",
    "math/log.c",
    "math/log10.c",
    "math/log10f.c",
    "math/log10l.c",
    "math/log1p.c",
    "math/log1pf.c",
    "math/log1pl.c",
    "math/log2.c",
    "math/log2_data.c",
    "math/log2f.c",
    "math/log2f_data.c",
    "math/log2l.c",
    "math/log_data.c",
    "math/logb.c",
    "math/logbf.c",
    "math/logbl.c",
    "math/logf.c",
    "math/logf_data.c",
    "math/logl.c",
    "math/lrint.c",
    "math/lrintf.c",
    "math/lrintl.c",
    "math/lround.c",
    "math/lroundf.c",
    "math/lroundl.c",
    "math/modf.c",
    "math/modff.c",
    "math/modfl.c",
    "math/nan.c",
    "math/nanf.c",
    "math/nanl.c",
    "math/nearbyint.c",
    "math/nearbyintf.c",
    "math/nearbyintl.c",
    "math/nextafter.c",
    "math/nextafterf.c",
    "math/nextafterl.c",
    "math/nexttoward.c",
    "math/nexttowardf.c",
    "math/nexttowardl.c",
    "math/pow.c",
    "math/pow_data.c",
    "math/powf.c",
    "math/powf_data.c",
    "math/powl.c",
    "math/remainder.c",
    "math/remainderf.c",
    "math/remainderl.c",
    "math/remquo.c",
    "math/remquof.c",
    "math/remquol.c",
    "math/rint.c",
    "math/rintf.c",
    "math/rintl.c",
    "math/round.c",
    "math/roundf.c",
    "math/roundl.c",
    "math/scalb.c",
    "math/scalbf.c",
    "math/scalbln.c",
    "math/scalblnf.c",
    "math/scalblnl.c",
    "math/scalbn.c",
    "math/scalbnf.c",
    "math/scalbnl.c",
    "math/signgam.c",
    "math/significand.c",
    "math/significandf.c",
    "math/sin.c",
    "math/sincos.c",
    "math/sincosf.c",
    "math/sincosl.c",
    "math/sinf.c",
    "math/sinh.c",
    "math/sinhf.c",
    "math/sinhl.c",
    "math/sinl.c",
    "math/sqrt.c",
    "math/sqrtf.c",
    "math/sqrtl.c",
    "math/tan.c",
    "math/tanf.c",
    "math/tanh.c",
    "math/tanhf.c",
    "math/tanhl.c",
    "math/tanl.c",
    "math/tgamma.c",
    "math/tgammaf.c",
    "math/tgammal.c",
    "math/trunc.c",
    "math/truncf.c",
    "math/truncl.c",
    "math/x86_64/fabs.c",
    "math/x86_64/fabsf.c",
    "math/x86_64/fabsl.c",
    "math/x86_64/fma.c",
    "math/x86_64/fmaf.c",
    "math/x86_64/fmodl.c",
    "math/x86_64/llrint.c",
    "math/x86_64/llrintf.c",
    "math/x86_64/llrintl.c",
    "math/x86_64/lrint.c",
    "math/x86_64/lrintf.c",
    "math/x86_64/lrintl.c",
    "math/x86_64/remainderl.c",
    "math/x86_64/remquol.c",
    "math/x86_64/rintl.c",
    "math/x86_64/sqrt.c",
    "math/x86_64/sqrtf.c",
    "math/x86_64/sqrtl.c",
    "misc/a64l.c",
    "misc/basename.c",
    "misc/dirname.c",
    "misc/ffs.c",
    "misc/ffsl.c",
    "misc/ffsll.c",
    "misc/fmtmsg.c",
    "misc/forkpty.c",
    "misc/get_current_dir_name.c",
    "misc/getauxval.c",
    "misc/getdomainname.c",
    "misc/getentropy.c",
    "misc/gethostid.c",
    "misc/getopt.c",
    "misc/getopt_long.c",
    "misc/getpriority.c",
    "misc/getresgid.c",
    "misc/getresuid.c",
    "misc/getrlimit.c",
    "misc/getrusage.c",
    "misc/getsubopt.c",
    "misc/initgroups.c",
    "misc/issetugid.c",
    "misc/lockf.c",
    "misc/login_tty.c",
    "misc/mntent.c",
    "misc/nftw.c",
    "misc/openpty.c",
    "misc/ptsname.c",
    "misc/pty.c",
    "misc/realpath.c",
    "misc/setdomainname.c",
    "misc/setpriority.c",
    "misc/setrlimit.c",
    "misc/syscall.c",
    "misc/syslog.c",
    "misc/uname.c",
    "misc/wordexp.c",
    "mman/madvise.c",
    "mman/mincore.c",
    "mman/mlock.c",
    "mman/mlockall.c",
    "mman/mmap.c",
    "mman/mprotect.c",
    "mman/mremap.c",
    "mman/msync.c",
    "mman/munlock.c",
    "mman/munlockall.c",
    "mman/munmap.c",
    "mman/posix_madvise.c",
    "mman/shm_open.c",
    "mq/mq_close.c",
    "mq/mq_getattr.c",
    "mq/mq_notify.c",
    "mq/mq_open.c",
    "mq/mq_receive.c",
    "mq/mq_send.c",
    "mq/mq_setattr.c",
    "mq/mq_timedreceive.c",
    "mq/mq_timedsend.c",
    "mq/mq_unlink.c",
    "multibyte/btowc.c",
    "multibyte/c16rtomb.c",
    "multibyte/c32rtomb.c",
    "multibyte/internal.c",
    "multibyte/mblen.c",
    "multibyte/mbrlen.c",
    "multibyte/mbrtoc16.c",
    "multibyte/mbrtoc32.c",
    "multibyte/mbrtowc.c",
    "multibyte/mbsinit.c",
    "multibyte/mbsnrtowcs.c",
    "multibyte/mbsrtowcs.c",
    "multibyte/mbstowcs.c",
    "multibyte/mbtowc.c",
    "multibyte/wcrtomb.c",
    "multibyte/wcsnrtombs.c",
    "multibyte/wcsrtombs.c",
    "multibyte/wcstombs.c",
    "multibyte/wctob.c",
    "multibyte/wctomb.c",
    "network/accept.c",
    "network/accept4.c",
    "network/bind.c",
    "network/connect.c",
    "network/dn_comp.c",
    "network/dn_expand.c",
    "network/dn_skipname.c",
    "network/dns_parse.c",
    "network/ent.c",
    "network/ether.c",
    "network/freeaddrinfo.c",
    "network/gai_strerror.c",
    "network/getaddrinfo.c",
    "network/gethostbyaddr.c",
    "network/gethostbyaddr_r.c",
    "network/gethostbyname.c",
    "network/gethostbyname2.c",
    "network/gethostbyname2_r.c",
    "network/gethostbyname_r.c",
    "network/getifaddrs.c",
    "network/getnameinfo.c",
    "network/getpeername.c",
    "network/getservbyname.c",
    "network/getservbyname_r.c",
    "network/getservbyport.c",
    "network/getservbyport_r.c",
    "network/getsockname.c",
    "network/getsockopt.c",
    "network/h_errno.c",
    "network/herror.c",
    "network/hstrerror.c",
    "network/htonl.c",
    "network/htons.c",
    "network/if_freenameindex.c",
    "network/if_indextoname.c",
    "network/if_nameindex.c",
    "network/if_nametoindex.c",
    "network/in6addr_any.c",
    "network/in6addr_loopback.c",
    "network/inet_addr.c",
    "network/inet_aton.c",
    "network/inet_legacy.c",
    "network/inet_ntoa.c",
    "network/inet_ntop.c",
    "network/inet_pton.c",
    "network/listen.c",
    "network/lookup_ipliteral.c",
    "network/lookup_name.c",
    "network/lookup_serv.c",
    "network/netlink.c",
    "network/netname.c",
    "network/ns_parse.c",
    "network/ntohl.c",
    "network/ntohs.c",
    "network/proto.c",
    "network/recv.c",
    "network/recvfrom.c",
    "network/recvmmsg.c",
    "network/recvmsg.c",
    "network/res_init.c",
    "network/res_mkquery.c",
    "network/res_msend.c",
    "network/res_query.c",
    "network/res_querydomain.c",
    "network/res_send.c",
    "network/res_state.c",
    "network/resolvconf.c",
    "network/send.c",
    "network/sendmmsg.c",
    "network/sendmsg.c",
    "network/sendto.c",
    "network/serv.c",
    "network/setsockopt.c",
    "network/shutdown.c",
    "network/sockatmark.c",
    "network/socket.c",
    "network/socketpair.c",
    "passwd/fgetgrent.c",
    "passwd/fgetpwent.c",
    "passwd/fgetspent.c",
    "passwd/getgr_a.c",
    "passwd/getgr_r.c",
    "passwd/getgrent.c",
    "passwd/getgrent_a.c",
    "passwd/getgrouplist.c",
    "passwd/getpw_a.c",
    "passwd/getpw_r.c",
    "passwd/getpwent.c",
    "passwd/getpwent_a.c",
    "passwd/getspent.c",
    "passwd/getspnam.c",
    "passwd/getspnam_r.c",
    "passwd/lckpwdf.c",
    "passwd/nscd_query.c",
    "passwd/putgrent.c",
    "passwd/putpwent.c",
    "passwd/putspent.c",
    "prng/__rand48_step.c",
    "prng/__seed48.c",
    "prng/drand48.c",
    "prng/lcong48.c",
    "prng/lrand48.c",
    "prng/mrand48.c",
    "prng/rand.c",
    "prng/rand_r.c",
    "prng/random.c",
    "prng/seed48.c",
    "prng/srand48.c",
    "process/execl.c",
    "process/execle.c",
    "process/execlp.c",
    "process/execv.c",
    "process/execve.c",
    "process/execvp.c",
    "process/fexecve.c",
    "process/fork.c",
    "process/posix_spawn.c",
    "process/posix_spawn_file_actions_addchdir.c",
    "process/posix_spawn_file_actions_addclose.c",
    "process/posix_spawn_file_actions_adddup2.c",
    "process/posix_spawn_file_actions_addfchdir.c",
    "process/posix_spawn_file_actions_addopen.c",
    "process/posix_spawn_file_actions_destroy.c",
    "process/posix_spawn_file_actions_init.c",
    "process/posix_spawnattr_destroy.c",
    "process/posix_spawnattr_getflags.c",
    "process/posix_spawnattr_getpgroup.c",
    "process/posix_spawnattr_getsigdefault.c",
    "process/posix_spawnattr_getsigmask.c",
    "process/posix_spawnattr_init.c",
    "process/posix_spawnattr_sched.c",
    "process/posix_spawnattr_setflags.c",
    "process/posix_spawnattr_setpgroup.c",
    "process/posix_spawnattr_setsigdefault.c",
    "process/posix_spawnattr_setsigmask.c",
    "process/posix_spawnp.c",
    "process/system.c",
    "process/vfork.c",
    "process/wait.c",
    "process/waitid.c",
    "process/waitpid.c",
    "regex/fnmatch.c",
    "regex/glob.c",
    "regex/regcomp.c",
    "regex/regerror.c",
    "regex/regexec.c",
    "regex/tre-mem.c",
    "sched/affinity.c",
    "sched/sched_cpucount.c",
    "sched/sched_get_priority_max.c",
    "sched/sched_getcpu.c",
    "sched/sched_getparam.c",
    "sched/sched_getscheduler.c",
    "sched/sched_rr_get_interval.c",
    "sched/sched_setparam.c",
    "sched/sched_setscheduler.c",
    "sched/sched_yield.c",
    "search/hsearch.c",
    "search/insque.c",
    "search/lsearch.c",
    "search/tdelete.c",
    "search/tdestroy.c",
    "search/tfind.c",
    "search/tsearch.c",
    "search/twalk.c",
    "select/poll.c",
    "select/pselect.c",
    "select/select.c",
    "setjmp/longjmp.c",
    "setjmp/setjmp.c",
    "signal/block.c",
    "signal/getitimer.c",
    "signal/kill.c",
    "signal/killpg.c",
    "signal/psiginfo.c",
    "signal/psignal.c",
    "signal/raise.c",
    "signal/restore.c",
    "signal/setitimer.c",
    "signal/sigaction.c",
    "signal/sigaddset.c",
    "signal/sigaltstack.c",
    "signal/sigandset.c",
    "signal/sigdelset.c",
    "signal/sigemptyset.c",
    "signal/sigfillset.c",
    "signal/sighold.c",
    "signal/sigignore.c",
    "signal/siginterrupt.c",
    "signal/sigisemptyset.c",
    "signal/sigismember.c",
    "signal/siglongjmp.c",
    "signal/signal.c",
    "signal/sigorset.c",
    "signal/sigpause.c",
    "signal/sigpending.c",
    "signal/sigprocmask.c",
    "signal/sigqueue.c",
    "signal/sigrelse.c",
    "signal/sigrtmax.c",
    "signal/sigrtmin.c",
    "signal/sigset.c",
    "signal/sigsetjmp.c",
    "signal/sigsetjmp_tail.c",
    "signal/sigsuspend.c",
    "signal/sigtimedwait.c",
    "signal/sigwait.c",
    "signal/sigwaitinfo.c",
    "stat/__xstat.c",
    "stat/chmod.c",
    "stat/fchmod.c",
    "stat/fchmodat.c",
    "stat/fstat.c",
    "stat/fstatat.c",
    "stat/futimens.c",
    "stat/futimesat.c",
    "stat/lchmod.c",
    "stat/lstat.c",
    "stat/mkdir.c",
    "stat/mkdirat.c",
    "stat/mkfifo.c",
    "stat/mkfifoat.c",
    "stat/mknod.c",
    "stat/mknodat.c",
    "stat/stat.c",
    "stat/statvfs.c",
    "stat/umask.c",
    "stat/utimensat.c",
    "stdio/__fclose_ca.c",
    "stdio/__fdopen.c",
    "stdio/__fmodeflags.c",
    "stdio/__fopen_rb_ca.c",
    "stdio/__lockfile.c",
    "stdio/__overflow.c",
    "stdio/__stdio_close.c",
    "stdio/__stdio_exit.c",
    "stdio/__stdio_read.c",
    "stdio/__stdio_seek.c",
    "stdio/__stdio_write.c",
    "stdio/__stdout_write.c",
    "stdio/__toread.c",
    "stdio/__towrite.c",
    "stdio/__uflow.c",
    "stdio/asprintf.c",
    "stdio/clearerr.c",
    "stdio/dprintf.c",
    "stdio/ext.c",
    "stdio/ext2.c",
    "stdio/fclose.c",
    "stdio/feof.c",
    "stdio/ferror.c",
    "stdio/fflush.c",
    "stdio/fgetc.c",
    "stdio/fgetln.c",
    "stdio/fgetpos.c",
    "stdio/fgets.c",
    "stdio/fgetwc.c",
    "stdio/fgetws.c",
    "stdio/fileno.c",
    "stdio/flockfile.c",
    "stdio/fmemopen.c",
    "stdio/fopen.c",
    "stdio/fopencookie.c",
    "stdio/fprintf.c",
    "stdio/fputc.c",
    "stdio/fputs.c",
    "stdio/fputwc.c",
    "stdio/fputws.c",
    "stdio/fread.c",
    "stdio/freopen.c",
    "stdio/fscanf.c",
    "stdio/fseek.c",
    "stdio/fsetpos.c",
    "stdio/ftell.c",
    "stdio/ftrylockfile.c",
    "stdio/funlockfile.c",
    "stdio/fwide.c",
    "stdio/fwprintf.c",
    "stdio/fwrite.c",
    "stdio/fwscanf.c",
    "stdio/getc.c",
    "stdio/getc_unlocked.c",
    "stdio/getchar.c",
    "stdio/getchar_unlocked.c",
    "stdio/getdelim.c",
    "stdio/getline.c",
    "stdio/gets.c",
    "stdio/getw.c",
    "stdio/getwc.c",
    "stdio/getwchar.c",
    "stdio/ofl.c",
    "stdio/ofl_add.c",
    "stdio/open_memstream.c",
    "stdio/open_wmemstream.c",
    "stdio/pclose.c",
    "stdio/perror.c",
    "stdio/popen.c",
    "stdio/printf.c",
    "stdio/putc.c",
    "stdio/putc_unlocked.c",
    "stdio/putchar.c",
    "stdio/putchar_unlocked.c",
    "stdio/puts.c",
    "stdio/putw.c",
    "stdio/putwc.c",
    "stdio/putwchar.c",
    "stdio/remove.c",
    "stdio/rename.c",
    "stdio/rewind.c",
    "stdio/scanf.c",
    "stdio/setbuf.c",
    "stdio/setbuffer.c",
    "stdio/setlinebuf.c",
    "stdio/setvbuf.c",
    "stdio/snprintf.c",
    "stdio/sprintf.c",
    "stdio/sscanf.c",
    "stdio/stderr.c",
    "stdio/stdin.c",
    "stdio/stdout.c",
    "stdio/swprintf.c",
    "stdio/swscanf.c",
    "stdio/tempnam.c",
    "stdio/tmpfile.c",
    "stdio/tmpnam.c",
    "stdio/ungetc.c",
    "stdio/ungetwc.c",
    "stdio/vasprintf.c",
    "stdio/vdprintf.c",
    "stdio/vfprintf.c",
    "stdio/vfscanf.c",
    "stdio/vfwprintf.c",
    "stdio/vfwscanf.c",
    "stdio/vprintf.c",
    "stdio/vscanf.c",
    "stdio/vsnprintf.c",
    "stdio/vsprintf.c",
    "stdio/vsscanf.c",
    "stdio/vswprintf.c",
    "stdio/vswscanf.c",
    "stdio/vwprintf.c",
    "stdio/vwscanf.c",
    "stdio/wprintf.c",
    "stdio/wscanf.c",
    "stdlib/abs.c",
    "stdlib/atof.c",
    "stdlib/atoi.c",
    "stdlib/atol.c",
    "stdlib/atoll.c",
    "stdlib/bsearch.c",
    "stdlib/div.c",
    "stdlib/ecvt.c",
    "stdlib/fcvt.c",
    "stdlib/gcvt.c",
    "stdlib/imaxabs.c",
    "stdlib/imaxdiv.c",
    "stdlib/labs.c",
    "stdlib/ldiv.c",
    "stdlib/llabs.c",
    "stdlib/lldiv.c",
    "stdlib/qsort.c",
    "stdlib/strtod.c",
    "stdlib/strtol.c",
    "stdlib/wcstod.c",
    "stdlib/wcstol.c",
    "string/bcmp.c",
    "string/bcopy.c",
    "string/bzero.c",
    "string/explicit_bzero.c",
    "string/index.c",
    "string/memccpy.c",
    "string/memchr.c",
    "string/memcmp.c",
    "string/memcpy.c",
    "string/memmem.c",
    "string/memmove.c",
    "string/mempcpy.c",
    "string/memrchr.c",
    "string/memset.c",
    "string/rindex.c",
    "string/stpcpy.c",
    "string/stpncpy.c",
    "string/strcasecmp.c",
    "string/strcasestr.c",
    "string/strcat.c",
    "string/strchr.c",
    "string/strchrnul.c",
    "string/strcmp.c",
    "string/strcpy.c",
    "string/strcspn.c",
    "string/strdup.c",
    "string/strerror_r.c",
    "string/strlcat.c",
    "string/strlcpy.c",
    "string/strlen.c",
    "string/strncasecmp.c",
    "string/strncat.c",
    "string/strncmp.c",
    "string/strncpy.c",
    "string/strndup.c",
    "string/strnlen.c",
    "string/strpbrk.c",
    "string/strrchr.c",
    "string/strsep.c",
    "string/strsignal.c",
    "string/strspn.c",
    "string/strstr.c",
    "string/strtok.c",
    "string/strtok_r.c",
    "string/strverscmp.c",
    "string/swab.c",
    "string/wcpcpy.c",
    "string/wcpncpy.c",
    "string/wcscasecmp.c",
    "string/wcscasecmp_l.c",
    "string/wcscat.c",
    "string/wcschr.c",
    "string/wcscmp.c",
    "string/wcscpy.c",
    "string/wcscspn.c",
    "string/wcsdup.c",
    "string/wcslen.c",
    "string/wcsncasecmp.c",
    "string/wcsncasecmp_l.c",
    "string/wcsncat.c",
    "string/wcsncmp.c",
    "string/wcsncpy.c",
    "string/wcsnlen.c",
    "string/wcspbrk.c",
    "string/wcsrchr.c",
    "string/wcsspn.c",
    "string/wcsstr.c",
    "string/wcstok.c",
    "string/wcswcs.c",
    "string/wmemchr.c",
    "string/wmemcmp.c",
    "string/wmemcpy.c",
    "string/wmemmove.c",
    "string/wmemset.c",
    "temp/__randname.c",
    "temp/mkdtemp.c",
    "temp/mkostemp.c",
    "temp/mkostemps.c",
    "temp/mkstemp.c",
    "temp/mkstemps.c",
    "temp/mktemp.c",
    "termios/cfgetospeed.c",
    "termios/cfmakeraw.c",
    "termios/cfsetospeed.c",
    "thread/__lock.c",
    // "thread/__set_thread_area.c",
    // "thread/__syscall_cp.c",
    // "thread/__timedwait.c",
    // "thread/__tls_get_addr.c",
    // "thread/__unmapself.c",
    "thread/__wait.c",
    // "thread/call_once.c",
    // "thread/clone.c",
    // "thread/cnd_broadcast.c",
    // "thread/cnd_destroy.c",
    // "thread/cnd_init.c",
    // "thread/cnd_signal.c",
    // "thread/cnd_timedwait.c",
    // "thread/cnd_wait.c",
    // "thread/default_attr.c",
    // "thread/lock_ptc.c",
    // "thread/mtx_destroy.c",
    // "thread/mtx_init.c",
    // "thread/mtx_lock.c",
    // "thread/mtx_timedlock.c",
    // "thread/mtx_trylock.c",
    // "thread/mtx_unlock.c",
    "thread/ps4/musl_current_locale.c",
    "thread/ps4/pthread_atfork.c",
    "thread/ps4/pthread_attr_destroy.c",
    "thread/ps4/pthread_attr_get.c",
    "thread/ps4/pthread_attr_init.c",
    "thread/ps4/pthread_attr_setdetachstate.c",
    "thread/ps4/pthread_attr_setguardsize.c",
    "thread/ps4/pthread_attr_setinheritsched.c",
    "thread/ps4/pthread_attr_setschedparam.c",
    "thread/ps4/pthread_attr_setschedpolicy.c",
    "thread/ps4/pthread_attr_setscope.c",
    "thread/ps4/pthread_attr_setstack.c",
    "thread/ps4/pthread_attr_setstacksize.c",
    "thread/ps4/pthread_barrier_destroy.c",
    "thread/ps4/pthread_barrier_init.c",
    "thread/ps4/pthread_barrier_wait.c",
    "thread/ps4/pthread_barrierattr_destroy.c",
    "thread/ps4/pthread_barrierattr_init.c",
    "thread/ps4/pthread_barrierattr_setpshared.c",
    "thread/ps4/pthread_cancel.c",
    "thread/ps4/pthread_cleanup_push.c",
    "thread/ps4/pthread_cond_broadcast.c",
    "thread/ps4/pthread_cond_destroy.c",
    "thread/ps4/pthread_cond_init.c",
    "thread/ps4/pthread_cond_signal.c",
    "thread/ps4/pthread_cond_timedwait.c",
    "thread/ps4/pthread_cond_wait.c",
    "thread/ps4/pthread_condattr_destroy.c",
    "thread/ps4/pthread_condattr_init.c",
    "thread/ps4/pthread_condattr_setclock.c",
    "thread/ps4/pthread_condattr_setpshared.c",
    "thread/ps4/pthread_create.c",
    "thread/ps4/pthread_detach.c",
    "thread/ps4/pthread_equal.c",
    "thread/ps4/pthread_getattr_np.c",
    "thread/ps4/pthread_getconcurrency.c",
    "thread/ps4/pthread_getcpuclockid.c",
    "thread/ps4/pthread_getschedparam.c",
    "thread/ps4/pthread_getspecific.c",
    "thread/ps4/pthread_join.c",
    "thread/ps4/pthread_key_create.c",
    "thread/ps4/pthread_kill.c",
    "thread/ps4/pthread_mutex_consistent.c",
    "thread/ps4/pthread_mutex_destroy.c",
    "thread/ps4/pthread_mutex_getprioceiling.c",
    "thread/ps4/pthread_mutex_init.c",
    "thread/ps4/pthread_mutex_lock.c",
    "thread/ps4/pthread_mutex_setprioceiling.c",
    "thread/ps4/pthread_mutex_timedlock.c",
    "thread/ps4/pthread_mutex_trylock.c",
    "thread/ps4/pthread_mutex_unlock.c",
    "thread/ps4/pthread_mutexattr_destroy.c",
    "thread/ps4/pthread_mutexattr_init.c",
    "thread/ps4/pthread_mutexattr_setprotocol.c",
    "thread/ps4/pthread_mutexattr_setpshared.c",
    "thread/ps4/pthread_mutexattr_setrobust.c",
    "thread/ps4/pthread_mutexattr_settype.c",
    "thread/ps4/pthread_once.c",
    "thread/ps4/pthread_rwlock_destroy.c",
    "thread/ps4/pthread_rwlock_init.c",
    "thread/ps4/pthread_rwlock_rdlock.c",
    "thread/ps4/pthread_rwlock_timedrdlock.c",
    "thread/ps4/pthread_rwlock_timedwrlock.c",
    "thread/ps4/pthread_rwlock_tryrdlock.c",
    "thread/ps4/pthread_rwlock_trywrlock.c",
    "thread/ps4/pthread_rwlock_unlock.c",
    "thread/ps4/pthread_rwlock_wrlock.c",
    "thread/ps4/pthread_rwlockattr_destroy.c",
    "thread/ps4/pthread_rwlockattr_init.c",
    "thread/ps4/pthread_rwlockattr_setpshared.c",
    "thread/ps4/pthread_self.c",
    "thread/ps4/pthread_setattr_default_np.c",
    "thread/ps4/pthread_setcancelstate.c",
    "thread/ps4/pthread_setcanceltype.c",
    "thread/ps4/pthread_setconcurrency.c",
    "thread/ps4/pthread_setname_np.c",
    "thread/ps4/pthread_setschedparam.c",
    "thread/ps4/pthread_setschedprio.c",
    "thread/ps4/pthread_setspecific.c",
    "thread/ps4/pthread_sigmask.c",
    "thread/ps4/pthread_spin_destroy.c",
    "thread/ps4/pthread_spin_init.c",
    "thread/ps4/pthread_spin_lock.c",
    "thread/ps4/pthread_spin_trylock.c",
    "thread/ps4/pthread_spin_unlock.c",
    "thread/ps4/pthread_testcancel.c",
    // "thread/pthread_atfork.c",
    // "thread/pthread_attr_destroy.c",
    // "thread/pthread_attr_get.c",
    // "thread/pthread_attr_init.c",
    // "thread/pthread_attr_setdetachstate.c",
    // "thread/pthread_attr_setguardsize.c",
    // "thread/pthread_attr_setinheritsched.c",
    // "thread/pthread_attr_setschedparam.c",
    // "thread/pthread_attr_setschedpolicy.c",
    // "thread/pthread_attr_setscope.c",
    // "thread/pthread_attr_setstack.c",
    // "thread/pthread_attr_setstacksize.c",
    // "thread/pthread_barrier_destroy.c",
    // "thread/pthread_barrier_init.c",
    // "thread/pthread_barrier_wait.c",
    // "thread/pthread_barrierattr_destroy.c",
    // "thread/pthread_barrierattr_init.c",
    // "thread/pthread_barrierattr_setpshared.c",
    // "thread/pthread_cancel.c",
    // "thread/pthread_cleanup_push.c",
    // "thread/pthread_cond_broadcast.c",
    // "thread/pthread_cond_destroy.c",
    // "thread/pthread_cond_init.c",
    // "thread/pthread_cond_signal.c",
    // "thread/pthread_cond_timedwait.c",
    // "thread/pthread_cond_wait.c",
    // "thread/pthread_condattr_destroy.c",
    // "thread/pthread_condattr_init.c",
    // "thread/pthread_condattr_setclock.c",
    // "thread/pthread_condattr_setpshared.c",
    // "thread/pthread_create.c",
    // "thread/pthread_detach.c",
    // "thread/pthread_equal.c",
    // "thread/pthread_getattr_np.c",
    // "thread/pthread_getconcurrency.c",
    // "thread/pthread_getcpuclockid.c",
    // "thread/pthread_getschedparam.c",
    // "thread/pthread_getspecific.c",
    // "thread/pthread_join.c",
    // "thread/pthread_key_create.c",
    // "thread/pthread_kill.c",
    // "thread/pthread_mutex_consistent.c",
    // "thread/pthread_mutex_destroy.c",
    // "thread/pthread_mutex_getprioceiling.c",
    // "thread/pthread_mutex_init.c",
    // "thread/pthread_mutex_lock.c",
    // "thread/pthread_mutex_setprioceiling.c",
    // "thread/pthread_mutex_timedlock.c",
    // "thread/pthread_mutex_trylock.c",
    // "thread/pthread_mutex_unlock.c",
    // "thread/pthread_mutexattr_destroy.c",
    // "thread/pthread_mutexattr_init.c",
    // "thread/pthread_mutexattr_setprotocol.c",
    // "thread/pthread_mutexattr_setpshared.c",
    // "thread/pthread_mutexattr_setrobust.c",
    // "thread/pthread_mutexattr_settype.c",
    // "thread/pthread_once.c",
    // "thread/pthread_rwlock_destroy.c",
    // "thread/pthread_rwlock_init.c",
    // "thread/pthread_rwlock_rdlock.c",
    // "thread/pthread_rwlock_timedrdlock.c",
    // "thread/pthread_rwlock_timedwrlock.c",
    // "thread/pthread_rwlock_tryrdlock.c",
    // "thread/pthread_rwlock_trywrlock.c",
    // "thread/pthread_rwlock_unlock.c",
    // "thread/pthread_rwlock_wrlock.c",
    // "thread/pthread_rwlockattr_destroy.c",
    // "thread/pthread_rwlockattr_init.c",
    // "thread/pthread_rwlockattr_setpshared.c",
    // "thread/pthread_self.c",
    // "thread/pthread_setattr_default_np.c",
    // "thread/pthread_setcancelstate.c",
    // "thread/pthread_setcanceltype.c",
    // "thread/pthread_setconcurrency.c",
    // "thread/pthread_setname_np.c",
    // "thread/pthread_setschedparam.c",
    // "thread/pthread_setschedprio.c",
    // "thread/pthread_setspecific.c",
    // "thread/pthread_sigmask.c",
    // "thread/pthread_spin_destroy.c",
    // "thread/pthread_spin_init.c",
    // "thread/pthread_spin_lock.c",
    // "thread/pthread_spin_trylock.c",
    // "thread/pthread_spin_unlock.c",
    // "thread/pthread_testcancel.c",
    "thread/sem_destroy.c",
    "thread/sem_getvalue.c",
    "thread/sem_init.c",
    "thread/sem_open.c",
    "thread/sem_post.c",
    "thread/sem_timedwait.c",
    "thread/sem_trywait.c",
    "thread/sem_unlink.c",
    "thread/sem_wait.c",
    // "thread/synccall.c",
    // "thread/syscall_cp.c",
    // "thread/thrd_create.c",
    // "thread/thrd_exit.c",
    // "thread/thrd_join.c",
    // "thread/thrd_sleep.c",
    // "thread/thrd_yield.c",
    // "thread/tls.c",
    // "thread/tss_create.c",
    // "thread/tss_delete.c",
    // "thread/tss_set.c",
    // "thread/vmlock.c",
    "time/__map_file.c",
    "time/__month_to_secs.c",
    "time/__secs_to_tm.c",
    "time/__tm_to_secs.c",
    "time/__tz.c",
    "time/__year_to_secs.c",
    "time/asctime.c",
    "time/asctime_r.c",
    "time/clock.c",
    "time/clock_getcpuclockid.c",
    "time/clock_getres.c",
    "time/clock_gettime.c",
    "time/clock_nanosleep.c",
    "time/clock_settime.c",
    "time/ctime.c",
    "time/ctime_r.c",
    "time/difftime.c",
    "time/ftime.c",
    "time/getdate.c",
    "time/gettimeofday.c",
    "time/gmtime.c",
    "time/gmtime_r.c",
    "time/localtime.c",
    "time/localtime_r.c",
    "time/mktime.c",
    "time/nanosleep.c",
    "time/strftime.c",
    "time/strptime.c",
    "time/time.c",
    "time/timegm.c",
    "time/timer_create.c",
    "time/timer_delete.c",
    "time/timer_getoverrun.c",
    "time/timer_gettime.c",
    "time/timer_settime.c",
    "time/times.c",
    "time/timespec_get.c",
    "time/utime.c",
    "time/wcsftime.c",
    "unistd/_exit.c",
    "unistd/access.c",
    "unistd/acct.c",
    "unistd/alarm.c",
    "unistd/chdir.c",
    "unistd/chown.c",
    "unistd/close.c",
    "unistd/ctermid.c",
    "unistd/dup.c",
    "unistd/dup2.c",
    "unistd/dup3.c",
    "unistd/faccessat.c",
    "unistd/fchdir.c",
    "unistd/fchown.c",
    "unistd/fchownat.c",
    "unistd/fdatasync.c",
    "unistd/fsync.c",
    "unistd/ftruncate.c",
    "unistd/getcwd.c",
    "unistd/getegid.c",
    "unistd/geteuid.c",
    "unistd/getgid.c",
    "unistd/getgroups.c",
    "unistd/gethostname.c",
    "unistd/getlogin.c",
    "unistd/getlogin_r.c",
    "unistd/getpgid.c",
    "unistd/getpgrp.c",
    "unistd/getpid.c",
    "unistd/getppid.c",
    "unistd/getsid.c",
    "unistd/getuid.c",
    "unistd/isatty.c",
    "unistd/lchown.c",
    "unistd/link.c",
    "unistd/linkat.c",
    "unistd/lseek.c",
    "unistd/nice.c",
    "unistd/pause.c",
    "unistd/pipe.c",
    "unistd/pipe2.c",
    "unistd/posix_close.c",
    "unistd/pread.c",
    "unistd/preadv.c",
    "unistd/pwrite.c",
    "unistd/pwritev.c",
    "unistd/read.c",
    "unistd/readlink.c",
    "unistd/readlinkat.c",
    "unistd/readv.c",
    "unistd/renameat.c",
    "unistd/rmdir.c",
    "unistd/setegid.c",
    "unistd/seteuid.c",
    "unistd/setgid.c",
    "unistd/setpgid.c",
    "unistd/setpgrp.c",
    "unistd/setregid.c",
    "unistd/setresgid.c",
    "unistd/setresuid.c",
    "unistd/setreuid.c",
    "unistd/setsid.c",
    "unistd/setuid.c",
    "unistd/setxid.c",
    "unistd/sleep.c",
    "unistd/symlink.c",
    "unistd/symlinkat.c",
    "unistd/sync.c",
    "unistd/tcgetpgrp.c",
    "unistd/tcsetpgrp.c",
    "unistd/truncate.c",
    "unistd/ttyname.c",
    "unistd/ttyname_r.c",
    "unistd/ualarm.c",
    "unistd/unlink.c",
    "unistd/unlinkat.c",
    "unistd/usleep.c",
    "unistd/write.c",
    "unistd/writev.c",
};
