/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(curl_easy_cleanup);
FUNC(curl_easy_duphandle);
FUNC(curl_easy_escape);
FUNC(curl_easy_getinfo);
FUNC(curl_easy_init);
FUNC(curl_easy_option_by_id);
FUNC(curl_easy_option_by_name);
FUNC(curl_easy_option_next);
FUNC(curl_easy_pause);
FUNC(curl_easy_perform);
FUNC(curl_easy_recv);
FUNC(curl_easy_reset);
FUNC(curl_easy_send);
FUNC(curl_easy_setopt);
FUNC(curl_easy_strerror);
FUNC(curl_easy_unescape);
FUNC(curl_easy_upkeep);
FUNC(curl_escape);
FUNC(curl_formadd);
FUNC(curl_formfree);
FUNC(curl_formget);
FUNC(curl_free);
FUNC(curl_getdate);
FUNC(curl_getenv);
FUNC(curl_global_cleanup);
FUNC(curl_global_init);
FUNC(curl_global_init_mem);
FUNC(curl_global_sslset);
FUNC(curl_maprintf);
FUNC(curl_mfprintf);
FUNC(curl_mime_addpart);
FUNC(curl_mime_data);
FUNC(curl_mime_data_cb);
FUNC(curl_mime_encoder);
FUNC(curl_mime_filedata);
FUNC(curl_mime_filename);
FUNC(curl_mime_free);
FUNC(curl_mime_headers);
FUNC(curl_mime_init);
FUNC(curl_mime_name);
FUNC(curl_mime_subparts);
FUNC(curl_mime_type);
FUNC(curl_mprintf);
FUNC(curl_msnprintf);
FUNC(curl_msprintf);
FUNC(curl_multi_add_handle);
FUNC(curl_multi_assign);
FUNC(curl_multi_cleanup);
FUNC(curl_multi_fdset);
FUNC(curl_multi_info_read);
FUNC(curl_multi_init);
FUNC(curl_multi_perform);
FUNC(curl_multi_poll);
FUNC(curl_multi_remove_handle);
FUNC(curl_multi_setopt);
FUNC(curl_multi_socket);
FUNC(curl_multi_socket_action);
FUNC(curl_multi_socket_all);
FUNC(curl_multi_strerror);
FUNC(curl_multi_timeout);
FUNC(curl_multi_wait);
FUNC(curl_multi_wakeup);
FUNC(curl_mvaprintf);
FUNC(curl_mvfprintf);
FUNC(curl_mvprintf);
FUNC(curl_mvsnprintf);
FUNC(curl_mvsprintf);
FUNC(curl_pushheader_byname);
FUNC(curl_pushheader_bynum);
FUNC(curl_share_cleanup);
FUNC(curl_share_init);
FUNC(curl_share_setopt);
FUNC(curl_share_strerror);
FUNC(curl_slist_append);
FUNC(curl_slist_free_all);
FUNC(curl_strequal);
FUNC(curl_strnequal);
FUNC(curl_unescape);
FUNC(curl_url);
FUNC(curl_url_cleanup);
FUNC(curl_url_dup);
FUNC(curl_url_get);
FUNC(curl_url_set);
FUNC(curl_version);
FUNC(curl_version_info);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
