/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(FT_Add_Default_Modules);
FUNC(FT_Bitmap_Convert);
FUNC(FT_Bitmap_Done);
FUNC(FT_Bitmap_New);
FUNC(FT_Done_Face);
FUNC(FT_Done_FreeType);
FUNC(FT_Done_MM_Var);
FUNC(FT_Face_GetCharVariantIndex);
FUNC(FT_Get_Advance);
FUNC(FT_Get_Char_Index);
FUNC(FT_Get_First_Char);
FUNC(FT_Get_Glyph_Name);
FUNC(FT_Get_Kerning);
FUNC(FT_Get_MM_Var);
FUNC(FT_Get_Name_Index);
FUNC(FT_Get_Next_Char);
FUNC(FT_Get_Sfnt_Table);
FUNC(FT_Get_Var_Blend_Coordinates);
FUNC(FT_Get_Var_Design_Coordinates);
FUNC(FT_Get_X11_Font_Format);
FUNC(FT_GlyphSlot_Embolden);
FUNC(FT_GlyphSlot_Oblique);
FUNC(FT_Init_FreeType);
FUNC(FT_Library_SetLcdFilter);
FUNC(FT_Load_Glyph);
FUNC(FT_Load_Sfnt_Table);
FUNC(FT_MulFix);
FUNC(FT_New_Face);
FUNC(FT_New_Library);
FUNC(FT_New_Memory_Face);
FUNC(FT_Outline_Decompose);
FUNC(FT_Outline_Embolden);
FUNC(FT_Outline_Get_CBox);
FUNC(FT_Outline_Transform);
FUNC(FT_Outline_Translate);
FUNC(FT_Reference_Face);
FUNC(FT_Render_Glyph);
FUNC(FT_RoundFix);
FUNC(FT_Select_Charmap);
FUNC(FT_Set_Char_Size);
FUNC(FT_Set_Transform);
FUNC(FT_Set_Var_Design_Coordinates);
FUNC(FT_Vector_Transform);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
