/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(FcCharSetAddChar);
FUNC(FcCharSetCreate);
FUNC(FcCharSetDestroy);
FUNC(FcCharSetMerge);
FUNC(FcCharSetSubtractCount);
FUNC(FcConfigCreate);
FUNC(FcConfigDestroy);
FUNC(FcConfigGetCurrent);
FUNC(FcConfigReference);
FUNC(FcConfigSubstitute);
FUNC(FcDefaultSubstitute);
FUNC(FcFontList);
FUNC(FcFontMatch);
FUNC(FcFontRenderPrepare);
FUNC(FcFontSetAdd);
FUNC(FcFontSetCreate);
FUNC(FcFontSetDestroy);
FUNC(FcFontSetMatch);
FUNC(FcFontSort);
FUNC(FcFreeTypeCharIndex);
FUNC(FcInit);
FUNC(FcInitBringUptoDate);
FUNC(FcLangSetAdd);
FUNC(FcLangSetCreate);
FUNC(FcLangSetDestroy);
FUNC(FcLangSetHasLang);
FUNC(FcMatrixMultiply);
FUNC(FcObjectSetBuild);
FUNC(FcObjectSetDestroy);
FUNC(FcPatternAddBool);
FUNC(FcPatternAddCharSet);
FUNC(FcPatternAddDouble);
FUNC(FcPatternAddInteger);
FUNC(FcPatternAddLangSet);
FUNC(FcPatternAddMatrix);
FUNC(FcPatternAddString);
FUNC(FcPatternCreate);
FUNC(FcPatternDel);
FUNC(FcPatternDestroy);
FUNC(FcPatternDuplicate);
FUNC(FcPatternEqual);
FUNC(FcPatternFilter);
FUNC(FcPatternFormat);
FUNC(FcPatternGet);
FUNC(FcPatternGetBool);
FUNC(FcPatternGetCharSet);
FUNC(FcPatternGetFTFace);
FUNC(FcPatternGetInteger);
FUNC(FcPatternGetLangSet);
FUNC(FcPatternGetMatrix);
FUNC(FcPatternGetString);
FUNC(FcPatternReference);
FUNC(FcPatternRemove);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
