/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(hb_blob_create);
FUNC(hb_buffer_add_utf16);
FUNC(hb_buffer_create);
FUNC(hb_buffer_destroy);
FUNC(hb_buffer_get_direction);
FUNC(hb_buffer_get_glyph_infos);
FUNC(hb_buffer_get_glyph_positions);
FUNC(hb_buffer_get_length);
FUNC(hb_buffer_guess_segment_properties);
FUNC(hb_buffer_reset);
FUNC(hb_buffer_set_direction);
FUNC(hb_buffer_set_script);
FUNC(hb_buffer_set_unicode_funcs);
FUNC(hb_face_create_for_tables);
FUNC(hb_face_destroy);
FUNC(hb_font_create);
FUNC(hb_font_destroy);
FUNC(hb_font_funcs_create);
FUNC(hb_font_funcs_make_immutable);
FUNC(hb_font_funcs_set_glyph_extents_func);
FUNC(hb_font_funcs_set_glyph_func);
FUNC(hb_font_funcs_set_glyph_h_advance_func);
FUNC(hb_font_funcs_set_glyph_h_origin_func);
FUNC(hb_font_funcs_set_nominal_glyph_func);
FUNC(hb_font_funcs_set_variation_glyph_func);
FUNC(hb_font_make_immutable);
FUNC(hb_font_set_funcs);
FUNC(hb_font_set_ppem);
FUNC(hb_font_set_scale);
FUNC(hb_ft_face_create_cached);
FUNC(hb_icu_get_unicode_funcs);
FUNC(hb_icu_script_to_script);
FUNC(hb_ot_layout_language_find_feature);
FUNC(hb_ot_layout_script_get_language_tags);
FUNC(hb_ot_layout_table_get_script_tags);
FUNC(hb_ot_tag_to_script);
FUNC(hb_shape);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
