/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(access);
FUNC(chdir);
FUNC(dup);
FUNC(dup2);
FUNC(ioctl);
FUNC(lstat);
FUNC(pipe);
FUNC(poll);
FUNC(pthread_cond_setname_np);
FUNC(pthread_get_user_context_np);
FUNC(pthread_kill);
FUNC(pthread_mutex_reltimedlock_np);
FUNC(pthread_mutex_setname_np);
FUNC(pthread_resume_user_context_np);
FUNC(pthread_suspend_user_context_np);
FUNC(sceKernelDebugRaiseException);
FUNC(sceKernelDebugRaiseExceptionWithContext);
FUNC(sceKernelGetFsSandboxRandomWord);
FUNC(sceKernelGetModuleInfoFromAddr);
FUNC(sceKernelJitCreateAliasOfSharedMemory);
FUNC(sceKernelJitCreateSharedMemory);
FUNC(sceKernelJitMapSharedMemory);
FUNC(sceKernelOpenSema);
FUNC(sceKernelSetProcessProperty);
FUNC(sem_setname);
FUNC(sigaction);
FUNC(sigaddset);
FUNC(sigaltstack);
FUNC(sigdelset);
FUNC(sigemptyset);
FUNC(sigfillset);
FUNC(sigismember);
FUNC(signal);
FUNC(sigprocmask);
FUNC(sigsuspend);
FUNC(socketpair);
FUNC(sysconf);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
