/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceKernelAddGpuExceptionEvent);
FUNC(sceKernelBacktraceSelf);
FUNC(sceKernelDeleteGpuExceptionEvent);
FUNC(sceKernelInstallExceptionHandler);
FUNC(sceKernelRemoveExceptionHandler);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
