/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceKernelAddCpumodeEvent);
FUNC(sceKernelDeleteCpumodeEvent);
FUNC(sceKernelGetCpumode);
FUNC(sceKernelSetFsstParam);
FUNC(sceKernelYieldCpumode);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
