/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(dup2);
FUNC(getrlimit);
FUNC(ioctl);
FUNC(kill);
FUNC(poll);
FUNC(pthread_kill);
FUNC(sceKernelGetExecutableModuleHandle);
FUNC(sceKernelJitCreateAliasOfSharedMemory);
FUNC(sceKernelJitCreateSharedMemory);
FUNC(sceKernelJitGetSharedMemoryInfo);
FUNC(sceKernelJitMapSharedMemory);
FUNC(setrlimit);
FUNC(sigaction);
FUNC(sigaddset);
FUNC(sigdelset);
FUNC(sigemptyset);
FUNC(sigfillset);
FUNC(sigismember);
FUNC(sigprocmask);
FUNC(sigsuspend);
FUNC(socketpair);
FUNC(sysconf);
FUNC(sysctl);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
