/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(ioctl);
FUNC(sceKernelGetSocPowerConsumption);
FUNC(sceKernelIccGetCountTime);
FUNC(sceKernelIccGetErrLog);
FUNC(sceKernelIccGetHwInfo);
FUNC(sceKernelIccGetSysEventLog);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
