/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceKernelJitCreateAliasOfSharedMemory);
FUNC(sceKernelJitCreateSharedMemory);
FUNC(sceKernelJitGetSharedMemoryInfo);
FUNC(sceKernelJitMapSharedMemory);
FUNC(socketpair);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
