/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(AsyncStorageClearNative);
FUNC(AsyncStorageCloseNative);
FUNC(AsyncStorageGetAllKeysNative);
FUNC(AsyncStorageGetItemNative);
FUNC(AsyncStorageOpenNative);
FUNC(AsyncStorageRemoveItemNative);
FUNC(AsyncStorageSetItemNative);
FUNC(DecryptRnpsBundle);
FUNC(HttpCacheWrapperFree);
FUNC(HttpCacheWrapperRetrieve);
FUNC(HttpCacheWrapperRevalidate);
FUNC(NetCtlCheckCallbackNative);
FUNC(NetCtlGetDeviceTypeNative);
FUNC(NetCtlGetStateNative);
FUNC(NetCtlInitNative);
FUNC(NetCtlRegisterCallbackNative);
FUNC(NetCtlTermNative);
FUNC(NetCtlUnregisterCallbackNative);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
