/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(png_create_info_struct);
FUNC(png_create_read_struct);
FUNC(png_create_write_struct);
FUNC(png_destroy_read_struct);
FUNC(png_destroy_write_struct);
FUNC(png_error);
FUNC(png_get_bit_depth);
FUNC(png_get_channels);
FUNC(png_get_color_type);
FUNC(png_get_error_ptr);
FUNC(png_get_gAMA);
FUNC(png_get_IHDR);
FUNC(png_get_image_height);
FUNC(png_get_image_width);
FUNC(png_get_interlace_type);
FUNC(png_get_io_ptr);
FUNC(png_get_PLTE);
FUNC(png_get_progressive_ptr);
FUNC(png_get_tRNS);
FUNC(png_get_user_chunk_ptr);
FUNC(png_get_valid);
FUNC(png_process_data);
FUNC(png_process_data_pause);
FUNC(png_progressive_combine_row);
FUNC(png_read_end);
FUNC(png_read_image);
FUNC(png_read_info);
FUNC(png_read_row);
FUNC(png_read_update_info);
FUNC(png_save_uint_16);
FUNC(png_save_uint_32);
FUNC(png_set_bKGD);
FUNC(png_set_chunk_cache_max);
FUNC(png_set_chunk_malloc_max);
FUNC(png_set_crc_action);
FUNC(png_set_expand);
FUNC(png_set_expand_gray_1_2_4_to_8);
FUNC(png_set_filler);
FUNC(png_set_gAMA);
FUNC(png_set_gamma);
FUNC(png_set_gray_to_rgb);
FUNC(png_set_IHDR);
FUNC(png_set_interlace_handling);
FUNC(png_set_keep_unknown_chunks);
FUNC(png_set_longjmp_fn);
FUNC(png_set_packing);
FUNC(png_set_packswap);
FUNC(png_set_palette_to_rgb);
FUNC(png_set_progressive_read_fn);
FUNC(png_set_read_fn);
FUNC(png_set_read_user_chunk_fn);
FUNC(png_set_read_user_transform_fn);
FUNC(png_set_strip_16);
FUNC(png_set_tRNS_to_alpha);
FUNC(png_set_user_limits);
FUNC(png_set_write_fn);
FUNC(png_set_write_user_transform_fn);
FUNC(png_start_read_image);
FUNC(png_write_end);
FUNC(png_write_image);
FUNC(png_write_info);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
