/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(CreateWebApiLibCtx);
FUNC(DestroyWebApiLibCtx);
FUNC(GetLibHttpCtxId);
FUNC(InitializeNetLib);
FUNC(NpStateManagerRegisterCallback);
FUNC(NpStateManagerRtcSetTick);
FUNC(NpStateManagerStart);
FUNC(NpStateManagerStop);
FUNC(NpStateManagerUnregisterCallback);
FUNC(RtcGetCurrentAdNetworkTickNative);
FUNC(RtcGetCurrentDebugNetworkTickNative);
FUNC(RtcGetCurrentNetworkTickNative);
FUNC(TerminateNetLib);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
