/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceVideoCoreInterfaceAddVblankEvent);
FUNC(sceVideoCoreInterfaceCloseCanvas);
FUNC(sceVideoCoreInterfaceCloseVideoOut);
FUNC(sceVideoCoreInterfaceCreateCanvasContext);
FUNC(sceVideoCoreInterfaceCreateFrameBufferContext);
FUNC(sceVideoCoreInterfaceDestroyCanvasContext);
FUNC(sceVideoCoreInterfaceDestroyFrameBufferContext);
FUNC(sceVideoCoreInterfaceFinishRendering);
FUNC(sceVideoCoreInterfaceFlushVideoOutBuffer);
FUNC(sceVideoCoreInterfaceGetCanvasVideoBufferAddress);
FUNC(sceVideoCoreInterfaceGetCanvasVideoBufferSize);
FUNC(sceVideoCoreInterfaceGetRenderFrameBuffer);
FUNC(sceVideoCoreInterfaceInitializeInterface);
FUNC(sceVideoCoreInterfaceLoadModule);
FUNC(sceVideoCoreInterfaceMainLoop);
FUNC(sceVideoCoreInterfaceOpenCanvas);
FUNC(sceVideoCoreInterfaceOpenVideoOut);
FUNC(sceVideoCoreInterfaceSetCanvasId);
FUNC(sceVideoCoreInterfaceSetFunctionTable);
FUNC(sceVideoCoreInterfaceSetFunctionTableExt);
FUNC(sceVideoCoreInterfaceSetVideoOutBufferInfo);
FUNC(sceVideoCoreInterfaceSubmitCanvases);
FUNC(sceVideoCoreInterfaceUnloadModule);
FUNC(sceVideoCoreInterfaceWaitCanvasFlip);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
