/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNetCtlGetInfoV6);
FUNC(sceNetCtlGetResultV6);
FUNC(sceNetCtlGetStateV6);
FUNC(sceNetCtlRegisterCallbackV6);
FUNC(sceNetCtlUnregisterCallbackV6);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
