/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSigninDialogClose);
FUNC(sceSigninDialogGetResult);
FUNC(sceSigninDialogGetStatus);
FUNC(sceSigninDialogInitialize);
FUNC(sceSigninDialogOpen);
FUNC(sceSigninDialogTerminate);
FUNC(sceSigninDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
