/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(FinalizeImeModule);
FUNC(InitializeImeModule);
FUNC(sceImeCheckFilterText);
FUNC(sceImeCheckRemoteEventParam);
FUNC(sceImeCheckUpdateTextInfo);
FUNC(sceImeClose);
FUNC(sceImeConfigGet);
FUNC(sceImeConfigSet);
FUNC(sceImeConfirmCandidate);
FUNC(sceImeDicAddWord);
FUNC(sceImeDicDeleteLearnDics);
FUNC(sceImeDicDeleteUserDics);
FUNC(sceImeDicDeleteWord);
FUNC(sceImeDicGetWords);
FUNC(sceImeDicReplaceWord);
FUNC(sceImeDisableController);
FUNC(sceImeFilterText);
FUNC(sceImeForTestFunction);
FUNC(sceImeGetPanelPositionAndForm);
FUNC(sceImeGetPanelSize);
FUNC(sceImeKeyboardClose);
FUNC(sceImeKeyboardGetInfo);
FUNC(sceImeKeyboardGetResourceId);
FUNC(sceImeKeyboardOpen);
FUNC(sceImeKeyboardOpenInternal);
FUNC(sceImeKeyboardSetMode);
FUNC(sceImeKeyboardUpdate);
FUNC(sceImeOpen);
FUNC(sceImeOpenInternal);
FUNC(sceImeParamInit);
FUNC(sceImeSetCandidateIndex);
FUNC(sceImeSetCaret);
FUNC(sceImeSetText);
FUNC(sceImeSetTextGeometry);
FUNC(sceImeUpdate);
FUNC(sceImeVshClearPreedit);
FUNC(sceImeVshClose);
FUNC(sceImeVshConfirmPreedit);
FUNC(sceImeVshDisableController);
FUNC(sceImeVshGetPanelPositionAndForm);
FUNC(sceImeVshInformConfirmdString);
FUNC(sceImeVshInformConfirmdString2);
FUNC(sceImeVshOpen);
FUNC(sceImeVshSendTextInfo);
FUNC(sceImeVshSetCaretGeometry);
FUNC(sceImeVshSetCaretIndexInPreedit);
FUNC(sceImeVshSetPanelPosition);
FUNC(sceImeVshSetParam);
FUNC(sceImeVshSetPreeditGeometry);
FUNC(sceImeVshSetSelectGeometry);
FUNC(sceImeVshSetSelectionText);
FUNC(sceImeVshUpdate);
FUNC(sceImeVshUpdateContext);
FUNC(sceImeVshUpdateContext2);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
