/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceVshAvcapClose);
FUNC(sceVshAvcapCreateSyncer);
FUNC(sceVshAvcapDeleteSyncer);
FUNC(sceVshAvcapGetInfo);
FUNC(sceVshAvcapGetStaticInfo);
FUNC(sceVshAvcapInit);
FUNC(sceVshAvcapOpenAudio);
FUNC(sceVshAvcapOpenAudioEx);
FUNC(sceVshAvcapOpenUserdata);
FUNC(sceVshAvcapOpenVideo);
FUNC(sceVshAvcapOpenVideoEx);
FUNC(sceVshAvcapReadAudio);
FUNC(sceVshAvcapReadUserdata);
FUNC(sceVshAvcapReadVideo);
FUNC(sceVshAvcapSelect);
FUNC(sceVshAvcapSetInfo);
FUNC(sceVshAvcapSetStaticInfo);
FUNC(sceVshAvcapStart);
FUNC(sceVshAvcapStop);
FUNC(sceVshAvcapTerm);
FUNC(sceVshAvcapUpdateSyncer);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
