/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceAvPlayerAddSource);
FUNC(sceAvPlayerAddSourceEx);
FUNC(sceAvPlayerChangeStream);
FUNC(sceAvPlayerClose);
FUNC(sceAvPlayerCurrentTime);
FUNC(sceAvPlayerDisableStream);
FUNC(sceAvPlayerEnableStream);
FUNC(sceAvPlayerGetAudioData);
FUNC(sceAvPlayerGetStreamInfo);
FUNC(sceAvPlayerGetVideoData);
FUNC(sceAvPlayerGetVideoDataEx);
FUNC(sceAvPlayerInit);
FUNC(sceAvPlayerInitEx);
FUNC(sceAvPlayerIsActive);
FUNC(sceAvPlayerJumpToTime);
FUNC(sceAvPlayerPause);
FUNC(sceAvPlayerPostInit);
FUNC(sceAvPlayerPrintf);
FUNC(sceAvPlayerResume);
FUNC(sceAvPlayerSetAvSyncMode);
FUNC(sceAvPlayerSetLogCallback);
FUNC(sceAvPlayerSetLooping);
FUNC(sceAvPlayerSetTrickSpeed);
FUNC(sceAvPlayerStart);
FUNC(sceAvPlayerStop);
FUNC(sceAvPlayerStreamCount);
FUNC(sceAvPlayerVprintf);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
