/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpGriefReportReadGroupMessageFile);
FUNC(sceNpGriefReportReadJsonFile);
FUNC(sceNpGriefReportReadLfpsCommentFile);
FUNC(sceNpGriefReportReadReportItem);
FUNC(sceNpGriefReportReadTextChatFile);
FUNC(sceNpGriefReportWriteActivityAttachFile);
FUNC(sceNpGriefReportWriteGroupMessageFile);
FUNC(sceNpGriefReportWriteJsonFile);
FUNC(sceNpGriefReportWriteReportItem);
FUNC(sceNpGriefReportWriteReportItem2);
FUNC(sceNpGriefReportWriteTemporaryFile);
FUNC(sceNpGriefReportWriteTextChatFile);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
