/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceHidControlConnectHandle);
FUNC(sceHidControlConnectPort);
FUNC(sceHidControlDisconnectDevice);
FUNC(sceHidControlDisconnectHandle);
FUNC(sceHidControlDisconnectPort);
FUNC(sceHidControlGetAuthInformation);
FUNC(sceHidControlGetBatteryState);
FUNC(sceHidControlGetDeviceId);
FUNC(sceHidControlGetDeviceInfo);
FUNC(sceHidControlGetDeviceName);
FUNC(sceHidControlGetJediExtensionUnitInfo);
FUNC(sceHidControlGetJediState);
FUNC(sceHidControlGetSparkState);
FUNC(sceHidControlInit);
FUNC(sceHidControlSetApplicationFocus);
FUNC(sceHidControlSetHandleState);
FUNC(sceHidControlSetJediAudioOutPath);
FUNC(sceHidControlSetJediVolumeGain);
FUNC(sceHidControlSetProcessFocus);
FUNC(sceHidControlSetRevokeList);
FUNC(sceHidControlSetUserColor);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
