/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceOpusDecCreate);
FUNC(sceOpusDecCtl);
FUNC(sceOpusDecDecode);
FUNC(sceOpusDecDecodeCancelForTimeout);
FUNC(sceOpusDecDecodeFloat);
FUNC(sceOpusDecDecodeFloatWithPriority);
FUNC(sceOpusDecDecodeFloatWithPriorityAndTimeout);
FUNC(sceOpusDecDecodeWithPriority);
FUNC(sceOpusDecDecodeWithPriorityAndTimeout);
FUNC(sceOpusDecDestroy);
FUNC(sceOpusDecGetSize);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
