/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNetCtlCheckCallback);
FUNC(sceNetCtlCheckCallbackForLibIpcInt);
FUNC(sceNetCtlClearEventForLibIpcInt);
FUNC(sceNetCtlClearEventIpcInt);
FUNC(sceNetCtlConnectConfIpcInt);
FUNC(sceNetCtlConnectIpcInt);
FUNC(sceNetCtlConnectWithRetryIpcInt);
FUNC(sceNetCtlDisableBandwidthManagementIpcInt);
FUNC(sceNetCtlDisconnectIpcInt);
FUNC(sceNetCtlEnableBandwidthManagementIpcInt);
FUNC(sceNetCtlGetBandwidthInfoIpcInt);
FUNC(sceNetCtlGetEtherLinkMode);
FUNC(sceNetCtlGetIfStat);
FUNC(sceNetCtlGetInfo);
FUNC(sceNetCtlGetInfoIpcInt);
FUNC(sceNetCtlGetInfoV6);
FUNC(sceNetCtlGetInfoV6IpcInt);
FUNC(sceNetCtlGetNatInfo);
FUNC(sceNetCtlGetNatInfoIpcInt);
FUNC(sceNetCtlGetNetEvConfigInfoIpcInt);
FUNC(sceNetCtlGetResult);
FUNC(sceNetCtlGetResultIpcInt);
FUNC(sceNetCtlGetResultV6);
FUNC(sceNetCtlGetResultV6IpcInt);
FUNC(sceNetCtlGetScanInfoBssidForSsidListScanIpcInt);
FUNC(sceNetCtlGetScanInfoBssidIpcInt);
FUNC(sceNetCtlGetScanInfoByBssidIpcInt);
FUNC(sceNetCtlGetScanInfoForSsidListScanIpcInt);
FUNC(sceNetCtlGetScanInfoForSsidScanIpcInt);
FUNC(sceNetCtlGetState);
FUNC(sceNetCtlGetState2IpcInt);
FUNC(sceNetCtlGetStateIpcInt);
FUNC(sceNetCtlGetStateV6);
FUNC(sceNetCtlGetStateV6IpcInt);
FUNC(sceNetCtlGetWifiType);
FUNC(sceNetCtlInit);
FUNC(sceNetCtlIsBandwidthManagementEnabledIpcInt);
FUNC(sceNetCtlRegisterCallback);
FUNC(sceNetCtlRegisterCallbackForLibIpcInt);
FUNC(sceNetCtlRegisterCallbackIpcInt);
FUNC(sceNetCtlRegisterCallbackV6);
FUNC(sceNetCtlRegisterCallbackV6IpcInt);
FUNC(sceNetCtlScanIpcInt);
FUNC(sceNetCtlSetErrorNotificationEnabledIpcInt);
FUNC(sceNetCtlSetStunWithPaddingFlagIpcInt);
FUNC(sceNetCtlTerm);
FUNC(sceNetCtlUnregisterCallback);
FUNC(sceNetCtlUnregisterCallbackForLibIpcInt);
FUNC(sceNetCtlUnregisterCallbackIpcInt);
FUNC(sceNetCtlUnregisterCallbackV6);
FUNC(sceNetCtlUnregisterCallbackV6IpcInt);
FUNC(sceNetCtlUnsetStunWithPaddingFlagIpcInt);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
