/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceFontFtInitAliases);
FUNC(sceFontFtSetAliasFont);
FUNC(sceFontFtSetAliasPath);
FUNC(sceFontFtSupportBdf);
FUNC(sceFontFtSupportCid);
FUNC(sceFontFtSupportFontFormats);
FUNC(sceFontFtSupportOpenType);
FUNC(sceFontFtSupportOpenTypeOtf);
FUNC(sceFontFtSupportOpenTypeTtf);
FUNC(sceFontFtSupportPcf);
FUNC(sceFontFtSupportPfr);
FUNC(sceFontFtSupportSystemFonts);
FUNC(sceFontFtSupportTrueType);
FUNC(sceFontFtSupportTrueTypeGx);
FUNC(sceFontFtSupportType1);
FUNC(sceFontFtSupportType42);
FUNC(sceFontFtSupportWinFonts);
FUNC(sceFontFtTermAliases);
FUNC(sceFontSelectGlyphsFt);
FUNC(sceFontSelectLibraryFt);
FUNC(sceFontSelectRendererFt);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
