/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(scePlayGoDialogClose);
FUNC(scePlayGoDialogGetResult);
FUNC(scePlayGoDialogGetStatus);
FUNC(scePlayGoDialogInitialize);
FUNC(scePlayGoDialogOpen);
FUNC(scePlayGoDialogTerminate);
FUNC(scePlayGoDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
