/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceUsbStorageDialogClose);
FUNC(sceUsbStorageDialogGetResult);
FUNC(sceUsbStorageDialogGetStatus);
FUNC(sceUsbStorageDialogInitialize);
FUNC(sceUsbStorageDialogOpen);
FUNC(sceUsbStorageDialogTerminate);
FUNC(sceUsbStorageDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
