/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(_Z5dummyv);
FUNC(sceNpEntitlementAccessAbortRequest);
FUNC(sceNpEntitlementAccessDeleteRequest);
FUNC(sceNpEntitlementAccessGenerateTransactionId);
FUNC(sceNpEntitlementAccessGetAddcontEntitlementInfo);
FUNC(sceNpEntitlementAccessGetAddcontEntitlementInfoList);
FUNC(sceNpEntitlementAccessGetEntitlementKey);
FUNC(sceNpEntitlementAccessGetSkuFlag);
FUNC(sceNpEntitlementAccessInitialize);
FUNC(sceNpEntitlementAccessPollConsumableEntitlementInfo);
FUNC(sceNpEntitlementAccessPollConsumeEntitlement);
FUNC(sceNpEntitlementAccessPollServiceEntitlementInfo);
FUNC(sceNpEntitlementAccessPollServiceEntitlementInfoList);
FUNC(sceNpEntitlementAccessPollUnifiedEntitlementInfo);
FUNC(sceNpEntitlementAccessPollUnifiedEntitlementInfoList);
FUNC(sceNpEntitlementAccessRequestConsumableEntitlementInfo);
FUNC(sceNpEntitlementAccessRequestConsumeEntitlement);
FUNC(sceNpEntitlementAccessRequestConsumeServiceEntitlement);
FUNC(sceNpEntitlementAccessRequestConsumeUnifiedEntitlement);
FUNC(sceNpEntitlementAccessRequestServiceEntitlementInfo);
FUNC(sceNpEntitlementAccessRequestServiceEntitlementInfoList);
FUNC(sceNpEntitlementAccessRequestUnifiedEntitlementInfo);
FUNC(sceNpEntitlementAccessRequestUnifiedEntitlementInfoList);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
