/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceAvSettingAddCallbacks);
FUNC(sceAvSettingAddCallbacksForLnc);
FUNC(sceAvSettingAddCallbacksForSocialScreen);
FUNC(sceAvSettingCallbackFuncsInit);
FUNC(sceAvSettingCallbackFuncsInit_);
FUNC(sceAvSettingCallbackFuncsInitForLnc);
FUNC(sceAvSettingCallbackFuncsInitForLnc_);
FUNC(sceAvSettingChangeOutputMode);
FUNC(sceAvSettingChangeOutputMode2);
FUNC(sceAvSettingChangeOutputMode3);
FUNC(sceAvSettingChangeOutputModeForDiag);
FUNC(sceAvSettingChangeProcessAttribute);
FUNC(sceAvSettingCheckCallback);
FUNC(sceAvSettingControlHdcpEncryption);
FUNC(sceAvSettingDriverChangeConnectionStatus);
FUNC(sceAvSettingDriverUpdateStatus);
FUNC(sceAvSettingEnterAudioMuteForShutdown);
FUNC(sceAvSettingGetCurrentDeviceInfo_);
FUNC(sceAvSettingGetCurrentHdmiDeviceId);
FUNC(sceAvSettingGetCurrentOutputMode_);
FUNC(sceAvSettingGetCurrentOutputMode2_);
FUNC(sceAvSettingGetDetailedHdcpStatus);
FUNC(sceAvSettingGetDeviceInfo);
FUNC(sceAvSettingGetHdcpStatus);
FUNC(sceAvSettingGetHdmiConnectDisconnectNum);
FUNC(sceAvSettingGetHdmiKsvList);
FUNC(sceAvSettingGetHdmiMonitorInfo);
FUNC(sceAvSettingGetHdmiRawEdid);
FUNC(sceAvSettingGetMorpheusPuStatus);
FUNC(sceAvSettingGetNativeHdmiMonitorInfo);
FUNC(sceAvSettingGetRawHdmiMonitorInfo);
FUNC(sceAvSettingInit);
FUNC(sceAvSettingIsSupportedAudioOutModeByHdmiMonitorInfo);
FUNC(sceAvSettingIsSupportedHdcpVersionByHdmiMonitorInfo);
FUNC(sceAvSettingIsSupportedVideoOutModeByHdmiMonitorInfo);
FUNC(sceAvSettingIsSuspendedProcessOutputModeAvailable);
FUNC(sceAvSettingIsSuspendedProcessOutputModeAvailable2);
FUNC(sceAvSettingIsVrSupportedByHdmiMonitorInfo2);
FUNC(sceAvSettingNotifyAudioOutMode);
FUNC(sceAvSettingNotifyResponseForSocialScreen);
FUNC(sceAvSettingNotifyUmdEvent);
FUNC(sceAvSettingNotifyVideoOutMode);
FUNC(sceAvSettingRemoveCallbacks);
FUNC(sceAvSettingRemoveProcessOutputMode);
FUNC(sceAvSettingSet2dVrMode);
FUNC(sceAvSettingSetAudioOutModeAny_);
FUNC(sceAvSettingSetAudioOutModeInvalid_);
FUNC(sceAvSettingSetAvOutputMode);
FUNC(sceAvSettingSetDispclk);
FUNC(sceAvSettingSetDisplayBlackLevel);
FUNC(sceAvSettingSetHdcpMode);
FUNC(sceAvSettingSetHdcpStatus);
FUNC(sceAvSettingSetHdmiGamutMetadata_);
FUNC(sceAvSettingSetVideoOutModeAny_);
FUNC(sceAvSettingSetVideoOutModeInvalid_);
FUNC(sceAvSettingSetVideoOutputColorEffect);
FUNC(sceAvSettingSetVideoOutSource);
FUNC(sceAvSettingSimulateProcessOutputModeArbitration_);
FUNC(sceAvSettingTerm);
FUNC(sceAvSettingWaitCallback);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
