/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceAjmBatchCancel);
FUNC(sceAjmBatchErrorDump);
FUNC(sceAjmBatchJobControlBufferRa);
FUNC(sceAjmBatchJobInlineBuffer);
FUNC(sceAjmBatchJobRunBufferRa);
FUNC(sceAjmBatchJobRunSplitBufferRa);
FUNC(sceAjmBatchStartBuffer);
FUNC(sceAjmBatchWait);
FUNC(sceAjmDecAt9ParseConfigData);
FUNC(sceAjmDecMp3ParseFrame);
FUNC(sceAjmFinalize);
FUNC(sceAjmInitialize);
FUNC(sceAjmInstanceCodecType);
FUNC(sceAjmInstanceCreate);
FUNC(sceAjmInstanceDestroy);
FUNC(sceAjmInstanceExtend);
FUNC(sceAjmInstanceSwitch);
FUNC(sceAjmMemoryRegister);
FUNC(sceAjmMemoryUnregister);
FUNC(sceAjmModuleRegister);
FUNC(sceAjmModuleUnregister);
FUNC(sceAjmStrError);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
