/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(__wrap_access);
FUNC(__wrap_clock_gettime);
FUNC(__wrap_fchown);
FUNC(__wrap_getcwd);
FUNC(__wrap_getenv);
FUNC(__wrap_link);
FUNC(__wrap_lstat);
FUNC(__wrap_mmap);
FUNC(__wrap_readlink);
FUNC(__wrap_statvfs);
FUNC(__wrap_symlink);
FUNC(arc4random);
FUNC(arc4random_buf);
FUNC(clock_gettime_np);
FUNC(closedir);
FUNC(fnmatch);
FUNC(freeaddrinfo);
FUNC(gai_strerror);
FUNC(getaddrinfo);
FUNC(getenv_np);
FUNC(gethostbyname);
FUNC(gethostbyname_r);
FUNC(getnameinfo);
FUNC(getservbyname);
FUNC(isatty);
FUNC(mkstemp);
FUNC(mmap_np);
FUNC(msetname);
FUNC(opendir);
FUNC(pthread_setname_np);
FUNC(readdir);
FUNC(readdir_r);
FUNC(setenv_np);
FUNC(strcasestr);
FUNC(sysinfo);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
