/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceAudioOutA3dControl);
FUNC(sceAudioOutA3dExit);
FUNC(sceAudioOutA3dInit);
FUNC(sceAudioOutAttachToApplicationByPid);
FUNC(sceAudioOutChangeAppModuleState);
FUNC(sceAudioOutClose);
FUNC(sceAudioOutDetachFromApplicationByPid);
FUNC(sceAudioOutExConfigureOutputMode);
FUNC(sceAudioOutExGetSystemInfo);
FUNC(sceAudioOutExPtClose);
FUNC(sceAudioOutExPtGetLastOutputTime);
FUNC(sceAudioOutExPtOpen);
FUNC(sceAudioOutExSystemInfoIsSupportedAudioOutExMode);
FUNC(sceAudioOutGetFocusEnablePid);
FUNC(sceAudioOutGetHandleStatusInfo);
FUNC(sceAudioOutGetInfo);
FUNC(sceAudioOutGetInfoOpenNum);
FUNC(sceAudioOutGetLastOutputTime);
FUNC(sceAudioOutGetPortState);
FUNC(sceAudioOutGetSimulatedBusUsableStatusByBusType);
FUNC(sceAudioOutGetSimulatedHandleStatusInfo);
FUNC(sceAudioOutGetSimulatedHandleStatusInfo2);
FUNC(sceAudioOutGetSparkVss);
FUNC(sceAudioOutGetSystemState);
FUNC(sceAudioOutInit);
FUNC(sceAudioOutInitIpmiGetSession);
FUNC(sceAudioOutMasteringGetState);
FUNC(sceAudioOutMasteringInit);
FUNC(sceAudioOutMasteringSetParam);
FUNC(sceAudioOutMasteringTerm);
FUNC(sceAudioOutMbusInit);
FUNC(sceAudioOutOpen);
FUNC(sceAudioOutOpenEx);
FUNC(sceAudioOutOutput);
FUNC(sceAudioOutOutputs);
FUNC(sceAudioOutPtClose);
FUNC(sceAudioOutPtGetLastOutputTime);
FUNC(sceAudioOutPtOpen);
FUNC(sceAudioOutSetConnections);
FUNC(sceAudioOutSetConnectionsForUser);
FUNC(sceAudioOutSetDevConnection);
FUNC(sceAudioOutSetHeadphoneOutMode);
FUNC(sceAudioOutSetJediJackVolume);
FUNC(sceAudioOutSetJediSpkVolume);
FUNC(sceAudioOutSetMainOutput);
FUNC(sceAudioOutSetMixLevelPadSpk);
FUNC(sceAudioOutSetMorpheusParam);
FUNC(sceAudioOutSetMorpheusWorkingMode);
FUNC(sceAudioOutSetPortConnections);
FUNC(sceAudioOutSetPortStatuses);
FUNC(sceAudioOutSetRecMode);
FUNC(sceAudioOutSetSparkParam);
FUNC(sceAudioOutSetUsbVolume);
FUNC(sceAudioOutSetVolume);
FUNC(sceAudioOutSetVolumeDown);
FUNC(sceAudioOutStartAuxBroadcast);
FUNC(sceAudioOutStartSharePlay);
FUNC(sceAudioOutStopAuxBroadcast);
FUNC(sceAudioOutStopSharePlay);
FUNC(sceAudioOutSuspendResume);
FUNC(sceAudioOutSysConfigureOutputMode);
FUNC(sceAudioOutSysGetHdmiMonitorInfo);
FUNC(sceAudioOutSysGetSystemInfo);
FUNC(sceAudioOutSysHdmiMonitorInfoIsSupportedAudioOutMode);
FUNC(sceAudioOutSystemControlGet);
FUNC(sceAudioOutSystemControlSet);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
