/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceVdecCoreAnalyzeStream);
FUNC(sceVdecCoreCreateDecoder);
FUNC(sceVdecCoreDeleteDecoder);
FUNC(sceVdecCoreFinalizeComputeResource);
FUNC(sceVdecCoreFlushDecodeOutput);
FUNC(sceVdecCoreGetDecodeOutput);
FUNC(sceVdecCoreInitializeComputeResource);
FUNC(sceVdecCoreMapMemoryBlock);
FUNC(sceVdecCoreQueryComputeResourceInfo);
FUNC(sceVdecCoreQueryFrameBufferInfo);
FUNC(sceVdecCoreQueryInstanceSize);
FUNC(sceVdecCoreResetDecoder);
FUNC(sceVdecCoreSetDecodeInput);
FUNC(sceVdecCoreSetDecodeOutputSw);
FUNC(sceVdecCoreSyncDecode);
FUNC(sceVdecCoreSyncDecodeOutputSw);
FUNC(sceVdecCoreSyncDecodeWptr);
FUNC(sceVdecCoreTrySyncDecode);
FUNC(sceVdecCoreTrySyncDecodeOutputSw);
FUNC(sceVdecCoreTrySyncDecodeWptr);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
