/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceVoiceConnectIPortToOPort);
FUNC(sceVoiceCreatePort);
FUNC(sceVoiceDeletePort);
FUNC(sceVoiceDisconnectIPortFromOPort);
FUNC(sceVoiceEnd);
FUNC(sceVoiceGetBitRate);
FUNC(sceVoiceGetMuteFlag);
FUNC(sceVoiceGetPortAttr);
FUNC(sceVoiceGetPortInfo);
FUNC(sceVoiceGetResourceInfo);
FUNC(sceVoiceGetVolume);
FUNC(sceVoiceInit);
FUNC(sceVoiceInitHQ);
FUNC(sceVoicePausePort);
FUNC(sceVoicePausePortAll);
FUNC(sceVoiceReadFromOPort);
FUNC(sceVoiceResetPort);
FUNC(sceVoiceResumePort);
FUNC(sceVoiceResumePortAll);
FUNC(sceVoiceSetBitRate);
FUNC(sceVoiceSetMuteFlag);
FUNC(sceVoiceSetMuteFlagAll);
FUNC(sceVoiceSetThreadsParams);
FUNC(sceVoiceSetVolume);
FUNC(sceVoiceStart);
FUNC(sceVoiceStop);
FUNC(sceVoiceUpdatePort);
FUNC(sceVoiceVADAdjustment);
FUNC(sceVoiceVADSetVersion);
FUNC(sceVoiceWriteToIPort);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
