/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSysUtilSendAddressingSystemNotification);
FUNC(sceSysUtilSendAddressingSystemNotificationWithDeviceId);
FUNC(sceSysUtilSendAddressingSystemNotificationWithUserId);
FUNC(sceSysUtilSendAddressingSystemNotificationWithUserName);
FUNC(sceSysUtilSendNotificationRequest);
FUNC(sceSysUtilSendNpDebugNotificationRequest);
FUNC(sceSysUtilSendSystemNotification);
FUNC(sceSysUtilSendSystemNotification2);
FUNC(sceSysUtilSendSystemNotificationParamInit);
FUNC(sceSysUtilSendSystemNotificationWithAppId);
FUNC(sceSysUtilSendSystemNotificationWithAppInfo);
FUNC(sceSysUtilSendSystemNotificationWithAppName);
FUNC(sceSysUtilSendSystemNotificationWithAppNameRelatedToUser);
FUNC(sceSysUtilSendSystemNotificationWithDeviceId);
FUNC(sceSysUtilSendSystemNotificationWithDeviceIdRelatedToUser);
FUNC(sceSysUtilSendSystemNotificationWithErrorCode);
FUNC(sceSysUtilSendSystemNotificationWithParams);
FUNC(sceSysUtilSendSystemNotificationWithText);
FUNC(sceSysUtilSendSystemNotificationWithTextRelatedToUser);
FUNC(sceSysUtilSendSystemNotificationWithUserId);
FUNC(sceSysUtilSendSystemNotificationWithUserName);
FUNC(sceSysUtilSendSystemNotificationWithUserNameInfo);
FUNC(sceSysUtilSendTrcCheckNotificationRequest);
FUNC(sceSysUtilSendWebDebugNotificationRequest);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
