/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceAvSettingDebugAddCallbacks);
FUNC(sceAvSettingDebugClearDiagCommand);
FUNC(sceAvSettingDebugSetDiagState);
FUNC(sceAvSettingDebugSetHdmiMonitorInfo);
FUNC(sceAvSettingDebugSetProcessAttribute);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
