/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(_Z5dummyv);
FUNC(sceAppContentAddcontDelete);
FUNC(sceAppContentAddcontEnqueueDownload);
FUNC(sceAppContentAddcontEnqueueDownloadSp);
FUNC(sceAppContentAddcontMount);
FUNC(sceAppContentAddcontShrink);
FUNC(sceAppContentAddcontUnmount);
FUNC(sceAppContentAppParamGetInt);
FUNC(sceAppContentAppParamGetString);
FUNC(sceAppContentDownload0Expand);
FUNC(sceAppContentDownload0Shrink);
FUNC(sceAppContentDownload1Expand);
FUNC(sceAppContentDownload1Shrink);
FUNC(sceAppContentDownloadDataFormat);
FUNC(sceAppContentDownloadDataGetAvailableSpaceKb);
FUNC(sceAppContentGetAddcontDownloadProgress);
FUNC(sceAppContentGetAddcontInfo);
FUNC(sceAppContentGetAddcontInfoList);
FUNC(sceAppContentGetEntitlementKey);
FUNC(sceAppContentGetRegion);
FUNC(sceAppContentInitialize);
FUNC(sceAppContentRequestPatchInstall);
FUNC(sceAppContentSmallSharedDataFormat);
FUNC(sceAppContentSmallSharedDataGetAvailableSpaceKb);
FUNC(sceAppContentSmallSharedDataMount);
FUNC(sceAppContentSmallSharedDataUnmount);
FUNC(sceAppContentTemporaryDataFormat);
FUNC(sceAppContentTemporaryDataGetAvailableSpaceKb);
FUNC(sceAppContentTemporaryDataMount);
FUNC(sceAppContentTemporaryDataMount2);
FUNC(sceAppContentTemporaryDataUnmount);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
