/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceCustomMusicCoreBgmClose);
FUNC(sceCustomMusicCoreBgmOpen);
FUNC(sceCustomMusicCoreBgmOpen2);
FUNC(sceCustomMusicCoreBgmOutput);
FUNC(sceCustomMusicCoreBgmSetAudioVolume);
FUNC(sceCustomMusicCoreBgmStart);
FUNC(sceCustomMusicCoreBgmStop);
FUNC(sceCustomMusicCoreGetBgmAuthorityStatus);
FUNC(sceCustomMusicCoreGetHdcpStatus);
FUNC(sceCustomMusicCoreGetSystemAudioVolume);
FUNC(sceCustomMusicCorePostEvent);
FUNC(sceCustomMusicCoreSendEvent);
FUNC(sceCustomMusicCoreSendMulticastEvent);
FUNC(sceCustomMusicCoreSendSpMessage);
FUNC(sceCustomMusicCoreSetSystemAudioVolume);
FUNC(sceCustomMusicCoreStartOperation);
FUNC(sceCustomMusicCoreStartOperation2);
FUNC(sceCustomMusicCoreStopOperation);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
