/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceUsbdAllocTransfer);
FUNC(sceUsbdAttachKernelDriver);
FUNC(sceUsbdBulkTransfer);
FUNC(sceUsbdCancelTransfer);
FUNC(sceUsbdCheckConnected);
FUNC(sceUsbdClaimInterface);
FUNC(sceUsbdClearHalt);
FUNC(sceUsbdClose);
FUNC(sceUsbdControlTransfer);
FUNC(sceUsbdControlTransferGetData);
FUNC(sceUsbdControlTransferGetSetup);
FUNC(sceUsbdDetachKernelDriver);
FUNC(sceUsbdEventHandlerActive);
FUNC(sceUsbdEventHandlingOk);
FUNC(sceUsbdExit);
FUNC(sceUsbdFillBulkTransfer);
FUNC(sceUsbdFillControlSetup);
FUNC(sceUsbdFillControlTransfer);
FUNC(sceUsbdFillInterruptTransfer);
FUNC(sceUsbdFillIsoTransfer);
FUNC(sceUsbdFreeConfigDescriptor);
FUNC(sceUsbdFreeDeviceList);
FUNC(sceUsbdFreeTransfer);
FUNC(sceUsbdGetActiveConfigDescriptor);
FUNC(sceUsbdGetBusNumber);
FUNC(sceUsbdGetConfigDescriptor);
FUNC(sceUsbdGetConfigDescriptorByValue);
FUNC(sceUsbdGetConfiguration);
FUNC(sceUsbdGetDescriptor);
FUNC(sceUsbdGetDevice);
FUNC(sceUsbdGetDeviceAddress);
FUNC(sceUsbdGetDeviceDescriptor);
FUNC(sceUsbdGetDeviceList);
FUNC(sceUsbdGetDeviceSpeed);
FUNC(sceUsbdGetIsoPacketBuffer);
FUNC(sceUsbdGetMaxIsoPacketSize);
FUNC(sceUsbdGetMaxPacketSize);
FUNC(sceUsbdGetStringDescriptor);
FUNC(sceUsbdGetStringDescriptorAscii);
FUNC(sceUsbdHandleEvents);
FUNC(sceUsbdHandleEventsLocked);
FUNC(sceUsbdHandleEventsTimeout);
FUNC(sceUsbdInit);
FUNC(sceUsbdInterruptTransfer);
FUNC(sceUsbdKernelDriverActive);
FUNC(sceUsbdLockEvents);
FUNC(sceUsbdLockEventWaiters);
FUNC(sceUsbdOpen);
FUNC(sceUsbdOpenDeviceWithVidPid);
FUNC(sceUsbdRefDevice);
FUNC(sceUsbdReleaseInterface);
FUNC(sceUsbdResetDevice);
FUNC(sceUsbdSetConfiguration);
FUNC(sceUsbdSetInterfaceAltSetting);
FUNC(sceUsbdSetIsoPacketLengths);
FUNC(sceUsbdSubmitTransfer);
FUNC(sceUsbdTryLockEvents);
FUNC(sceUsbdUnlockEvents);
FUNC(sceUsbdUnlockEventWaiters);
FUNC(sceUsbdUnrefDevice);
FUNC(sceUsbdWaitForEvent);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
