/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSocialScreenDialogClose);
FUNC(sceSocialScreenDialogGetResult);
FUNC(sceSocialScreenDialogGetStatus);
FUNC(sceSocialScreenDialogInitialize);
FUNC(sceSocialScreenDialogOpen);
FUNC(sceSocialScreenDialogTerminate);
FUNC(sceSocialScreenDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
