/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceVnaCancelDownloadTts);
FUNC(sceVnaCancelTts);
FUNC(sceVnaCheckCallback);
FUNC(sceVnaCloseTtsStream);
FUNC(sceVnaGetFeedbackStatus);
FUNC(sceVnaGetMicStatus);
FUNC(sceVnaGetVadState);
FUNC(sceVnaGetWakeupPhraseInfo);
FUNC(sceVnaGetWakeupPhraseInfoCount);
FUNC(sceVnaInitialize);
FUNC(sceVnaInitializeForParty);
FUNC(sceVnaNotify);
FUNC(sceVnaNotifyStatus);
FUNC(sceVnaOpenTtsStream);
FUNC(sceVnaReadTtsStream);
FUNC(sceVnaRegisterCallback);
FUNC(sceVnaRequestDownloadTts);
FUNC(sceVnaRequestTts);
FUNC(sceVnaSetDucking);
FUNC(sceVnaSetInputDevice);
FUNC(sceVnaSetWakeupPhrase);
FUNC(sceVnaStartAnalyze);
FUNC(sceVnaStartKeywordDetection);
FUNC(sceVnaStopAnalyze);
FUNC(sceVnaStopKeywordDetection);
FUNC(sceVnaTerminate);
FUNC(sceVnaUnregisterCallback);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
