/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpPartyCheckCallback);
FUNC(sceNpPartyCreate);
FUNC(sceNpPartyCreateA);
FUNC(sceNpPartyGetId);
FUNC(sceNpPartyGetMemberInfo);
FUNC(sceNpPartyGetMemberInfoA);
FUNC(sceNpPartyGetMembers);
FUNC(sceNpPartyGetMembersA);
FUNC(sceNpPartyGetMemberSessionInfo);
FUNC(sceNpPartyGetMemberVoiceInfo);
FUNC(sceNpPartyGetState);
FUNC(sceNpPartyGetStateAsUser);
FUNC(sceNpPartyGetStateAsUserA);
FUNC(sceNpPartyGetVoiceChatPriority);
FUNC(sceNpPartyInitialize);
FUNC(sceNpPartyJoin);
FUNC(sceNpPartyLeave);
FUNC(sceNpPartyRegisterHandler);
FUNC(sceNpPartyRegisterHandlerA);
FUNC(sceNpPartyRegisterPrivateHandler);
FUNC(sceNpPartySendBinaryMessage);
FUNC(sceNpPartySetVoiceChatPriority);
FUNC(sceNpPartyShowInvitationList);
FUNC(sceNpPartyShowInvitationListA);
FUNC(sceNpPartyTerminate);
FUNC(sceNpPartyUnregisterPrivateHandler);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
