/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSocialScreenCloseSeparateMode);
FUNC(sceSocialScreenConfigureSeparateMode);
FUNC(sceSocialScreenCrashDaemon);
FUNC(sceSocialScreenGetIgnoreSeparateMode);
FUNC(sceSocialScreenInitialize);
FUNC(sceSocialScreenInitializeSeparateModeParameter);
FUNC(sceSocialScreenOpenSeparateMode);
FUNC(sceSocialScreenReserveHighFrameRateVideoCaptureRequest);
FUNC(sceSocialScreenSetIgnoreSeparateMode);
FUNC(sceSocialScreenSetMode);
FUNC(sceSocialScreenTerminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
