/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(scePlayerInvitationDialogClose);
FUNC(scePlayerInvitationDialogGetResult);
FUNC(scePlayerInvitationDialogGetStatus);
FUNC(scePlayerInvitationDialogInitialize);
FUNC(scePlayerInvitationDialogOpen);
FUNC(scePlayerInvitationDialogTerminate);
FUNC(scePlayerInvitationDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
