/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSysmoduleGetModuleHandleInternal);
FUNC(sceSysmoduleGetModuleInfoForUnwind);
FUNC(sceSysmoduleIsCalledFromSysModule);
FUNC(sceSysmoduleIsCameraPreloaded);
FUNC(sceSysmoduleIsLoaded);
FUNC(sceSysmoduleIsLoadedInternal);
FUNC(sceSysmoduleLoadModule);
FUNC(sceSysmoduleLoadModuleByNameInternal);
FUNC(sceSysmoduleLoadModuleInternal);
FUNC(sceSysmoduleLoadModuleInternalWithArg);
FUNC(sceSysmoduleMapLibcForLibkernel);
FUNC(sceSysmodulePreloadModuleForLibkernel);
FUNC(sceSysmoduleUnloadModule);
FUNC(sceSysmoduleUnloadModuleByNameInternal);
FUNC(sceSysmoduleUnloadModuleInternal);
FUNC(sceSysmoduleUnloadModuleInternalWithArg);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
