/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSystemServiceAddLocalProcessForPs2Emu);
FUNC(sceSystemServiceGetParentSocketForPs2Emu);
FUNC(sceSystemServiceKillLocalProcessForPs2Emu);
FUNC(sceSystemServiceShowImposeMenuForPs2Emu);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
