/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceImeBackendAllConfirm);
FUNC(sceImeBackendAllDeleteConvertString);
FUNC(sceImeBackendBackspaceCharacter);
FUNC(sceImeBackendClose);
FUNC(sceImeBackendConvertBackward);
FUNC(sceImeBackendConvertCancel);
FUNC(sceImeBackendConvertForward);
FUNC(sceImeBackendDeleteCharacter);
FUNC(sceImeBackendEnterCharacter);
FUNC(sceImeBackendForTestFunction);
FUNC(sceImeBackendGetCandidateList);
FUNC(sceImeBackendGetCandidateListSize);
FUNC(sceImeBackendGetCandidateSelect);
FUNC(sceImeBackendGetCaretIndex);
FUNC(sceImeBackendGetConfirmString);
FUNC(sceImeBackendGetConvertMode);
FUNC(sceImeBackendGetConvertString);
FUNC(sceImeBackendGetStatus);
FUNC(sceImeBackendGetString);
FUNC(sceImeBackendModeCaretNext);
FUNC(sceImeBackendModeCaretPrevious);
FUNC(sceImeBackendOpen);
FUNC(sceImeBackendParamInit);
FUNC(sceImeBackendPartConfirm);
FUNC(sceImeBackendReset);
FUNC(sceImeBackendSetConvertMode);
FUNC(sceImeBackendTemporalConfirm);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
