/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceHmdSetupDialogClose);
FUNC(sceHmdSetupDialogGetResult);
FUNC(sceHmdSetupDialogGetStatus);
FUNC(sceHmdSetupDialogInitialize);
FUNC(sceHmdSetupDialogOpen);
FUNC(sceHmdSetupDialogTerminate);
FUNC(sceHmdSetupDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
