/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceOpusCeltDecCreate);
FUNC(sceOpusCeltDecCtl);
FUNC(sceOpusCeltDecDecode);
FUNC(sceOpusCeltDecDecodeFloat);
FUNC(sceOpusCeltDecDecodeFloatWithPriority);
FUNC(sceOpusCeltDecDecodeWithPriority);
FUNC(sceOpusCeltDecDestroy);
FUNC(sceOpusCeltDecGetSize);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
