/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceDeviceServiceGetEventState);
FUNC(sceDeviceServiceGetGeneration);
FUNC(sceDeviceServiceInitialize);
FUNC(sceDeviceServiceQueryDeviceInfo_);
FUNC(sceDeviceServiceTerminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
