/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceContentSearchCloseMetadata);
FUNC(sceContentSearchGetApplicationLastUpdateId);
FUNC(sceContentSearchGetContentLastUpdateId);
FUNC(sceContentSearchGetMetadataFieldInfo);
FUNC(sceContentSearchGetMetadataValue);
FUNC(sceContentSearchGetMyApplicationIndex);
FUNC(sceContentSearchGetNumOfApplication);
FUNC(sceContentSearchGetNumOfContent);
FUNC(sceContentSearchGetTotalContentSize);
FUNC(sceContentSearchInit);
FUNC(sceContentSearchOpenMetadata);
FUNC(sceContentSearchOpenMetadataByContentId);
FUNC(sceContentSearchSearchApplication);
FUNC(sceContentSearchSearchContent);
FUNC(sceContentSearchTerm);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
