/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceDtcpIpActivateAsync);
FUNC(sceDtcpIpAddHeader);
FUNC(sceDtcpIpByteSeekAsync);
FUNC(sceDtcpIpCancelActivate);
FUNC(sceDtcpIpCheckActivationAsync);
FUNC(sceDtcpIpCloseContentAsync);
FUNC(sceDtcpIpGetErrorCode);
FUNC(sceDtcpIpGetHttpStatusCode);
FUNC(sceDtcpIpInit);
FUNC(sceDtcpIpInitAuthAsync);
FUNC(sceDtcpIpOpenContentAsync);
FUNC(sceDtcpIpPollAsync);
FUNC(sceDtcpIpReadAsync);
FUNC(sceDtcpIpRemoveHeader);
FUNC(sceDtcpIpStartAuthAsync);
FUNC(sceDtcpIpStartSeq);
FUNC(sceDtcpIpStopAuthAsync);
FUNC(sceDtcpIpStopSeq);
FUNC(sceDtcpIpTerm);
FUNC(sceDtcpIpTermAuthAsync);
FUNC(sceDtcpIpTimeSeekAsync);
FUNC(sceDtcpIpWaitAsync);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
