/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(scePlayGoClose);
FUNC(scePlayGoGetChunkId);
FUNC(scePlayGoGetEta);
FUNC(scePlayGoGetInstallSpeed);
FUNC(scePlayGoGetLanguageMask);
FUNC(scePlayGoGetLocus);
FUNC(scePlayGoGetProgress);
FUNC(scePlayGoGetToDoList);
FUNC(scePlayGoInitialize);
FUNC(scePlayGoOpen);
FUNC(scePlayGoPrefetch);
FUNC(scePlayGoSetInstallSpeed);
FUNC(scePlayGoSetLanguageMask);
FUNC(scePlayGoSetToDoList);
FUNC(scePlayGoTerminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
