/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceAudio3dAudioOutClose);
FUNC(sceAudio3dAudioOutOpen);
FUNC(sceAudio3dAudioOutOutput);
FUNC(sceAudio3dAudioOutOutputs);
FUNC(sceAudio3dBedWrite);
FUNC(sceAudio3dBedWrite2);
FUNC(sceAudio3dCreateSpeakerArray);
FUNC(sceAudio3dDeleteSpeakerArray);
FUNC(sceAudio3dGetDefaultOpenParameters);
FUNC(sceAudio3dGetSpeakerArrayMemorySize);
FUNC(sceAudio3dGetSpeakerArrayMixCoefficients);
FUNC(sceAudio3dGetSpeakerArrayMixCoefficients2);
FUNC(sceAudio3dInitialize);
FUNC(sceAudio3dObjectReserve);
FUNC(sceAudio3dObjectSetAttributes);
FUNC(sceAudio3dObjectUnreserve);
FUNC(sceAudio3dPortAdvance);
FUNC(sceAudio3dPortClose);
FUNC(sceAudio3dPortCreate);
FUNC(sceAudio3dPortDestroy);
FUNC(sceAudio3dPortFlush);
FUNC(sceAudio3dPortFreeState);
FUNC(sceAudio3dPortGetAttributesSupported);
FUNC(sceAudio3dPortGetList);
FUNC(sceAudio3dPortGetParameters);
FUNC(sceAudio3dPortGetQueueLevel);
FUNC(sceAudio3dPortGetState);
FUNC(sceAudio3dPortGetStatus);
FUNC(sceAudio3dPortOpen);
FUNC(sceAudio3dPortPush);
FUNC(sceAudio3dPortQueryDebug);
FUNC(sceAudio3dPortSetAttribute);
FUNC(sceAudio3dReportRegisterHandler);
FUNC(sceAudio3dReportUnregisterHandler);
FUNC(sceAudio3dSetGpuRenderer);
FUNC(sceAudio3dStrError);
FUNC(sceAudio3dTerminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
