/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceVdecwrapCreateDecoder);
FUNC(sceVdecwrapDeleteDecoder);
FUNC(sceVdecwrapFlushDecodeOutput);
FUNC(sceVdecwrapGetDecodeOutput);
FUNC(sceVdecwrapMapDirectMemory);
FUNC(sceVdecwrapQueryDecoderMemoryInfo);
FUNC(sceVdecwrapQueryFrameBufferInfo);
FUNC(sceVdecwrapResetDecoder);
FUNC(sceVdecwrapSetDecodeInput);
FUNC(sceVdecwrapSyncDecode);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
