/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSdecCreateSw);
FUNC(sceSdecDestroySw);
FUNC(sceSdecGetVersionSw);
FUNC(sceSdecQueryMemorySw);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
