/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpWebApi2AbortRequest);
FUNC(sceNpWebApi2AddHttpRequestHeader);
FUNC(sceNpWebApi2AddMultipartPart);
FUNC(sceNpWebApi2AddWebTraceTag);
FUNC(sceNpWebApi2CheckTimeout);
FUNC(sceNpWebApi2CreateMultipartRequest);
FUNC(sceNpWebApi2CreateRequest);
FUNC(sceNpWebApi2CreateUserContext);
FUNC(sceNpWebApi2DeleteRequest);
FUNC(sceNpWebApi2DeleteUserContext);
FUNC(sceNpWebApi2GetHttpResponseHeaderValue);
FUNC(sceNpWebApi2GetHttpResponseHeaderValueLength);
FUNC(sceNpWebApi2GetMemoryPoolStats);
FUNC(sceNpWebApi2Initialize);
FUNC(sceNpWebApi2InitializeForPresence);
FUNC(sceNpWebApi2IntCreateRequest);
FUNC(sceNpWebApi2IntInitialize);
FUNC(sceNpWebApi2IntInitialize2);
FUNC(sceNpWebApi2IntPushEventCreateCtxIndFilter);
FUNC(sceNpWebApi2PushEventAbortHandle);
FUNC(sceNpWebApi2PushEventCreateFilter);
FUNC(sceNpWebApi2PushEventCreateHandle);
FUNC(sceNpWebApi2PushEventCreatePushContext);
FUNC(sceNpWebApi2PushEventDeleteFilter);
FUNC(sceNpWebApi2PushEventDeleteHandle);
FUNC(sceNpWebApi2PushEventDeletePushContext);
FUNC(sceNpWebApi2PushEventRegisterCallback);
FUNC(sceNpWebApi2PushEventRegisterPushContextCallback);
FUNC(sceNpWebApi2PushEventSetHandleTimeout);
FUNC(sceNpWebApi2PushEventStartPushContextCallback);
FUNC(sceNpWebApi2PushEventUnregisterCallback);
FUNC(sceNpWebApi2PushEventUnregisterPushContextCallback);
FUNC(sceNpWebApi2ReadData);
FUNC(sceNpWebApi2SendMultipartRequest);
FUNC(sceNpWebApi2SendRequest);
FUNC(sceNpWebApi2SetMultipartContentType);
FUNC(sceNpWebApi2SetRequestTimeout);
FUNC(sceNpWebApi2Terminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
