/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceMusicPlayerServiceBeginTransaction);
FUNC(sceMusicPlayerServiceCreateTrackList);
FUNC(sceMusicPlayerServiceEndTransaction);
FUNC(sceMusicPlayerServiceGetAudioVolume);
FUNC(sceMusicPlayerServiceGetCurrentPlayStatus);
FUNC(sceMusicPlayerServiceGetPlaybackResults);
FUNC(sceMusicPlayerServiceGetPlayStatusExtension);
FUNC(sceMusicPlayerServiceGetTrackInfo);
FUNC(sceMusicPlayerServiceGetTrackListVersion);
FUNC(sceMusicPlayerServiceInitialize);
FUNC(sceMusicPlayerServiceInitialize2);
FUNC(sceMusicPlayerServiceInitialize3);
FUNC(sceMusicPlayerServiceInsertTrackEntry);
FUNC(sceMusicPlayerServiceNextTrack);
FUNC(sceMusicPlayerServicePause);
FUNC(sceMusicPlayerServicePlay);
FUNC(sceMusicPlayerServicePlayStartByTime);
FUNC(sceMusicPlayerServicePreviousTrack);
FUNC(sceMusicPlayerServiceReceiveEvent);
FUNC(sceMusicPlayerServiceRemoveAllData);
FUNC(sceMusicPlayerServiceRemoveTrackEntry);
FUNC(sceMusicPlayerServiceRemoveTrackList);
FUNC(sceMusicPlayerServiceSeek);
FUNC(sceMusicPlayerServiceSetAudioVolume);
FUNC(sceMusicPlayerServiceSetRepeatMode);
FUNC(sceMusicPlayerServiceSetShuffle);
FUNC(sceMusicPlayerServiceSetTrackList);
FUNC(sceMusicPlayerServiceSetTrackList2);
FUNC(sceMusicPlayerServiceSetUsbStorageDeviceInfo);
FUNC(sceMusicPlayerServiceStop);
FUNC(sceMusicPlayerServiceTerminate);
FUNC(sceMusicPlayerServiceUnpause);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
