/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSrcUtilityFinalize);
FUNC(sceSrcUtilityFlush);
FUNC(sceSrcUtilityGetDelaySamples);
FUNC(sceSrcUtilityGetHandleSize);
FUNC(sceSrcUtilityGetPriority);
FUNC(sceSrcUtilityInitialize);
FUNC(sceSrcUtilityResample);
FUNC(sceSrcUtilitySetPriority);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
