/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceCompanionHttpdAddHeader);
FUNC(sceCompanionHttpdGet2ndScreenStatus);
FUNC(sceCompanionHttpdGetEvent);
FUNC(sceCompanionHttpdGetUserId);
FUNC(sceCompanionHttpdInitialize);
FUNC(sceCompanionHttpdInitialize2);
FUNC(sceCompanionHttpdOptParamInitialize);
FUNC(sceCompanionHttpdRegisterRequestBodyReceptionCallback);
FUNC(sceCompanionHttpdRegisterRequestCallback);
FUNC(sceCompanionHttpdRegisterRequestCallback2);
FUNC(sceCompanionHttpdSetBody);
FUNC(sceCompanionHttpdSetStatus);
FUNC(sceCompanionHttpdStart);
FUNC(sceCompanionHttpdStop);
FUNC(sceCompanionHttpdTerminate);
FUNC(sceCompanionHttpdUnregisterRequestBodyReceptionCallback);
FUNC(sceCompanionHttpdUnregisterRequestCallback);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
