/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceHmdDistortionGet2dVrCommand);
FUNC(sceHmdDistortionGetCompoundEyeCorrectionCommand);
FUNC(sceHmdDistortionGetCorrectionCommand);
FUNC(sceHmdDistortionGetWideNearCorrectionCommand);
FUNC(sceHmdDistortionGetWorkMemoryAlign);
FUNC(sceHmdDistortionGetWorkMemorySize);
FUNC(sceHmdDistortionInitialize);
FUNC(sceHmdDistortionSetOutputMinColor);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
