/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceRtcCheckValid);
FUNC(sceRtcCompareTick);
FUNC(sceRtcConvertLocalTimeToUtc);
FUNC(sceRtcConvertUtcToLocalTime);
FUNC(sceRtcEnd);
FUNC(sceRtcFormatRFC2822);
FUNC(sceRtcFormatRFC2822LocalTime);
FUNC(sceRtcFormatRFC3339);
FUNC(sceRtcFormatRFC3339LocalTime);
FUNC(sceRtcFormatRFC3339Precise);
FUNC(sceRtcFormatRFC3339PreciseLocalTime);
FUNC(sceRtcGetCurrentAdNetworkTick);
FUNC(sceRtcGetCurrentClock);
FUNC(sceRtcGetCurrentClockLocalTime);
FUNC(sceRtcGetCurrentDebugNetworkTick);
FUNC(sceRtcGetCurrentNetworkTick);
FUNC(sceRtcGetCurrentRawNetworkTick);
FUNC(sceRtcGetCurrentTick);
FUNC(sceRtcGetDayOfWeek);
FUNC(sceRtcGetDaysInMonth);
FUNC(sceRtcGetDosTime);
FUNC(sceRtcGetTick);
FUNC(sceRtcGetTickResolution);
FUNC(sceRtcGetTime_t);
FUNC(sceRtcGetWin32FileTime);
FUNC(sceRtcInit);
FUNC(sceRtcIsLeapYear);
FUNC(sceRtcParseDateTime);
FUNC(sceRtcParseRFC3339);
FUNC(sceRtcSetConf);
FUNC(sceRtcSetCurrentAdNetworkTick);
FUNC(sceRtcSetCurrentDebugNetworkTick);
FUNC(sceRtcSetCurrentNetworkTick);
FUNC(sceRtcSetCurrentTick);
FUNC(sceRtcSetDosTime);
FUNC(sceRtcSetTick);
FUNC(sceRtcSetTime_t);
FUNC(sceRtcSetWin32FileTime);
FUNC(sceRtcTickAddDays);
FUNC(sceRtcTickAddHours);
FUNC(sceRtcTickAddMicroseconds);
FUNC(sceRtcTickAddMinutes);
FUNC(sceRtcTickAddMonths);
FUNC(sceRtcTickAddSeconds);
FUNC(sceRtcTickAddTicks);
FUNC(sceRtcTickAddWeeks);
FUNC(sceRtcTickAddYears);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
