/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceUpsrvGetCompletedTaskId);
FUNC(sceUpsrvGetRebootFlag);
FUNC(sceUpsrvGetSystemExUpdateTaskState);
FUNC(sceUpsrvInitialize);
FUNC(sceUpsrvPostErrorLog);
FUNC(sceUpsrvResumePausedTask);
FUNC(sceUpsrvSwitchSystemExBank);
FUNC(sceUpsrvSwitchSystemExBankWithoutVerify);
FUNC(sceUpsrvTerminate);
FUNC(sceUpsrvUpdateCancelBDUpdate);
FUNC(sceUpsrvUpdateCheckCancel);
FUNC(sceUpsrvUpdateCheckCreateHandler);
FUNC(sceUpsrvUpdateCheckDestroyHandler);
FUNC(sceUpsrvUpdateCheckDoCheckSystem);
FUNC(sceUpsrvUpdateCheckDoCheckSystemBeta);
FUNC(sceUpsrvUpdateCheckDoCheckSystemExpBeta);
FUNC(sceUpsrvUpdateCheckDoCheckSystemForDevKit);
FUNC(sceUpsrvUpdateCheckDoCheckSystemForSettings);
FUNC(sceUpsrvUpdateCheckDoCheckSystemVersionDown);
FUNC(sceUpsrvUpdateCheckDoCheckSystemWithPupInfo);
FUNC(sceUpsrvUpdateCheckGetUpdatelistURL);
FUNC(sceUpsrvUpdateCheckIsSystemBetaClosed);
FUNC(sceUpsrvUpdateCreateUpdateTask);
FUNC(sceUpsrvUpdateDestroyUpdateTask);
FUNC(sceUpsrvUpdateDoCheckBootUpdate);
FUNC(sceUpsrvUpdateDoUpdate);
FUNC(sceUpsrvUpdateDoUpdateBeta);
FUNC(sceUpsrvUpdateDoUpdateExpBeta);
FUNC(sceUpsrvUpdateDoUpdateSystemEx);
FUNC(sceUpsrvUpdateDoUpdateWithHandler);
FUNC(sceUpsrvUpdateDoUpdateWithPupInfo);
FUNC(sceUpsrvUpdateDoUpdateWithPupPath);
FUNC(sceUpsrvUpdateGetBetaAgreementUrl);
FUNC(sceUpsrvUpdateGetBetaAgreementUrlForUpdate);
FUNC(sceUpsrvUpdateGetBetaFeatureListUrlForUpdate);
FUNC(sceUpsrvUpdateGetDownloadProgress);
FUNC(sceUpsrvUpdateGetEulaDisplay);
FUNC(sceUpsrvUpdateGetEulaStr);
FUNC(sceUpsrvUpdateGetEulaStrLen);
FUNC(sceUpsrvUpdateGetFeatureListUrl);
FUNC(sceUpsrvUpdateGetFeatureListUrlForSystemExUpdate);
FUNC(sceUpsrvUpdateGetFeatureListUrlForUpdate);
FUNC(sceUpsrvUpdateGetImageWritingProgress);
FUNC(sceUpsrvUpdateGetObfuscatedString);
FUNC(sceUpsrvUpdateGetUpdateTaskInfo);
FUNC(sceUpsrvUpdateGetUpdateTaskMgrInfo);
FUNC(sceUpsrvUpdateSetEulaAccept);
FUNC(sceUpsrvUpdateSetUpdateMode);
FUNC(sceUpsrvUpdateStartUpdateTask);
FUNC(sceUpsrvVerifySystemExBank);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
