/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(_ZN3sce16CommonDialogUtil12getSelfAppIdEv);
FUNC(_ZN3sce16CommonDialogUtil6Client11closeModuleEv);
FUNC(_ZN3sce16CommonDialogUtil6Client11updateStateEv);
FUNC(_ZN3sce16CommonDialogUtil6Client15launchCmnDialogEv);
FUNC(_ZN3sce16CommonDialogUtil6ClientD0Ev);
FUNC(_ZN3sce16CommonDialogUtil6ClientD1Ev);
FUNC(_ZN3sce16CommonDialogUtil6ClientD2Ev);
FUNC(_ZNK3sce16CommonDialogUtil6Client10isCloseReqEv);
FUNC(_ZNK3sce16CommonDialogUtil6Client13getFinishDataEPvm);
FUNC(_ZNK3sce16CommonDialogUtil6Client14getClientStateEv);
FUNC(_ZNK3sce16CommonDialogUtil6Client19isInitializedStatusEv);
FUNC(_ZNK3sce16CommonDialogUtil6Client8getAppIdEv);
FUNC(_ZNK3sce16CommonDialogUtil6Client8isFinishEv);
FUNC(_ZNK3sce16CommonDialogUtil6Client9getResultEv);
FUNC(_ZTVN3sce16CommonDialogUtil6ClientE);
FUNC(sceCommonDialogInitialize);
FUNC(sceCommonDialogIsUsed);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
