/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(FT_Get_PFR_Advance);
FUNC(FT_Get_PFR_Kerning);
FUNC(FT_Get_PFR_Metrics);
FUNC(pfr_cmap_class_rec);
FUNC(pfr_driver_class);
FUNC(psaux_module_class);
FUNC(t1_cmap_classes);
FUNC(t1_cmap_custom_class_rec);
FUNC(t1_cmap_expert_class_rec);
FUNC(t1_cmap_standard_class_rec);
FUNC(t1_cmap_unicode_class_rec);
FUNC(t1_driver_class);
FUNC(t1cid_driver_class);
FUNC(t42_driver_class);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
