/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceUsbStorageGetdentsClose);
FUNC(sceUsbStorageGetdentsOpen);
FUNC(sceUsbStorageGetdentsRead);
FUNC(sceUsbStorageRegisterCallbackForMapUnavailable);
FUNC(sceUsbStorageRequestMapWSB);
FUNC(sceUsbStorageUnregisterCallbackForMapUnavailable);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
