/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(scePadTrackerCalibrate);
FUNC(scePadTrackerGetWorkingMemorySize);
FUNC(scePadTrackerInit);
FUNC(scePadTrackerReadState);
FUNC(scePadTrackerTerm);
FUNC(scePadTrackerUpdate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
