/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceDbgKeyboardClose);
FUNC(sceDbgKeyboardGetKey2Char);
FUNC(sceDbgKeyboardInit);
FUNC(sceDbgKeyboardOpen);
FUNC(sceDbgKeyboardRead);
FUNC(sceDbgKeyboardReadState);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
