/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceAudiodecClearContext);
FUNC(sceAudiodecCreateDecoder);
FUNC(sceAudiodecDecode);
FUNC(sceAudiodecDecode2);
FUNC(sceAudiodecDecode2WithPriority);
FUNC(sceAudiodecDecodeWithPriority);
FUNC(sceAudiodecDeleteDecoder);
FUNC(sceAudiodecInitLibrary);
FUNC(sceAudiodecTermLibrary);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
