/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceVideoRecordingClose);
FUNC(sceVideoRecordingCopyBGRAtoNV12);
FUNC(sceVideoRecordingGetInfo);
FUNC(sceVideoRecordingGetStatus);
FUNC(sceVideoRecordingInit);
FUNC(sceVideoRecordingOpen);
FUNC(sceVideoRecordingOpen2);
FUNC(sceVideoRecordingQueryHddSize2);
FUNC(sceVideoRecordingQueryMemSize);
FUNC(sceVideoRecordingQueryMemSize2);
FUNC(sceVideoRecordingSetInfo);
FUNC(sceVideoRecordingStart);
FUNC(sceVideoRecordingStop);
FUNC(sceVideoRecordingTerm);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
