/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSdecCreateSwHevc);
FUNC(sceSdecDestroySwHevc);
FUNC(sceSdecExecuteSwHevc);
FUNC(sceSdecGetFrameSwHevc);
FUNC(sceSdecGetVersionSwHevc);
FUNC(sceSdecQueryMemorySwHevc);
FUNC(sceSdecResetSwHevc);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
