/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceMusicCoreServerCheckCoreStatus);
FUNC(sceMusicCoreServerRegistEventCallback);
FUNC(sceMusicCoreServerTriggerEvent);
FUNC(sceMusicCoreServerTriggerEventSync);
FUNC(sceMusicCoreServerTryLoadCore);
FUNC(sceMusicCoreServerUnregistEventCallback);
FUNC(sceMusicCoreServerUpdateSpWakeupAuthorityList);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
