/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceAutoMounterClientGetUsbDeviceInfo);
FUNC(sceAutoMounterClientGetUsbDeviceList);
FUNC(sceAutoMounterClientInit);
FUNC(sceAutoMounterClientRegisterCallback);
FUNC(sceAutoMounterClientTerm);
FUNC(sceAutoMounterClientUnregisterCallback);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
