/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpSnsTwitchDialogClose);
FUNC(sceNpSnsTwitchDialogGetResult);
FUNC(sceNpSnsTwitchDialogGetStatus);
FUNC(sceNpSnsTwitchDialogInitialize);
FUNC(sceNpSnsTwitchDialogOpen);
FUNC(sceNpSnsTwitchDialogTerminate);
FUNC(sceNpSnsTwitchDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
