/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSystemStateMgrCancelShutdownTimer);
FUNC(sceSystemStateMgrEnterMediaPlaybackMode);
FUNC(sceSystemStateMgrEnterStandby);
FUNC(sceSystemStateMgrExtendShutdownTimer);
FUNC(sceSystemStateMgrExtendShutdownTimerForPostAutoUpdateProcess);
FUNC(sceSystemStateMgrGetCurrentState);
FUNC(sceSystemStateMgrGetTriggerCode);
FUNC(sceSystemStateMgrIsBdDriveReady);
FUNC(sceSystemStateMgrIsGpuPerformanceNormal);
FUNC(sceSystemStateMgrIsShellUIShutdownInProgress);
FUNC(sceSystemStateMgrIsStandbyModeEnabled);
FUNC(sceSystemStateMgrLeaveMediaPlaybackMode);
FUNC(sceSystemStateMgrNotifySystemSuspendResumeProgress);
FUNC(sceSystemStateMgrReboot);
FUNC(sceSystemStateMgrSendCecOneTouchPlayCommand);
FUNC(sceSystemStateMgrStartRebootTimer);
FUNC(sceSystemStateMgrStartShutdownTimer);
FUNC(sceSystemStateMgrStartStadbyTimer);
FUNC(sceSystemStateMgrStartVshAutoUpdateTimer);
FUNC(sceSystemStateMgrTickMusicPlayback);
FUNC(sceSystemStateMgrTickPartyChat);
FUNC(sceSystemStateMgrTurnOff);
FUNC(sceSystemStateMgrVshAutoUpdate);
FUNC(sceSystemStateMgrWaitVshAutoUpdateVerifyDone);
FUNC(sceSystemStateMgrWakeUp);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
