/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceVrServiceDialogClose);
FUNC(sceVrServiceDialogGetResult);
FUNC(sceVrServiceDialogGetStatus);
FUNC(sceVrServiceDialogInitialize);
FUNC(sceVrServiceDialogOpen);
FUNC(sceVrServiceDialogTerminate);
FUNC(sceVrServiceDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
