/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpMatching2CreateContext);
FUNC(sceNpMatching2CreateJoinRoom);
FUNC(sceNpMatching2GetUserInfoList);
FUNC(sceNpMatching2JoinRoom);
FUNC(sceNpMatching2SignalingGetConnectionInfo);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
