/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNgs2CalcWaveformBlock);
FUNC(sceNgs2CustomRackGetModuleInfo);
FUNC(sceNgs2FftInit);
FUNC(sceNgs2FftProcess);
FUNC(sceNgs2FftQuerySize);
FUNC(sceNgs2GeomApply);
FUNC(sceNgs2GeomCalcListener);
FUNC(sceNgs2GeomResetListenerParam);
FUNC(sceNgs2GeomResetSourceParam);
FUNC(sceNgs2GetWaveformFrameInfo);
FUNC(sceNgs2PanGetVolumeMatrix);
FUNC(sceNgs2PanInit);
FUNC(sceNgs2ParseWaveformData);
FUNC(sceNgs2ParseWaveformFile);
FUNC(sceNgs2ParseWaveformUser);
FUNC(sceNgs2RackCreate);
FUNC(sceNgs2RackCreateWithAllocator);
FUNC(sceNgs2RackDestroy);
FUNC(sceNgs2RackGetInfo);
FUNC(sceNgs2RackGetUserData);
FUNC(sceNgs2RackGetVoiceHandle);
FUNC(sceNgs2RackLock);
FUNC(sceNgs2RackQueryBufferSize);
FUNC(sceNgs2RackSetUserData);
FUNC(sceNgs2RackUnlock);
FUNC(sceNgs2ReportRegisterHandler);
FUNC(sceNgs2ReportUnregisterHandler);
FUNC(sceNgs2SystemCreate);
FUNC(sceNgs2SystemCreateWithAllocator);
FUNC(sceNgs2SystemDestroy);
FUNC(sceNgs2SystemEnumHandles);
FUNC(sceNgs2SystemEnumRackHandles);
FUNC(sceNgs2SystemGetInfo);
FUNC(sceNgs2SystemGetUserData);
FUNC(sceNgs2SystemLock);
FUNC(sceNgs2SystemQueryBufferSize);
FUNC(sceNgs2SystemRender);
FUNC(sceNgs2SystemSetGrainSamples);
FUNC(sceNgs2SystemSetSampleRate);
FUNC(sceNgs2SystemSetUserData);
FUNC(sceNgs2SystemUnlock);
FUNC(sceNgs2VoiceControl);
FUNC(sceNgs2VoiceGetMatrixInfo);
FUNC(sceNgs2VoiceGetOwner);
FUNC(sceNgs2VoiceGetPortInfo);
FUNC(sceNgs2VoiceGetState);
FUNC(sceNgs2VoiceGetStateFlags);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
