/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceShareUtilityAdvanceFromFileWithContentIdList);
FUNC(sceShareUtilityAdvanceFromFileWithTitleIdList);
FUNC(sceShareUtilityAdvanceGetServiceInfo);
FUNC(sceShareUtilityAdvanceInitialize);
FUNC(sceShareUtilityAdvanceQueryServiceInfo);
FUNC(sceShareUtilityAdvanceQueryServiceInfoA);
FUNC(sceShareUtilityAdvanceResetPlayingContent);
FUNC(sceShareUtilityAdvanceSetPlayingContent);
FUNC(sceShareUtilityAdvanceSetUploadContentData);
FUNC(sceShareUtilityAdvanceTerminate);
FUNC(sceShareUtilityAdvanceValidateContents);
FUNC(sceShareUtilityAdvanceWakeUpShareMenu);
FUNC(sceShareUtilityAdvanceWakeUpShareMenuBroadcast);
FUNC(sceShareUtilityAdvanceWakeUpShareMenuDefault);
FUNC(sceShareUtilityAdvanceWakeUpShareMenuForShareContent);
FUNC(sceShareUtilityInitialize);
FUNC(sceShareUtilityInitializeEx2);
FUNC(sceShareUtilityOpenShareMenu);
FUNC(sceShareUtilityOpenShareMenuBroadcast);
FUNC(sceShareUtilityOpenShareMenuDefault);
FUNC(sceShareUtilityOpenShareMenuForShareContent);
FUNC(sceShareUtilityTerminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
