/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceCameraAccGetData);
FUNC(sceCameraAudioClose);
FUNC(sceCameraAudioGetData);
FUNC(sceCameraAudioGetData2);
FUNC(sceCameraAudioOpen);
FUNC(sceCameraAudioReset);
FUNC(sceCameraChangeAppModuleState);
FUNC(sceCameraClose);
FUNC(sceCameraCloseByHandle);
FUNC(sceCameraDeviceOpen);
FUNC(sceCameraGetAttribute);
FUNC(sceCameraGetAutoExposureGain);
FUNC(sceCameraGetAutoWhiteBalance);
FUNC(sceCameraGetCalibData);
FUNC(sceCameraGetCalibDataFromDevice);
FUNC(sceCameraGetCalibrationData);
FUNC(sceCameraGetConfig);
FUNC(sceCameraGetContrast);
FUNC(sceCameraGetDefectivePixelCancellation);
FUNC(sceCameraGetDeviceConfig);
FUNC(sceCameraGetDeviceConfigWithoutHandle);
FUNC(sceCameraGetDeviceID);
FUNC(sceCameraGetDeviceIDWithoutOpen);
FUNC(sceCameraGetDeviceInfo);
FUNC(sceCameraGetExposureGain);
FUNC(sceCameraGetFrameData);
FUNC(sceCameraGetGamma);
FUNC(sceCameraGetHue);
FUNC(sceCameraGetLensCorrection);
FUNC(sceCameraGetMmapConnectedCount);
FUNC(sceCameraGetProductInfo);
FUNC(sceCameraGetRegister);
FUNC(sceCameraGetRegistryInfo);
FUNC(sceCameraGetSaturation);
FUNC(sceCameraGetSharpness);
FUNC(sceCameraGetVrCaptureInfo);
FUNC(sceCameraGetWhiteBalance);
FUNC(sceCameraInitializeRegistryCalibData);
FUNC(sceCameraIsAttached);
FUNC(sceCameraIsConfigChangeDone);
FUNC(sceCameraIsValidFrameData);
FUNC(sceCameraOpen);
FUNC(sceCameraOpenByModuleId);
FUNC(sceCameraRemoveAppModuleFocus);
FUNC(sceCameraSetAppModuleFocus);
FUNC(sceCameraSetAttribute);
FUNC(sceCameraSetAttributeInternal);
FUNC(sceCameraSetAutoExposureGain);
FUNC(sceCameraSetAutoWhiteBalance);
FUNC(sceCameraSetCalibData);
FUNC(sceCameraSetConfig);
FUNC(sceCameraSetConfigInternal);
FUNC(sceCameraSetContrast);
FUNC(sceCameraSetDebugStop);
FUNC(sceCameraSetDefectivePixelCancellation);
FUNC(sceCameraSetDefectivePixelCancellationInternal);
FUNC(sceCameraSetExposureGain);
FUNC(sceCameraSetForceActivate);
FUNC(sceCameraSetGamma);
FUNC(sceCameraSetHue);
FUNC(sceCameraSetLensCorrection);
FUNC(sceCameraSetLensCorrectionInternal);
FUNC(sceCameraSetProcessFocus);
FUNC(sceCameraSetProcessFocusByHandle);
FUNC(sceCameraSetRegister);
FUNC(sceCameraSetSaturation);
FUNC(sceCameraSetSharpness);
FUNC(sceCameraSetTrackerMode);
FUNC(sceCameraSetUacModeInternal);
FUNC(sceCameraSetVideoSync);
FUNC(sceCameraSetVideoSyncInternal);
FUNC(sceCameraSetWhiteBalance);
FUNC(sceCameraStart);
FUNC(sceCameraStartByHandle);
FUNC(sceCameraStop);
FUNC(sceCameraStopByHandle);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
