/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSystemLogger2Initialize);
FUNC(sceSystemLogger2SetAsyncPeripheralConnectionLog);
FUNC(sceSystemLogger2SetLog);
FUNC(sceSystemLogger2SetLogAsync);
FUNC(sceSystemLogger2SetPeripheralConnectionLog);
FUNC(sceSystemLogger2Terminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
