/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceAt9EncClearContext);
FUNC(sceAt9EncCreateEncoder);
FUNC(sceAt9EncEncode);
FUNC(sceAt9EncFlush);
FUNC(sceAt9EncQueryMemSize);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
