/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceAppMessagingClearEventFlag);
FUNC(sceAppMessagingReceiveMsg);
FUNC(sceAppMessagingSendMsg);
FUNC(sceAppMessagingSendMsgToShellCore);
FUNC(sceAppMessagingSendMsgToShellUI);
FUNC(sceAppMessagingSetEventFlag);
FUNC(sceAppMessagingTryGetEventFlag);
FUNC(sceAppMessagingTryReceiveMsg);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
