/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(isobmf_box_getchildbox);
FUNC(isobmf_box_getdiskoffset);
FUNC(isobmf_box_getflags32b);
FUNC(isobmf_box_getmember_length);
FUNC(isobmf_box_getmember_ptr);
FUNC(isobmf_box_getmember_type);
FUNC(isobmf_box_getnextbox);
FUNC(isobmf_box_getstate);
FUNC(isobmf_box_gettype);
FUNC(isobmf_decoder_clear);
FUNC(isobmf_decoder_create);
FUNC(isobmf_decoder_decode);
FUNC(isobmf_decoder_destroy);
FUNC(isobmf_decoder_get_decoder_tree);
FUNC(isobmf_decoder_getquerydata);
FUNC(isobmf_decoder_next_disk_offset);
FUNC(isobmf_decoder_query);
FUNC(isobmf_memmanager_set);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
