/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpWebApiCreateContext);
FUNC(sceNpWebApiCreatePushEventFilter);
FUNC(sceNpWebApiCreateServicePushEventFilter);
FUNC(sceNpWebApiDeletePushEventFilter);
FUNC(sceNpWebApiDeleteServicePushEventFilter);
FUNC(sceNpWebApiRegisterExtdPushEventCallback);
FUNC(sceNpWebApiRegisterNotificationCallback);
FUNC(sceNpWebApiRegisterPushEventCallback);
FUNC(sceNpWebApiRegisterServicePushEventCallback);
FUNC(sceNpWebApiUnregisterNotificationCallback);
FUNC(sceNpWebApiUnregisterPushEventCallback);
FUNC(sceNpWebApiUnregisterServicePushEventCallback);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
