/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(_Z5dummyv);
FUNC(sceHttpCacheClear);
FUNC(sceHttpCacheClearAll);
FUNC(sceHttpCacheCompleteRequest);
FUNC(sceHttpCacheCreateRequest);
FUNC(sceHttpCacheDeleteRequest);
FUNC(sceHttpCacheInit);
FUNC(sceHttpCacheReadData);
FUNC(sceHttpCacheRetrieve);
FUNC(sceHttpCacheRetrieveWithMemoryPool);
FUNC(sceHttpCacheRevalidate);
FUNC(sceHttpCacheRevalidateWithMemoryPool);
FUNC(sceHttpCacheSetData);
FUNC(sceHttpCacheSetResponseHeader);
FUNC(sceHttpCacheSystemClearAll);
FUNC(sceHttpCacheSystemInit);
FUNC(sceHttpCacheSystemSendStatistics);
FUNC(sceHttpCacheSystemShutdown);
FUNC(sceHttpCacheSystemTerm);
FUNC(sceHttpCacheTerm);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
