/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceMoveTrackerCalibrateReset);
FUNC(sceMoveTrackerCalibrateYaw);
FUNC(sceMoveTrackerCameraUpdate);
FUNC(sceMoveTrackerCaptureInit);
FUNC(sceMoveTrackerCaptureTerm);
FUNC(sceMoveTrackerControllersUpdate);
FUNC(sceMoveTrackerGetState);
FUNC(sceMoveTrackerGetVersion);
FUNC(sceMoveTrackerGetWorkingMemorySize);
FUNC(sceMoveTrackerInit);
FUNC(sceMoveTrackerPlayGetImages);
FUNC(sceMoveTrackerPlayGetStates);
FUNC(sceMoveTrackerPlayStart);
FUNC(sceMoveTrackerPlayStep);
FUNC(sceMoveTrackerRecordSave);
FUNC(sceMoveTrackerRecordStart);
FUNC(sceMoveTrackerRecordStop);
FUNC(sceMoveTrackerTerm);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
