/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpScoreAbortRequest);
FUNC(sceNpScoreCensorComment);
FUNC(sceNpScoreCensorCommentAsync);
FUNC(sceNpScoreChangeModeForOtherSaveDataOwners);
FUNC(sceNpScoreCreateNpTitleCtx);
FUNC(sceNpScoreCreateNpTitleCtxA);
FUNC(sceNpScoreCreateRequest);
FUNC(sceNpScoreCreateTitleCtx);
FUNC(sceNpScoreDeleteNpTitleCtx);
FUNC(sceNpScoreDeleteRequest);
FUNC(sceNpScoreGetBoardInfo);
FUNC(sceNpScoreGetBoardInfoAsync);
FUNC(sceNpScoreGetFriendsRanking);
FUNC(sceNpScoreGetFriendsRankingA);
FUNC(sceNpScoreGetFriendsRankingAAsync);
FUNC(sceNpScoreGetFriendsRankingAsync);
FUNC(sceNpScoreGetFriendsRankingForCrossSave);
FUNC(sceNpScoreGetFriendsRankingForCrossSaveAsync);
FUNC(sceNpScoreGetGameData);
FUNC(sceNpScoreGetGameDataAsync);
FUNC(sceNpScoreGetGameDataByAccountId);
FUNC(sceNpScoreGetGameDataByAccountIdAsync);
FUNC(sceNpScoreGetRankingByAccountId);
FUNC(sceNpScoreGetRankingByAccountIdAsync);
FUNC(sceNpScoreGetRankingByAccountIdForCrossSave);
FUNC(sceNpScoreGetRankingByAccountIdForCrossSaveAsync);
FUNC(sceNpScoreGetRankingByAccountIdPcId);
FUNC(sceNpScoreGetRankingByAccountIdPcIdAsync);
FUNC(sceNpScoreGetRankingByAccountIdPcIdForCrossSave);
FUNC(sceNpScoreGetRankingByAccountIdPcIdForCrossSaveAsync);
FUNC(sceNpScoreGetRankingByNpId);
FUNC(sceNpScoreGetRankingByNpIdAsync);
FUNC(sceNpScoreGetRankingByNpIdPcId);
FUNC(sceNpScoreGetRankingByNpIdPcIdAsync);
FUNC(sceNpScoreGetRankingByRange);
FUNC(sceNpScoreGetRankingByRangeA);
FUNC(sceNpScoreGetRankingByRangeAAsync);
FUNC(sceNpScoreGetRankingByRangeAsync);
FUNC(sceNpScoreGetRankingByRangeForCrossSave);
FUNC(sceNpScoreGetRankingByRangeForCrossSaveAsync);
FUNC(sceNpScorePollAsync);
FUNC(sceNpScoreRecordGameData);
FUNC(sceNpScoreRecordGameDataAsync);
FUNC(sceNpScoreRecordScore);
FUNC(sceNpScoreRecordScoreAsync);
FUNC(sceNpScoreSanitizeComment);
FUNC(sceNpScoreSanitizeCommentAsync);
FUNC(sceNpScoreSetPlayerCharacterId);
FUNC(sceNpScoreSetThreadParam);
FUNC(sceNpScoreSetTimeout);
FUNC(sceNpScoreWaitAsync);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
