/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceCompositorAllocateIndex);
FUNC(sceCompositorCheckCrash);
FUNC(sceCompositorCommandGpuPerfBegin);
FUNC(sceCompositorCommandGpuPerfEnd);
FUNC(sceCompositorCreateIndirectRenderTarget);
FUNC(sceCompositorDeleteIndirectRenderTarget);
FUNC(sceCompositorFlush);
FUNC(sceCompositorFlushWithRepeat);
FUNC(sceCompositorGetAnotherProcessSystemAddress);
FUNC(sceCompositorGetAnotherProcessSystemSize);
FUNC(sceCompositorGetAnotherProcessVideoAddress);
FUNC(sceCompositorGetAnotherProcessVideoSize);
FUNC(sceCompositorGetCanvasHandle);
FUNC(sceCompositorGetClientList);
FUNC(sceCompositorGetDmemOffset);
FUNC(sceCompositorGetDummyAddress);
FUNC(sceCompositorGetDummySize);
FUNC(sceCompositorGetRemainedCommandNum);
FUNC(sceCompositorGetRenderTargetResolution);
FUNC(sceCompositorGetSystemAddress);
FUNC(sceCompositorGetSystemSize);
FUNC(sceCompositorGetVideoAddress);
FUNC(sceCompositorGetVideoSize);
FUNC(sceCompositorHandleProcessEvents);
FUNC(sceCompositorInit);
FUNC(sceCompositorInitWithProcessOrder);
FUNC(sceCompositorInsertThreadTraceMarker);
FUNC(sceCompositorIsDebugCaptureEnabled);
FUNC(sceCompositorIsReady4K);
FUNC(sceCompositorLockCommandBuffer);
FUNC(sceCompositorMakeCanvasHandle);
FUNC(sceCompositorMapAnotherProcess);
FUNC(sceCompositorQuit);
FUNC(sceCompositorReleaseCommandBuffer);
FUNC(sceCompositorReleaseIndex);
FUNC(sceCompositorReleaseLocalStall);
FUNC(sceCompositorReserveCommandBuffer);
FUNC(sceCompositorResetZoomCommand);
FUNC(sceCompositorSetCompositeCanvasCommandInC);
FUNC(sceCompositorSetCursorImageAddress);
FUNC(sceCompositorSetDebugPositionCommand);
FUNC(sceCompositorSetEndOfFrameCommand);
FUNC(sceCompositorSetEventCommand);
FUNC(sceCompositorSetFlipCommand);
FUNC(sceCompositorSetGameSufaceControlCommand);
FUNC(sceCompositorSetGnmContextCommand);
FUNC(sceCompositorSetIndirectCanvasCommand);
FUNC(sceCompositorSetIndirectCompositionCommand);
FUNC(sceCompositorSetIndirectRenderTargetConfigCommand);
FUNC(sceCompositorSetInvisibleCanvasCommand);
FUNC(sceCompositorSetKeepDisplayBufferCommand);
FUNC(sceCompositorSetLocalStallCommand);
FUNC(sceCompositorSetMemoryCommand);
FUNC(sceCompositorSetMorpheusState);
FUNC(sceCompositorSetPatchCommand);
FUNC(sceCompositorSetPostEventCommand);
FUNC(sceCompositorSetRepeatCommand);
FUNC(sceCompositorSetResolutionCommand);
FUNC(sceCompositorSetSeparateContextCommand);
FUNC(sceCompositorSetSystemConfigWithMask);
FUNC(sceCompositorSetVideoOutMode);
FUNC(sceCompositorSetZoomCommand);
FUNC(sceCompositorSystemConfig);
FUNC(sceCompositorWaitEndOfRendering);
FUNC(sceCompositorWaitEvent);
FUNC(sceCompositorWaitPostEvent);
FUNC(sceCompsoitorGetGpuClock);
FUNC(sceCompsoitorGetProcessRenderingTime);
FUNC(sceCompsoitorGetRenderingTime);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
