/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(MvpHttpAbort);
FUNC(MvpHttpDeInit);
FUNC(MvpHttpGet);
FUNC(MvpHttpGetLastError);
FUNC(MvpHttpHead);
FUNC(MvpHttpHeadCleanup);
FUNC(MvpHttpInit);
FUNC(MvpHttpPost);
FUNC(MvpHttpSetCert);
FUNC(MvpHttpSetRecvTimeout);
FUNC(MvpHttpSetRedirectCb);
FUNC(sceTsCloseFile);
FUNC(sceTsDisableRepresentation);
FUNC(sceTsEnableRepresentation);
FUNC(sceTsEnableStream);
FUNC(sceTsGetAvailableBW);
FUNC(sceTsGetLiveStatus);
FUNC(sceTsGetNextAuInfo);
FUNC(sceTsGetNextUnitData);
FUNC(sceTsGetRepresentationCount);
FUNC(sceTsGetRepresentationInfo);
FUNC(sceTsGetSeekWindow);
FUNC(sceTsGetStreamInfo);
FUNC(sceTsGetUrlEncryptionType);
FUNC(sceTsJumpPTS);
FUNC(sceTsOpenFile);
FUNC(sceTsOpenFileEx);
FUNC(sceTsReleaseBuffer);
FUNC(sceTsRepresentationIsEnabled);
FUNC(sceTsSetAvailableBW);
FUNC(sceTsSetStartingBW);
FUNC(sceTsStartFileStreaming);
FUNC(sceTsStopFileStreaming);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
