/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpSnsYouTubeDialogClose);
FUNC(sceNpSnsYouTubeDialogGetResult);
FUNC(sceNpSnsYouTubeDialogGetStatus);
FUNC(sceNpSnsYouTubeDialogInitialize);
FUNC(sceNpSnsYouTubeDialogOpen);
FUNC(sceNpSnsYouTubeDialogTerminate);
FUNC(sceNpSnsYouTubeDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
