/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSystemServiceActivateHevc);
FUNC(sceSystemServiceActivateHevcAbort);
FUNC(sceSystemServiceActivateHevcGetStatus);
FUNC(sceSystemServiceActivateHevcInit);
FUNC(sceSystemServiceActivateHevcIsActivated);
FUNC(sceSystemServiceActivateHevcStart);
FUNC(sceSystemServiceActivateHevcTerm);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
