/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNetCtlApAppInitWpaKey);
FUNC(sceNetCtlApAppInitWpaKeyForQa);
FUNC(sceNetCtlApAppStartWithRetry);
FUNC(sceNetCtlApAppStartWithRetryPid);
FUNC(sceNetCtlApRestart);
FUNC(sceNetCtlApRpCheckCallback);
FUNC(sceNetCtlApRpClearEvent);
FUNC(sceNetCtlApRpGetInfo);
FUNC(sceNetCtlApRpGetResult);
FUNC(sceNetCtlApRpGetState);
FUNC(sceNetCtlApRpRegisterCallback);
FUNC(sceNetCtlApRpStart);
FUNC(sceNetCtlApRpStartConf);
FUNC(sceNetCtlApRpStartWithRetry);
FUNC(sceNetCtlApRpStop);
FUNC(sceNetCtlApRpUnregisterCallback);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
