/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceVideoNativeExtEssential_CreateDecInstance);
FUNC(sceVideoNativeExtEssential_DestroyDecInstance);
FUNC(sceVideoNativeExtEssential_Finalize);
FUNC(sceVideoNativeExtEssential_Initialize);
FUNC(sceVideoNativeExtEssential_IsInit);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
