/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(scePatchCheckerCancel);
FUNC(scePatchCheckerCheckPatch);
FUNC(scePatchCheckerClearCache);
FUNC(scePatchCheckerCreateHandler);
FUNC(scePatchCheckerDestroyHandler);
FUNC(scePatchCheckerDisableAutoDownload);
FUNC(scePatchCheckerEnableAutoDownload);
FUNC(scePatchCheckerGetApplicableTick);
FUNC(scePatchCheckerGetPackageInfo);
FUNC(scePatchCheckerInitialize);
FUNC(scePatchCheckerRequestCheckPatch);
FUNC(scePatchCheckerRequestCheckPatchByType);
FUNC(scePatchCheckerSetCache);
FUNC(scePatchCheckerSetFakeCache);
FUNC(scePatchCheckerTerminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
