/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSharePlayCrashDaemon);
FUNC(sceSharePlayGetCurrentConnectionInfo);
FUNC(sceSharePlayGetCurrentConnectionInfoA);
FUNC(sceSharePlayGetCurrentInfo);
FUNC(sceSharePlayGetEvent);
FUNC(sceSharePlayInitialize);
FUNC(sceSharePlayNotifyDialogOpen);
FUNC(sceSharePlayNotifyForceCloseForCdlg);
FUNC(sceSharePlayNotifyOpenQuickMenu);
FUNC(sceSharePlayResumeScreenForCdlg);
FUNC(sceSharePlayServerLock);
FUNC(sceSharePlayServerUnLock);
FUNC(sceSharePlaySetMode);
FUNC(sceSharePlaySetProhibition);
FUNC(sceSharePlaySetProhibitionModeWithAppId);
FUNC(sceSharePlayStartStandby);
FUNC(sceSharePlayStartStreaming);
FUNC(sceSharePlayStopStandby);
FUNC(sceSharePlayStopStreaming);
FUNC(sceSharePlayTerminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
