/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceBluetoothHidDebugGetVersion);
FUNC(sceBluetoothHidDisconnectDevice);
FUNC(sceBluetoothHidGetDeviceInfo);
FUNC(sceBluetoothHidGetDeviceName);
FUNC(sceBluetoothHidGetFeatureReport);
FUNC(sceBluetoothHidGetInputReport);
FUNC(sceBluetoothHidGetReportDescriptor);
FUNC(sceBluetoothHidInit);
FUNC(sceBluetoothHidInterruptOutput);
FUNC(sceBluetoothHidParamInitialize);
FUNC(sceBluetoothHidRegisterCallback);
FUNC(sceBluetoothHidRegisterDevice);
FUNC(sceBluetoothHidSetFeatureReport);
FUNC(sceBluetoothHidSetOutputReport);
FUNC(sceBluetoothHidThreadParamInitialize);
FUNC(sceBluetoothHidUnregisterCallback);
FUNC(sceBluetoothHidUnregisterDevice);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
