/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(_ZN19JITSharedDataMemory11shared_freeEPv);
FUNC(_ZN19JITSharedDataMemory13shared_callocEmm);
FUNC(_ZN19JITSharedDataMemory13shared_mallocEm);
FUNC(_ZN19JITSharedDataMemory14shared_reallocEPvm);
FUNC(_ZN19JITSharedDataMemory15shared_mallinfoEv);
FUNC(_ZN19JITSharedDataMemory15shared_memalignEmm);
FUNC(_ZN19JITSharedDataMemory27shared_malloc_max_footprintEv);
FUNC(_ZN19JITSharedDataMemory9sbrk_infoE);
FUNC(_ZN19JITSharedTextMemory11shared_freeEPv);
FUNC(_ZN19JITSharedTextMemory15shared_mallinfoEv);
FUNC(_ZN19JITSharedTextMemory15shared_memalignEmm);
FUNC(_ZN19JITSharedTextMemory27shared_malloc_max_footprintEv);
FUNC(_ZN19JITSharedTextMemory9sbrk_infoE);
FUNC(_ZN9JITBridge12ringDoorbellEiNS_8DoorbellE);
FUNC(_ZN9JITBridge12waitDoorbellEi);
FUNC(_ZN9JITBridge14shutdownFromVMEPS_b);
FUNC(_ZN9JITBridge16initializeFromVMEPKcPPcPKNS_11RestartDataE);
FUNC(_ZN9JITBridge20shutdownFromCompilerEPS_b);
FUNC(_ZN9JITBridge22initializeFromCompilerEPKcPPcPKNS_11RestartDataE);
FUNC(_ZN9JITBridge8shutdownEb);
FUNC(_ZNK9JITBridge20sharedMemoryAreaSizeEv);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
