/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceVoiceQoSConnect);
FUNC(sceVoiceQoSCreateLocalEndpoint);
FUNC(sceVoiceQoSCreateRemoteEndpoint);
FUNC(sceVoiceQoSDeleteLocalEndpoint);
FUNC(sceVoiceQoSDeleteRemoteEndpoint);
FUNC(sceVoiceQoSDisconnect);
FUNC(sceVoiceQoSEnd);
FUNC(sceVoiceQoSGetConnectionAttribute);
FUNC(sceVoiceQoSGetLocalEndpoint);
FUNC(sceVoiceQoSGetLocalEndpointAttribute);
FUNC(sceVoiceQoSGetRemoteEndpoint);
FUNC(sceVoiceQoSGetRemoteEndpointAttribute);
FUNC(sceVoiceQoSGetStatus);
FUNC(sceVoiceQoSInit);
FUNC(sceVoiceQoSInitHQ);
FUNC(sceVoiceQoSReadPacket);
FUNC(sceVoiceQoSSetConnectionAttribute);
FUNC(sceVoiceQoSSetLocalEndpointAttribute);
FUNC(sceVoiceQoSSetRemoteEndpointAttribute);
FUNC(sceVoiceQoSWritePacket);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
