/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceWebBrowserDialogClose);
FUNC(sceWebBrowserDialogGetEvent);
FUNC(sceWebBrowserDialogGetResult);
FUNC(sceWebBrowserDialogGetStatus);
FUNC(sceWebBrowserDialogInitialize);
FUNC(sceWebBrowserDialogNavigate);
FUNC(sceWebBrowserDialogOpen);
FUNC(sceWebBrowserDialogOpenForPredeterminedContent);
FUNC(sceWebBrowserDialogResetCookie);
FUNC(sceWebBrowserDialogSetCookie);
FUNC(sceWebBrowserDialogSetZoom);
FUNC(sceWebBrowserDialogTerminate);
FUNC(sceWebBrowserDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
