/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpCommerceDialogClose);
FUNC(sceNpCommerceDialogGetResult);
FUNC(sceNpCommerceDialogGetStatus);
FUNC(sceNpCommerceDialogInitialize);
FUNC(sceNpCommerceDialogInitializeInternal);
FUNC(sceNpCommerceDialogOpen);
FUNC(sceNpCommerceDialogTerminate);
FUNC(sceNpCommerceDialogUpdateStatus);
FUNC(sceNpCommerceHidePsStoreIcon);
FUNC(sceNpCommerceSetPsStoreIconLayout);
FUNC(sceNpCommerceShowPsStoreIcon);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
