/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceVrTrackerCpuProcess);
FUNC(sceVrTrackerGetPlayAreaWarningInfo);
FUNC(sceVrTrackerGetResult);
FUNC(sceVrTrackerGetTime);
FUNC(sceVrTrackerGpuSubmit);
FUNC(sceVrTrackerGpuWait);
FUNC(sceVrTrackerGpuWaitAndCpuProcess);
FUNC(sceVrTrackerInit);
FUNC(sceVrTrackerNotifyEndOfCpuProcess);
FUNC(sceVrTrackerQueryMemory);
FUNC(sceVrTrackerRecalibrate);
FUNC(sceVrTrackerRegisterDevice);
FUNC(sceVrTrackerRegisterDeviceInternal);
FUNC(sceVrTrackerResetAll);
FUNC(sceVrTrackerResetOrientationRelative);
FUNC(sceVrTrackerSaveInternalBuffers);
FUNC(sceVrTrackerSetDurationUntilStatusNotTracking);
FUNC(sceVrTrackerSetExtendedMode);
FUNC(sceVrTrackerSetLEDBrightness);
FUNC(sceVrTrackerSetRestingMode);
FUNC(sceVrTrackerTerm);
FUNC(sceVrTrackerUnregisterDevice);
FUNC(sceVrTrackerUpdateMotionSensorData);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
