/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(_ZN4Manx11RunLoopImpl4initEv);
FUNC(_ZN4Manx27monotonicallyIncreasingTimeEv);
FUNC(_ZN4Manx6System19setVirtualRangeNameEPvmPKc);
FUNC(_ZN4Manx6System21defaultThreadPriorityEv);
FUNC(_ZN4Manx6System24setDefaultThreadPriorityEi);
FUNC(_ZN4Manx6System6osNameEv);
FUNC(_ZN4Manx7RunLoop3runEv);
FUNC(_ZN4Manx7RunLoop4pollEv);
FUNC(_ZN4Manx7RunLoop7currentEv);
FUNC(pa_pop_marker);
FUNC(pa_push_marker);
FUNC(pa_set_functions);
FUNC(pa_sync);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
