/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpEulaDialogCheckVersion);
FUNC(sceNpEulaDialogCheckVersionAbort);
FUNC(sceNpEulaDialogClose);
FUNC(sceNpEulaDialogGetResult);
FUNC(sceNpEulaDialogGetStatus);
FUNC(sceNpEulaDialogInitialize);
FUNC(sceNpEulaDialogOpen);
FUNC(sceNpEulaDialogTerminate);
FUNC(sceNpEulaDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
