/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceOpusCeltEncCreate);
FUNC(sceOpusCeltEncCtl);
FUNC(sceOpusCeltEncDestroy);
FUNC(sceOpusCeltEncEncode);
FUNC(sceOpusCeltEncEncodeFloat);
FUNC(sceOpusCeltEncEncodeFloatWithPriority);
FUNC(sceOpusCeltEncEncodeWithPriority);
FUNC(sceOpusCeltEncGetSize);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
