/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSdecCreateSw2);
FUNC(sceSdecDestroySw2);
FUNC(sceSdecGetVersionSw2);
FUNC(sceSdecQueryMemorySw2);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
