/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpSnsFacebookAbortRequest);
FUNC(sceNpSnsFacebookCreateRequest);
FUNC(sceNpSnsFacebookDeleteRequest);
FUNC(sceNpSnsFacebookGetAccessToken);
FUNC(sceNpSnsIntAbortRequest);
FUNC(sceNpSnsIntCreateRequest);
FUNC(sceNpSnsIntDeleteRequest);
FUNC(sceNpSnsIntFbGetGameAccessToken);
FUNC(sceNpSnsIntFbGetGameAccessTokenAllowed);
FUNC(sceNpSnsIntFbGetSystemAccessToken);
FUNC(sceNpSnsIntFbGetTitleInfo);
FUNC(sceNpSnsIntLinkedStatus);
FUNC(sceNpSnsIntPostOpenGraph);
FUNC(sceNpSnsIntTest);
FUNC(sceNpSnsIntTwGetSystemAccessToken);
FUNC(sceNpSnsIntUnlink);
FUNC(sceNpSnsIntYtGetAccessToken);
FUNC(sceNpSnsIntYtRefreshMasterToken);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
