/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceMusicCoreServerForceKillCurrentCore);
FUNC(sceMusicCoreServerGetCoreInfo);
FUNC(sceMusicCoreServerGetEvent);
FUNC(sceMusicCoreServerGetPlayStartCondition);
FUNC(sceMusicCoreServerGetPlayStatus);
FUNC(sceMusicCoreServerGetSpTrackInfo);
FUNC(sceMusicCoreServerGetSpWakeupAuthorityList);
FUNC(sceMusicCoreServerGetStatusOfTracks);
FUNC(sceMusicCoreServerGetTitleId);
FUNC(sceMusicCoreServerGetTrackInfo);
FUNC(sceMusicCoreServerInitialize);
FUNC(sceMusicCoreServerKillCurrentCore);
FUNC(sceMusicCoreServerLaunchSpCore);
FUNC(sceMusicCoreServerLaunchUsbMusicCore);
FUNC(sceMusicCoreServerPlayControl);
FUNC(sceMusicCoreServerPlaySpUri);
FUNC(sceMusicCoreServerSetAudioVolume);
FUNC(sceMusicCoreServerSetRepeatMode);
FUNC(sceMusicCoreServerSetShuffle);
FUNC(sceMusicCoreServerSetSpWakeupAuthorityList);
FUNC(sceMusicCoreServerSetTrackList);
FUNC(sceMusicCoreServerTerminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
