/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSpGetPid);
FUNC(sceSpKernelGettimeofday);
FUNC(sceSpKernelNanosleep);
FUNC(sceSpNetConnect);
FUNC(sceSpNetEpollAbort);
FUNC(sceSpNetEpollControl);
FUNC(sceSpNetEpollCreate);
FUNC(sceSpNetEpollDestroy);
FUNC(sceSpNetEpollWait);
FUNC(sceSpNetErrnoLoc);
FUNC(sceSpNetPoolCreate);
FUNC(sceSpNetPoolDestroy);
FUNC(sceSpNetRecv);
FUNC(sceSpNetResolverAbort);
FUNC(sceSpNetResolverCreate);
FUNC(sceSpNetResolverDestroy);
FUNC(sceSpNetResolverGetError);
FUNC(sceSpNetResolverStartNtoa);
FUNC(sceSpNetSend);
FUNC(sceSpNetSetsockopt);
FUNC(sceSpNetSocket);
FUNC(sceSpNetSocketClose);
FUNC(sceSpPthreadAttrDestroy);
FUNC(sceSpPthreadAttrInit);
FUNC(sceSpPthreadAttrSetinheritsched);
FUNC(sceSpPthreadAttrSetschedparam);
FUNC(sceSpPthreadAttrSetstacksize);
FUNC(sceSpPthreadCondattrDestroy);
FUNC(sceSpPthreadCondattrInit);
FUNC(sceSpPthreadCondDestroy);
FUNC(sceSpPthreadCondInit);
FUNC(sceSpPthreadCondSignal);
FUNC(sceSpPthreadCondWait);
FUNC(sceSpPthreadCreate);
FUNC(sceSpPthreadDetach);
FUNC(sceSpPthreadExit);
FUNC(sceSpPthreadJoin);
FUNC(sceSpPthreadMutexattrDestroy);
FUNC(sceSpPthreadMutexattrInit);
FUNC(sceSpPthreadMutexattrSetprioceiling);
FUNC(sceSpPthreadMutexattrSetprotocol);
FUNC(sceSpPthreadMutexattrSettype);
FUNC(sceSpPthreadMutexDestroy);
FUNC(sceSpPthreadMutexInit);
FUNC(sceSpPthreadMutexLock);
FUNC(sceSpPthreadMutexUnlock);
FUNC(sceSpPthreadSetprio);
FUNC(sceSpSelect);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
