/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpMatching2AbortContextStart);
FUNC(sceNpMatching2ContextStart);
FUNC(sceNpMatching2ContextStop);
FUNC(sceNpMatching2CreateContext);
FUNC(sceNpMatching2CreateContextA);
FUNC(sceNpMatching2CreateContextInternal);
FUNC(sceNpMatching2CreateJoinRoom);
FUNC(sceNpMatching2CreateJoinRoomA);
FUNC(sceNpMatching2DestroyContext);
FUNC(sceNpMatching2GetLobbyInfoList);
FUNC(sceNpMatching2GetLobbyMemberDataInternal);
FUNC(sceNpMatching2GetLobbyMemberDataInternalList);
FUNC(sceNpMatching2GetMemoryInfo);
FUNC(sceNpMatching2GetRoomDataExternalList);
FUNC(sceNpMatching2GetRoomDataInternal);
FUNC(sceNpMatching2GetRoomJoinedSlotMaskLocal);
FUNC(sceNpMatching2GetRoomMemberDataExternalList);
FUNC(sceNpMatching2GetRoomMemberDataInternal);
FUNC(sceNpMatching2GetRoomMemberIdListLocal);
FUNC(sceNpMatching2GetRoomPasswordLocal);
FUNC(sceNpMatching2GetServerId);
FUNC(sceNpMatching2GetSignalingOptParamLocal);
FUNC(sceNpMatching2GetSslMemoryInfo);
FUNC(sceNpMatching2GetUserInfoList);
FUNC(sceNpMatching2GetUserInfoListA);
FUNC(sceNpMatching2GetWorldIdArrayForAllServers);
FUNC(sceNpMatching2GetWorldInfoList);
FUNC(sceNpMatching2GrantRoomOwner);
FUNC(sceNpMatching2Initialize);
FUNC(sceNpMatching2JoinLobby);
FUNC(sceNpMatching2JoinRoom);
FUNC(sceNpMatching2JoinRoomA);
FUNC(sceNpMatching2KickoutRoomMember);
FUNC(sceNpMatching2LeaveLobby);
FUNC(sceNpMatching2LeaveRoom);
FUNC(sceNpMatching2RegisterContextCallback);
FUNC(sceNpMatching2RegisterLobbyEventCallback);
FUNC(sceNpMatching2RegisterLobbyMessageCallback);
FUNC(sceNpMatching2RegisterManualUdpSignalingCallback);
FUNC(sceNpMatching2RegisterRoomEventCallback);
FUNC(sceNpMatching2RegisterRoomMessageCallback);
FUNC(sceNpMatching2RegisterSignalingCallback);
FUNC(sceNpMatching2SearchRoom);
FUNC(sceNpMatching2SendLobbyChatMessage);
FUNC(sceNpMatching2SendRoomChatMessage);
FUNC(sceNpMatching2SendRoomMessage);
FUNC(sceNpMatching2SetDefaultRequestOptParam);
FUNC(sceNpMatching2SetExtraInitParam);
FUNC(sceNpMatching2SetLobbyMemberDataInternal);
FUNC(sceNpMatching2SetRoomDataExternal);
FUNC(sceNpMatching2SetRoomDataInternal);
FUNC(sceNpMatching2SetRoomDataInternalExt);
FUNC(sceNpMatching2SetRoomMemberDataInternal);
FUNC(sceNpMatching2SetSignalingOptParam);
FUNC(sceNpMatching2SetUserInfo);
FUNC(sceNpMatching2SignalingAbortConnection);
FUNC(sceNpMatching2SignalingCancelPeerNetInfo);
FUNC(sceNpMatching2SignalingEnableManualUdpMode);
FUNC(sceNpMatching2SignalingEstablishConnection);
FUNC(sceNpMatching2SignalingGetConnectionInfo);
FUNC(sceNpMatching2SignalingGetConnectionInfoA);
FUNC(sceNpMatching2SignalingGetConnectionStatus);
FUNC(sceNpMatching2SignalingGetLocalNetInfo);
FUNC(sceNpMatching2SignalingGetPeerNetInfo);
FUNC(sceNpMatching2SignalingGetPeerNetInfoResult);
FUNC(sceNpMatching2SignalingGetPingInfo);
FUNC(sceNpMatching2SignalingGetPort);
FUNC(sceNpMatching2SignalingSetPort);
FUNC(sceNpMatching2Terminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
