/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpSnsFacebookDialogClose);
FUNC(sceNpSnsFacebookDialogGetResult);
FUNC(sceNpSnsFacebookDialogGetStatus);
FUNC(sceNpSnsFacebookDialogInitialize);
FUNC(sceNpSnsFacebookDialogOpen);
FUNC(sceNpSnsFacebookDialogTerminate);
FUNC(sceNpSnsFacebookDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
