/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceInvitationDialogClose);
FUNC(sceInvitationDialogGetResult);
FUNC(sceInvitationDialogGetResultA);
FUNC(sceInvitationDialogGetStatus);
FUNC(sceInvitationDialogInitialize);
FUNC(sceInvitationDialogOpen);
FUNC(sceInvitationDialogOpenA);
FUNC(sceInvitationDialogTerminate);
FUNC(sceInvitationDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
