/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceEditMp4Abort);
FUNC(sceEditMp4Edit);
FUNC(sceEditMp4GetStatus);
FUNC(sceEditMp4Initialize);
FUNC(sceEditMp4InitializeParam);
FUNC(sceEditMp4QueryMemSize);
FUNC(sceEditMp4SetFinishCallback);
FUNC(sceEditMp4Terminate);
FUNC(sceEditMp4Unite);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
