/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceKeyboardClose);
FUNC(sceKeyboardConnectPort);
FUNC(sceKeyboardDebugGetDeviceId);
FUNC(sceKeyboardDeviceOpen);
FUNC(sceKeyboardDisconnectDevice);
FUNC(sceKeyboardDisconnectPort);
FUNC(sceKeyboardGetConnection);
FUNC(sceKeyboardGetDeviceInfo);
FUNC(sceKeyboardGetKey2Char);
FUNC(sceKeyboardInit);
FUNC(sceKeyboardMbusInit);
FUNC(sceKeyboardOpen);
FUNC(sceKeyboardRead);
FUNC(sceKeyboardReadState);
FUNC(sceKeyboardSetProcessFocus);
FUNC(sceKeyboardSetProcessPrivilege);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
