/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(audiodeccpuinternal_core_ops_m4aac2);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
