/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNetCtlApDialogClose);
FUNC(sceNetCtlApDialogGetResult);
FUNC(sceNetCtlApDialogGetStatus);
FUNC(sceNetCtlApDialogInitialize);
FUNC(sceNetCtlApDialogOpen);
FUNC(sceNetCtlApDialogTerminate);
FUNC(sceNetCtlApDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
