/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceVideodecCreateDecoder);
FUNC(sceVideodecDecode);
FUNC(sceVideodecDeleteDecoder);
FUNC(sceVideodecFlush);
FUNC(sceVideodecMapMemory);
FUNC(sceVideodecQueryResourceInfo);
FUNC(sceVideodecReset);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
