/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceRemoteplayApprove);
FUNC(sceRemoteplayChangeEnterKey);
FUNC(sceRemoteplayClearAllRegistData);
FUNC(sceRemoteplayClearConnectHistory);
FUNC(sceRemoteplayConfirmDeviceRegist);
FUNC(sceRemoteplayDisconnect);
FUNC(sceRemoteplayGeneratePinCode);
FUNC(sceRemoteplayGetApMode);
FUNC(sceRemoteplayGetConnectHistory);
FUNC(sceRemoteplayGetConnectionStatus);
FUNC(sceRemoteplayGetConnectUserId);
FUNC(sceRemoteplayGetMbusDeviceInfo);
FUNC(sceRemoteplayGetOperationStatus);
FUNC(sceRemoteplayGetRemoteplayStatus);
FUNC(sceRemoteplayGetRpMode);
FUNC(sceRemoteplayImeClose);
FUNC(sceRemoteplayImeFilterResult);
FUNC(sceRemoteplayImeGetEvent);
FUNC(sceRemoteplayImeNotify);
FUNC(sceRemoteplayImeNotifyEventResult);
FUNC(sceRemoteplayImeOpen);
FUNC(sceRemoteplayImeSetCaret);
FUNC(sceRemoteplayImeSetText);
FUNC(sceRemoteplayInitialize);
FUNC(sceRemoteplayIsRemoteOskReady);
FUNC(sceRemoteplayIsRemotePlaying);
FUNC(sceRemoteplayNotifyMbusDeviceRegistComplete);
FUNC(sceRemoteplayNotifyNpPushWakeup);
FUNC(sceRemoteplayNotifyPinCodeError);
FUNC(sceRemoteplayNotifyUserDelete);
FUNC(sceRemoteplayPrintAllRegistData);
FUNC(sceRemoteplayProhibit);
FUNC(sceRemoteplayProhibitStreaming);
FUNC(sceRemoteplayServerLock);
FUNC(sceRemoteplayServerUnLock);
FUNC(sceRemoteplaySetApMode);
FUNC(sceRemoteplaySetLogLevel);
FUNC(sceRemoteplaySetProhibition);
FUNC(sceRemoteplaySetProhibitionForVsh);
FUNC(sceRemoteplaySetRpMode);
FUNC(sceRemoteplayTerminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
