/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceMbusAcquireControl);
FUNC(sceMbusAcquireControlList);
FUNC(sceMbusAcquireControlWithState);
FUNC(sceMbusAcquireControlWithState2);
FUNC(sceMbusAcquireControlWithStateFlag);
FUNC(sceMbusAddAudioOutHandleAttribute);
FUNC(sceMbusAddHandle);
FUNC(sceMbusAddHandleByDeviceId);
FUNC(sceMbusAddHandleByUserId);
FUNC(sceMbusAddHandleByVidPid);
FUNC(sceMbusAddHandleWithModuleId);
FUNC(sceMbusAttachToApplicationByPid);
FUNC(sceMbusBindDeviceWithUserId);
FUNC(sceMbusChangeAppModuleState);
FUNC(sceMbusCheckDriverCallback);
FUNC(sceMbusConvertToLocalDeviceId);
FUNC(sceMbusConvertToLocalDeviceId2);
FUNC(sceMbusConvertToMbusDeviceId);
FUNC(sceMbusDetachFromApplicationByPid);
FUNC(sceMbusDisableBgmForShellUi);
FUNC(sceMbusDisconnectDevice);
FUNC(sceMbusDumpAppInfo);
FUNC(sceMbusDumpDeviceInfo);
FUNC(sceMbusDumpHandleStatusInfo);
FUNC(sceMbusDumpHandleStatusInfoAll);
FUNC(sceMbusDumpModuleStateInfo);
FUNC(sceMbusDumpModuleStateInfoAll);
FUNC(sceMbusDumpPlayerInfo);
FUNC(sceMbusDumpPortHandleInfo);
FUNC(sceMbusDumpProcMediaInfo);
FUNC(sceMbusDumpProcMediaInfoAll);
FUNC(sceMbusDumpUserMediaInfo);
FUNC(sceMbusEnterAudioOutAutoAttenuation);
FUNC(sceMbusEventBusStatusChangeSubscribe);
FUNC(sceMbusEventBusStatusChangeUnsubscribe);
FUNC(sceMbusEventCallbackFuncsInit_);
FUNC(sceMbusEventCreate_);
FUNC(sceMbusEventDestroy);
FUNC(sceMbusEventReceive);
FUNC(sceMbusGetControlStatus);
FUNC(sceMbusGetDeviceDescription);
FUNC(sceMbusGetDeviceInfo_);
FUNC(sceMbusGetDeviceInfoByBusId_);
FUNC(sceMbusGetDeviceInfoByCondition_);
FUNC(sceMbusGetDeviceInfoByConditionForDeviceService);
FUNC(sceMbusGetSimulatedBusUsableStatusByBusType);
FUNC(sceMbusGetSimulatedHandleStatusInfo);
FUNC(sceMbusGetSimulatedHandleStatusInfo2);
FUNC(sceMbusGetSparkState);
FUNC(sceMbusInit);
FUNC(sceMbusIsBgmProhibited);
FUNC(sceMbusIsUsingDevice);
FUNC(sceMbusLeaveAudioOutAutoAttenuation);
FUNC(sceMbusNotifyDriverEvent);
FUNC(sceMbusReenableBgmForShellUi);
FUNC(sceMbusRegisterDriver);
FUNC(sceMbusReleaseControl);
FUNC(sceMbusRemoveAudioOutHandleAttribute);
FUNC(sceMbusRemoveCameraAppModuleFocus);
FUNC(sceMbusRemoveHandle);
FUNC(sceMbusRemoveProxy);
FUNC(sceMbusResolveByDeviceId);
FUNC(sceMbusResolveByHandle);
FUNC(sceMbusResolveByPlayerId);
FUNC(sceMbusResolveByUserId);
FUNC(sceMbusSetAutoLoginMode);
FUNC(sceMbusSetCameraAppModuleFocus);
FUNC(sceMbusSetDeviceFunctionState);
FUNC(sceMbusSetDuckingSetting);
FUNC(sceMbusSetProxy);
FUNC(sceMbusSetRoutingMode);
FUNC(sceMbusSetScratchData);
FUNC(sceMbusSetScratchDataUpdatedEventMask);
FUNC(sceMbusSetSocialScreenAudioMode);
FUNC(sceMbusSetTestFlag);
FUNC(sceMbusSetThreadParam);
FUNC(sceMbusSetUsbPowerBlackList);
FUNC(sceMbusStartAudioOutAuxBroadcast);
FUNC(sceMbusStartAudioOutSharePlay);
FUNC(sceMbusStopAudioOutAuxBroadcast);
FUNC(sceMbusStopAudioOutSharePlay);
FUNC(sceMbusTerm);
FUNC(sceMbusUnregisterDriver);
FUNC(sceMbusUserLogin);
FUNC(sceMbusUserLogout);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
