/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpCheckNpAvailability);
FUNC(sceNpGetAccountCountry);
FUNC(sceNpGetAccountDateOfBirth);
FUNC(sceNpGetAccountId);
FUNC(sceNpGetAccountLanguage);
FUNC(sceNpGetGamePresenceStatus);
FUNC(sceNpGetParentalControlInfo);
FUNC(sceNpGetUserIdByOnlineId);
FUNC(sceNpInGameMessagePrepare);
FUNC(sceNpInGameMessageSendData);
FUNC(sceNpRegisterGamePresenceCallback);
FUNC(sceNpRegisterStateCallback);
FUNC(sceNpSetGamePresenceOnline);
FUNC(sceNpUnregisterStateCallback);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
