/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpAuthAbortRequest);
FUNC(sceNpAuthCreateAsyncRequest);
FUNC(sceNpAuthCreateRequest);
FUNC(sceNpAuthDeleteRequest);
FUNC(sceNpAuthGetAuthorizationCode);
FUNC(sceNpAuthGetAuthorizationCodeA);
FUNC(sceNpAuthGetAuthorizationCodeV3);
FUNC(sceNpAuthGetIdToken);
FUNC(sceNpAuthGetIdTokenA);
FUNC(sceNpAuthGetIdTokenV3);
FUNC(sceNpAuthPollAsync);
FUNC(sceNpAuthSetTimeout);
FUNC(sceNpAuthWaitAsync);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
