/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceCoredumpAttachMemoryRegion);
FUNC(sceCoredumpAttachMemoryRegionAsUserFile);
FUNC(sceCoredumpAttachUserFile);
FUNC(sceCoredumpAttachUserMemoryFile);
FUNC(sceCoredumpConfigDumpMode);
FUNC(sceCoredumpDebugTextOut);
FUNC(sceCoredumpGetStopInfoCpu);
FUNC(sceCoredumpGetStopInfoGpu);
FUNC(sceCoredumpGetThreadContextInfo);
FUNC(sceCoredumpInternalGetThreadContextInfo);
FUNC(sceCoredumpRegisterCoredumpHandler);
FUNC(sceCoredumpSetUserDataType);
FUNC(sceCoredumpUnregisterCoredumpHandler);
FUNC(sceCoredumpWriteUserData);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
