/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpWebApiAbortHandle);
FUNC(sceNpWebApiAbortRequest);
FUNC(sceNpWebApiAddHttpRequestHeader);
FUNC(sceNpWebApiAddMultipartPart);
FUNC(sceNpWebApiCheckTimeout);
FUNC(sceNpWebApiClearAllUnusedConnection);
FUNC(sceNpWebApiClearUnusedConnection);
FUNC(sceNpWebApiCreateContext);
FUNC(sceNpWebApiCreateContextA);
FUNC(sceNpWebApiCreateExtdPushEventFilter);
FUNC(sceNpWebApiCreateHandle);
FUNC(sceNpWebApiCreateMultipartRequest);
FUNC(sceNpWebApiCreatePushEventFilter);
FUNC(sceNpWebApiCreateRequest);
FUNC(sceNpWebApiCreateServicePushEventFilter);
FUNC(sceNpWebApiDeleteContext);
FUNC(sceNpWebApiDeleteExtdPushEventFilter);
FUNC(sceNpWebApiDeleteHandle);
FUNC(sceNpWebApiDeletePushEventFilter);
FUNC(sceNpWebApiDeleteRequest);
FUNC(sceNpWebApiDeleteServicePushEventFilter);
FUNC(sceNpWebApiGetConnectionStats);
FUNC(sceNpWebApiGetErrorCode);
FUNC(sceNpWebApiGetHttpResponseHeaderValue);
FUNC(sceNpWebApiGetHttpResponseHeaderValueLength);
FUNC(sceNpWebApiGetHttpStatusCode);
FUNC(sceNpWebApiGetMemoryPoolStats);
FUNC(sceNpWebApiInitialize);
FUNC(sceNpWebApiInitializeForPresence);
FUNC(sceNpWebApiIntCreateCtxIndExtdPushEventFilter);
FUNC(sceNpWebApiIntCreateRequest);
FUNC(sceNpWebApiIntCreateServicePushEventFilter);
FUNC(sceNpWebApiIntInitialize);
FUNC(sceNpWebApiIntRegisterServicePushEventCallback);
FUNC(sceNpWebApiIntRegisterServicePushEventCallbackA);
FUNC(sceNpWebApiReadData);
FUNC(sceNpWebApiRegisterExtdPushEventCallback);
FUNC(sceNpWebApiRegisterExtdPushEventCallbackA);
FUNC(sceNpWebApiRegisterNotificationCallback);
FUNC(sceNpWebApiRegisterPushEventCallback);
FUNC(sceNpWebApiRegisterServicePushEventCallback);
FUNC(sceNpWebApiSendMultipartRequest);
FUNC(sceNpWebApiSendMultipartRequest2);
FUNC(sceNpWebApiSendRequest);
FUNC(sceNpWebApiSendRequest2);
FUNC(sceNpWebApiSetHandleTimeout);
FUNC(sceNpWebApiSetMaxConnection);
FUNC(sceNpWebApiSetMultipartContentType);
FUNC(sceNpWebApiSetRequestTimeout);
FUNC(sceNpWebApiTerminate);
FUNC(sceNpWebApiUnregisterExtdPushEventCallback);
FUNC(sceNpWebApiUnregisterNotificationCallback);
FUNC(sceNpWebApiUnregisterPushEventCallback);
FUNC(sceNpWebApiUnregisterServicePushEventCallback);
FUNC(sceNpWebApiUtilityParseNpId);
FUNC(sceNpWebApiVshInitialize);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
