/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpTrophyAbortHandle);
FUNC(sceNpTrophyCaptureScreenshot);
FUNC(sceNpTrophyConfigGetTrophyDetails);
FUNC(sceNpTrophyConfigGetTrophyFlagArray);
FUNC(sceNpTrophyConfigGetTrophyGroupArray);
FUNC(sceNpTrophyConfigGetTrophyGroupDetails);
FUNC(sceNpTrophyConfigGetTrophySetInfo);
FUNC(sceNpTrophyConfigGetTrophySetInfoInGroup);
FUNC(sceNpTrophyConfigGetTrophySetVersion);
FUNC(sceNpTrophyConfigGetTrophyTitleDetails);
FUNC(sceNpTrophyConfigHasGroupFeature);
FUNC(sceNpTrophyCreateContext);
FUNC(sceNpTrophyCreateHandle);
FUNC(sceNpTrophyDestroyContext);
FUNC(sceNpTrophyDestroyHandle);
FUNC(sceNpTrophyGetGameIcon);
FUNC(sceNpTrophyGetGameInfo);
FUNC(sceNpTrophyGetGroupIcon);
FUNC(sceNpTrophyGetGroupInfo);
FUNC(sceNpTrophyGetTrophyIcon);
FUNC(sceNpTrophyGetTrophyInfo);
FUNC(sceNpTrophyGetTrophyUnlockState);
FUNC(sceNpTrophyGroupArrayGetNum);
FUNC(sceNpTrophyIntAbortHandle);
FUNC(sceNpTrophyIntCheckNetSyncTitles);
FUNC(sceNpTrophyIntCreateHandle);
FUNC(sceNpTrophyIntDestroyHandle);
FUNC(sceNpTrophyIntGetLocalTrophySummary);
FUNC(sceNpTrophyIntGetProgress);
FUNC(sceNpTrophyIntGetRunningTitle);
FUNC(sceNpTrophyIntGetRunningTitles);
FUNC(sceNpTrophyIntGetTrpIconByUri);
FUNC(sceNpTrophyIntNetSyncTitle);
FUNC(sceNpTrophyIntNetSyncTitles);
FUNC(sceNpTrophyNumInfoGetTotal);
FUNC(sceNpTrophyRegisterContext);
FUNC(sceNpTrophySetInfoGetTrophyFlagArray);
FUNC(sceNpTrophySetInfoGetTrophyNum);
FUNC(sceNpTrophyShowTrophyList);
FUNC(sceNpTrophySystemAbortHandle);
FUNC(sceNpTrophySystemBuildGroupIconUri);
FUNC(sceNpTrophySystemBuildNetTrophyIconUri);
FUNC(sceNpTrophySystemBuildTitleIconUri);
FUNC(sceNpTrophySystemBuildTrophyIconUri);
FUNC(sceNpTrophySystemCheckNetSyncTitles);
FUNC(sceNpTrophySystemCheckRecoveryRequired);
FUNC(sceNpTrophySystemCloseStorage);
FUNC(sceNpTrophySystemCreateContext);
FUNC(sceNpTrophySystemCreateHandle);
FUNC(sceNpTrophySystemDbgCtl);
FUNC(sceNpTrophySystemDebugLockTrophy);
FUNC(sceNpTrophySystemDebugUnlockTrophy);
FUNC(sceNpTrophySystemDestroyContext);
FUNC(sceNpTrophySystemDestroyHandle);
FUNC(sceNpTrophySystemDestroyTrophyConfig);
FUNC(sceNpTrophySystemGetDbgParam);
FUNC(sceNpTrophySystemGetDbgParamInt);
FUNC(sceNpTrophySystemGetGroupIcon);
FUNC(sceNpTrophySystemGetLocalTrophySummary);
FUNC(sceNpTrophySystemGetNextTitleFileEntryStatus);
FUNC(sceNpTrophySystemGetProgress);
FUNC(sceNpTrophySystemGetTitleFileStatus);
FUNC(sceNpTrophySystemGetTitleIcon);
FUNC(sceNpTrophySystemGetTitleSyncStatus);
FUNC(sceNpTrophySystemGetTrophyConfig);
FUNC(sceNpTrophySystemGetTrophyData);
FUNC(sceNpTrophySystemGetTrophyGroupData);
FUNC(sceNpTrophySystemGetTrophyIcon);
FUNC(sceNpTrophySystemGetTrophyTitleData);
FUNC(sceNpTrophySystemGetTrophyTitleIds);
FUNC(sceNpTrophySystemGetUserFileInfo);
FUNC(sceNpTrophySystemGetUserFileStatus);
FUNC(sceNpTrophySystemIsServerAvailable);
FUNC(sceNpTrophySystemNetSyncTitle);
FUNC(sceNpTrophySystemNetSyncTitles);
FUNC(sceNpTrophySystemOpenStorage);
FUNC(sceNpTrophySystemPerformRecovery);
FUNC(sceNpTrophySystemRemoveAll);
FUNC(sceNpTrophySystemRemoveTitleData);
FUNC(sceNpTrophySystemRemoveUserData);
FUNC(sceNpTrophySystemSetDbgParam);
FUNC(sceNpTrophySystemSetDbgParamInt);
FUNC(sceNpTrophyUnlockTrophy);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
