/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceContentBinderEnd);
FUNC(sceContentBinderGetNumOfDifference);
FUNC(sceContentBinderInitialize);
FUNC(sceContentBinderIsUpdated);
FUNC(sceContentBinderReset);
FUNC(sceContentBinderSearchDifference);
FUNC(sceContentBinderStart);
FUNC(sceContentBinderTerminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
