/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(_ZN23sceMetadataReaderWriter10jpegParser18jpegParserFinalizeEv);
FUNC(_ZN23sceMetadataReaderWriter10jpegParser20jpegParserInitializeEv);
FUNC(_ZN23sceMetadataReaderWriter10jpegParser22jpegParserReadMetadataERKSsRKNS_8MetadataERS3_);
FUNC(_ZN23sceMetadataReaderWriter10jpegParser23jpegParserWriteMetadataERKSsRKNS_8MetadataE);
FUNC(_ZN23sceMetadataReaderWriter10jpegParser26jpegParserExtractThumbnailERKSsRNS_9ThumbnailE);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
