/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceTextToSpeechCancelImpl);
FUNC(sceTextToSpeechCloseImpl);
FUNC(sceTextToSpeechGetStatusImpl);
FUNC(sceTextToSpeechInitImpl);
FUNC(sceTextToSpeechOpenImpl);
FUNC(sceTextToSpeechPauseImpl);
FUNC(sceTextToSpeechResumeImpl);
FUNC(sceTextToSpeechSpeakContinuousImpl);
FUNC(sceTextToSpeechSpeakImpl);
FUNC(sceTextToSpeechTermImpl);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
