/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpScoreCreateNpTitleCtx);
FUNC(sceNpScoreGetFriendsRanking);
FUNC(sceNpScoreGetFriendsRankingAsync);
FUNC(sceNpScoreGetGameData);
FUNC(sceNpScoreGetGameDataAsync);
FUNC(sceNpScoreGetRankingByNpId);
FUNC(sceNpScoreGetRankingByNpIdAsync);
FUNC(sceNpScoreGetRankingByNpIdPcId);
FUNC(sceNpScoreGetRankingByNpIdPcIdAsync);
FUNC(sceNpScoreGetRankingByRange);
FUNC(sceNpScoreGetRankingByRangeAsync);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
