/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpFriendListDialogClose);
FUNC(sceNpFriendListDialogGetResult);
FUNC(sceNpFriendListDialogGetResultA);
FUNC(sceNpFriendListDialogGetStatus);
FUNC(sceNpFriendListDialogInitialize);
FUNC(sceNpFriendListDialogOpen);
FUNC(sceNpFriendListDialogOpenA);
FUNC(sceNpFriendListDialogTerminate);
FUNC(sceNpFriendListDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
