/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpGameIntentGetPropertyValueString);
FUNC(sceNpGameIntentInitialize);
FUNC(sceNpGameIntentLaunchApp);
FUNC(sceNpGameIntentLaunchApp2);
FUNC(sceNpGameIntentNotifyAppLaunched);
FUNC(sceNpGameIntentReceiveIntent);
FUNC(sceNpGameIntentTerminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
