/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceMbusDebugAcquireControl);
FUNC(sceMbusDebugAcquireControlWithState);
FUNC(sceMbusDebugAcquireControlWithState2);
FUNC(sceMbusDebugAcquireControlWithStateFlag);
FUNC(sceMbusDebugAddProcess);
FUNC(sceMbusDebugCheckProcessResume);
FUNC(sceMbusDebugDisableBgmForShellUi);
FUNC(sceMbusDebugGetApplicationStartupInfo);
FUNC(sceMbusDebugGetControlStatus);
FUNC(sceMbusDebugGetDeviceInfo);
FUNC(sceMbusDebugGetInternalInfo);
FUNC(sceMbusDebugGetPriorityInfo);
FUNC(sceMbusDebugReenableBgmForShellUi);
FUNC(sceMbusDebugReleaseControl);
FUNC(sceMbusDebugRemoveCameraAppModuleFocus);
FUNC(sceMbusDebugResumeApplication);
FUNC(sceMbusDebugSetApplicationFocusByAppId);
FUNC(sceMbusDebugSetCameraAppModuleFocus);
FUNC(sceMbusDebugSetControllerFocusByAppId);
FUNC(sceMbusDebugSetOtherProcessExcludedAction);
FUNC(sceMbusDebugSetPriority);
FUNC(sceMbusDebugStartApplication);
FUNC(sceMbusDebugStartApplication2);
FUNC(sceMbusDebugStartApplicationNull);
FUNC(sceMbusDebugSuspendApplication);
FUNC(sceMbusDebugTerminateApplication);
FUNC(sceMbusDebugTerminateProcess);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
