/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceAudiodecCpuClearContext);
FUNC(sceAudiodecCpuDecode);
FUNC(sceAudiodecCpuInitDecoder);
FUNC(sceAudiodecCpuInternalClearContext);
FUNC(sceAudiodecCpuInternalDecode);
FUNC(sceAudiodecCpuInternalInitDecoder);
FUNC(sceAudiodecCpuInternalQueryMemSize);
FUNC(sceAudiodecCpuQueryMemSize);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
