/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceM4aacEncClearContext);
FUNC(sceM4aacEncCreateEncoder);
FUNC(sceM4aacEncDeleteEncoder);
FUNC(sceM4aacEncEncode);
FUNC(sceM4aacEncEncodeWithPriority);
FUNC(sceM4aacEncFlush);
FUNC(sceM4aacEncFlushWithPriority);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
