/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpSnsDailymotionDialogClose);
FUNC(sceNpSnsDailymotionDialogGetResult);
FUNC(sceNpSnsDailymotionDialogGetStatus);
FUNC(sceNpSnsDailymotionDialogInitialize);
FUNC(sceNpSnsDailymotionDialogOpen);
FUNC(sceNpSnsDailymotionDialogTerminate);
FUNC(sceNpSnsDailymotionDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
