/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceOpusSilkEncCreate);
FUNC(sceOpusSilkEncCtl);
FUNC(sceOpusSilkEncDestroy);
FUNC(sceOpusSilkEncEncode);
FUNC(sceOpusSilkEncEncodeCancelForTimeout);
FUNC(sceOpusSilkEncEncodeFloat);
FUNC(sceOpusSilkEncEncodeFloatWithPriority);
FUNC(sceOpusSilkEncEncodeFloatWithPriorityAndTimeout);
FUNC(sceOpusSilkEncEncodeWithPriority);
FUNC(sceOpusSilkEncEncodeWithPriorityAndTimeout);
FUNC(sceOpusSilkEncGetSize);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
