/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceCompanionUtilGetEvent);
FUNC(sceCompanionUtilGetRemoteOskEvent);
FUNC(sceCompanionUtilInitialize);
FUNC(sceCompanionUtilOptParamInitialize);
FUNC(sceCompanionUtilTerminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
