/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(scePlayReadyApiInitializeInitParams);
FUNC(scePlayReadyApiIsStarted);
FUNC(scePlayReadyApiStart);
FUNC(scePlayReadyApiStop);
FUNC(scePlayReadyApiVersion);
FUNC(scePlayReadyApiVersionString);
FUNC(scePlayReadyBufferFree);
FUNC(scePlayReadyBufferInit);
FUNC(scePlayReadyBufferInitWithData);
FUNC(scePlayReadyBufferMalloc);
FUNC(scePlayReadyBufferRealloc);
FUNC(scePlayReadyCloneDecryptContext);
FUNC(scePlayReadyContentGetProperty);
FUNC(scePlayReadyContentSetProperty);
FUNC(scePlayReadyDebugPrintf);
FUNC(scePlayReadyDebugSetLevel);
FUNC(scePlayReadyDomainCertEnumFini);
FUNC(scePlayReadyDomainCertEnumInit);
FUNC(scePlayReadyDomainCertEnumNext);
FUNC(scePlayReadyDomainCertFind);
FUNC(scePlayReadyDomainJoinGenerateChallenge);
FUNC(scePlayReadyDomainJoinProcessResponse);
FUNC(scePlayReadyDomainLeaveGenerateChallenge);
FUNC(scePlayReadyDomainLeaveProcessResponse);
FUNC(scePlayReadyFinalize);
FUNC(scePlayReadyFreeDecryptContext);
FUNC(scePlayReadyInitialize);
FUNC(scePlayReadyInitializeInitParams);
FUNC(scePlayReadyLicenseAcqGenerateAck);
FUNC(scePlayReadyLicenseAcqGenerateChallenge);
FUNC(scePlayReadyLicenseAcqGetAdditionalResponseData);
FUNC(scePlayReadyLicenseAcqProcessAckResponse);
FUNC(scePlayReadyLicenseAcqProcessResponse);
FUNC(scePlayReadyLicenseDelete);
FUNC(scePlayReadyLicenseDeleteInMemory);
FUNC(scePlayReadyLicenseGetExpirationTime);
FUNC(scePlayReadyLicenseGetProperty);
FUNC(scePlayReadyMemAlloc);
FUNC(scePlayReadyMemFree);
FUNC(scePlayReadyMemGetStats);
FUNC(scePlayReadyMemRealloc);
FUNC(scePlayReadyNewDecryptContext);
FUNC(scePlayReadyReaderBind);
FUNC(scePlayReadyReaderClose);
FUNC(scePlayReadyReaderCommit);
FUNC(scePlayReadyReaderDecrypt);
FUNC(scePlayReadyReaderDecrypt_Legacy);
FUNC(scePlayReadyReaderDecryptMultiple);
FUNC(scePlayReadyReaderDecryptMultipleOpaque);
FUNC(scePlayReadyReaderDecryptOpaque);
FUNC(scePlayReadyReaderFreeOpaqueContent);
FUNC(scePlayReadyReaderRetrieveOpaqueContent);
FUNC(scePlayReadyReinitialize);
FUNC(scePlayReadyReset);
FUNC(scePlayReadyStoreCleanup);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
