/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(bemp2sys_logprintf_getlevel);
FUNC(bemp2sys_logprintf_setfunc);
FUNC(bemp2sys_logprintf_setlevel);
FUNC(bemp2sys_memmanager_set);
FUNC(bemp2sys_packetizer_create);
FUNC(bemp2sys_packetizer_destroy);
FUNC(bemp2sys_packetizer_init);
FUNC(bemp2sys_packetizer_release);
FUNC(bemp2sys_pesparser_create);
FUNC(bemp2sys_pesparser_destroy);
FUNC(bemp2sys_pesparser_init);
FUNC(bemp2sys_pesparser_parse);
FUNC(bemp2sys_pesparser_release);
FUNC(bemp2sys_pesparser_sendmessage);
FUNC(bemp2sys_psdecoder_create);
FUNC(bemp2sys_psdecoder_destroy);
FUNC(bemp2sys_psdecoder_init);
FUNC(bemp2sys_psdecoder_readpacket);
FUNC(bemp2sys_psdecoder_release);
FUNC(bemp2sys_psdecoder_sendmessage);
FUNC(bemp2sys_tsdecoder_create);
FUNC(bemp2sys_tsdecoder_destroy);
FUNC(bemp2sys_tsdecoder_init);
FUNC(bemp2sys_tsdecoder_readpacket);
FUNC(bemp2sys_tsdecoder_release);
FUNC(bemp2sys_tsdecoder_sendmessage);
FUNC(bemp2sys_tsfilter_create);
FUNC(bemp2sys_tsfilter_destroy);
FUNC(bemp2sys_tsfilter_init);
FUNC(bemp2sys_tsfilter_release);
FUNC(bemp2sys_tsfilter_sendmessage);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
