/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceImeDialogAbort);
FUNC(sceImeDialogForceClose);
FUNC(sceImeDialogForTestFunction);
FUNC(sceImeDialogGetCurrentStarState);
FUNC(sceImeDialogGetPanelPositionAndForm);
FUNC(sceImeDialogGetPanelSize);
FUNC(sceImeDialogGetPanelSizeExtended);
FUNC(sceImeDialogGetResult);
FUNC(sceImeDialogGetStatus);
FUNC(sceImeDialogInit);
FUNC(sceImeDialogInitInternal);
FUNC(sceImeDialogInitInternal2);
FUNC(sceImeDialogInitInternal3);
FUNC(sceImeDialogSetPanelPosition);
FUNC(sceImeDialogTerm);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
