/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(ft_raster1_renderer_class);
FUNC(ft_raster5_renderer_class);
FUNC(FTC_CMapCache_Lookup);
FUNC(FTC_CMapCache_New);
FUNC(FTC_Image_Cache_Lookup);
FUNC(FTC_Image_Cache_New);
FUNC(FTC_ImageCache_Lookup);
FUNC(FTC_ImageCache_LookupScaler);
FUNC(FTC_ImageCache_New);
FUNC(FTC_Manager_Done);
FUNC(FTC_Manager_Lookup_Face);
FUNC(FTC_Manager_Lookup_Size);
FUNC(FTC_Manager_LookupFace);
FUNC(FTC_Manager_LookupSize);
FUNC(FTC_Manager_New);
FUNC(FTC_Manager_RemoveFaceID);
FUNC(FTC_Manager_Reset);
FUNC(FTC_Node_Unref);
FUNC(FTC_SBit_Cache_Lookup);
FUNC(FTC_SBit_Cache_New);
FUNC(FTC_SBitCache_Lookup);
FUNC(FTC_SBitCache_LookupScaler);
FUNC(FTC_SBitCache_New);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
