/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(_Z5dummyv);
FUNC(sceScreenShotCapture);
FUNC(sceScreenShotDisable);
FUNC(sceScreenShotDisableNotification);
FUNC(sceScreenShotEnable);
FUNC(sceScreenShotEnableNotification);
FUNC(sceScreenShotGetAppInfo);
FUNC(sceScreenShotGetDrcParam);
FUNC(sceScreenShotIsDisabled);
FUNC(sceScreenShotIsVshScreenCaptureDisabled);
FUNC(sceScreenShotSetOverlayImage);
FUNC(sceScreenShotSetOverlayImageWithOrigin);
FUNC(sceScreenShotSetParam);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
