/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSystemServiceActivateHevcSoft);
FUNC(sceSystemServiceActivateHevcSoftAbort);
FUNC(sceSystemServiceActivateHevcSoftGetStatus);
FUNC(sceSystemServiceActivateHevcSoftInit);
FUNC(sceSystemServiceActivateHevcSoftIsActivated);
FUNC(sceSystemServiceActivateHevcSoftStart);
FUNC(sceSystemServiceActivateHevcSoftTerm);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
