/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNetBweCheckCallbackIpcInt);
FUNC(sceNetBweClearEventIpcInt);
FUNC(sceNetBweFinishInternetConnectionTestIpcInt);
FUNC(sceNetBweGetInfoIpcInt);
FUNC(sceNetBweRegisterCallbackIpcInt);
FUNC(sceNetBweSetInternetConnectionTestResultIpcInt);
FUNC(sceNetBweStartInternetConnectionTestBandwidthTestIpcInt);
FUNC(sceNetBweStartInternetConnectionTestIpcInt);
FUNC(sceNetBweUnregisterCallbackIpcInt);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
