/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(_ZN3sce16CommonDialogUtil6Server13setFinishDataEPvm);
FUNC(_ZN3sce16CommonDialogUtil6Server6setRunEPvm);
FUNC(_ZN3sce16CommonDialogUtil6Server9setFinishEv);
FUNC(_ZN3sce16CommonDialogUtil6Server9setResultEi);
FUNC(_ZN3sce16CommonDialogUtil6ServerC2EPKcmmis);
FUNC(_ZN3sce16CommonDialogUtil6ServerD0Ev);
FUNC(_ZN3sce16CommonDialogUtil6ServerD1Ev);
FUNC(_ZN3sce16CommonDialogUtil6ServerD2Ev);
FUNC(_ZNK3sce16CommonDialogUtil6Server10getVersionERj);
FUNC(_ZNK3sce16CommonDialogUtil6Server10isCloseReqEv);
FUNC(_ZNK3sce16CommonDialogUtil6Server14getServerStateEv);
FUNC(_ZTVN3sce16CommonDialogUtil6ServerE);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
