/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceAudioInChangeAppModuleState);
FUNC(sceAudioInClose);
FUNC(sceAudioInCountPorts);
FUNC(sceAudioInDeviceHqOpen);
FUNC(sceAudioInDeviceIdHqOpen);
FUNC(sceAudioInDeviceIdOpen);
FUNC(sceAudioInDeviceOpen);
FUNC(sceAudioInDeviceOpenEx);
FUNC(sceAudioInExtClose);
FUNC(sceAudioInExtCtrl);
FUNC(sceAudioInExtInput);
FUNC(sceAudioInExtOpen);
FUNC(sceAudioInExtSetAecMode);
FUNC(sceAudioInGetGain);
FUNC(sceAudioInGetHandleStatusInfo);
FUNC(sceAudioInGetRerouteCount);
FUNC(sceAudioInGetSilentState);
FUNC(sceAudioInHqOpen);
FUNC(sceAudioInHqOpenEx);
FUNC(sceAudioInInit);
FUNC(sceAudioInInput);
FUNC(sceAudioInInputs);
FUNC(sceAudioInIsSharedDevice);
FUNC(sceAudioInOpen);
FUNC(sceAudioInOpenEx);
FUNC(sceAudioInSetAllMute);
FUNC(sceAudioInSetCompressorPreGain);
FUNC(sceAudioInSetConnections);
FUNC(sceAudioInSetConnectionsForUser);
FUNC(sceAudioInSetDevConnection);
FUNC(sceAudioInSetFocusForUser);
FUNC(sceAudioInSetMode);
FUNC(sceAudioInSetMode2);
FUNC(sceAudioInSetPortConnections);
FUNC(sceAudioInSetPortStatuses);
FUNC(sceAudioInSetSparkParam);
FUNC(sceAudioInSetSparkSideTone);
FUNC(sceAudioInSetUsbGain);
FUNC(sceAudioInSetUserMute);
FUNC(sceAudioInVmicCreate);
FUNC(sceAudioInVmicDestroy);
FUNC(sceAudioInVmicWrite);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
