/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceMsgDialogClose);
FUNC(sceMsgDialogGetResult);
FUNC(sceMsgDialogGetStatus);
FUNC(sceMsgDialogInitialize);
FUNC(sceMsgDialogOpen);
FUNC(sceMsgDialogProgressBarInc);
FUNC(sceMsgDialogProgressBarSetMsg);
FUNC(sceMsgDialogProgressBarSetValue);
FUNC(sceMsgDialogTerminate);
FUNC(sceMsgDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
