/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSystemGestureAppendTouchRecognizer);
FUNC(sceSystemGestureClose);
FUNC(sceSystemGestureCreateTouchRecognizer);
FUNC(sceSystemGestureDebugGetVersion);
FUNC(sceSystemGestureFinalizePrimitiveTouchRecognizer);
FUNC(sceSystemGestureGetPrimitiveTouchEventByIndex);
FUNC(sceSystemGestureGetPrimitiveTouchEventByPrimitiveID);
FUNC(sceSystemGestureGetPrimitiveTouchEvents);
FUNC(sceSystemGestureGetPrimitiveTouchEventsCount);
FUNC(sceSystemGestureGetTouchEventByEventID);
FUNC(sceSystemGestureGetTouchEventByIndex);
FUNC(sceSystemGestureGetTouchEvents);
FUNC(sceSystemGestureGetTouchEventsCount);
FUNC(sceSystemGestureGetTouchRecognizerInformation);
FUNC(sceSystemGestureInitializePrimitiveTouchRecognizer);
FUNC(sceSystemGestureOpen);
FUNC(sceSystemGestureRemoveTouchRecognizer);
FUNC(sceSystemGestureResetPrimitiveTouchRecognizer);
FUNC(sceSystemGestureResetTouchRecognizer);
FUNC(sceSystemGestureUpdateAllTouchRecognizer);
FUNC(sceSystemGestureUpdatePrimitiveTouchRecognizer);
FUNC(sceSystemGestureUpdateTouchRecognizer);
FUNC(sceSystemGestureUpdateTouchRecognizerRectangle);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
