/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceUsbStorageGetDeviceInfo);
FUNC(sceUsbStorageGetDeviceList);
FUNC(sceUsbStorageInit);
FUNC(sceUsbStorageIsExist);
FUNC(sceUsbStorageRegisterCallback);
FUNC(sceUsbStorageRegisterCallbackForMapAvailable);
FUNC(sceUsbStorageRequestMap);
FUNC(sceUsbStorageRequestUnmap);
FUNC(sceUsbStorageTerm);
FUNC(sceUsbStorageUnregisterCallback);
FUNC(sceUsbStorageUnregisterCallbackForMapAvailable);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
