/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceIduUtilClearAllSchedules);
FUNC(sceIduUtilDeleteSaveData);
FUNC(sceIduUtilDisablePriorityDownloads);
FUNC(sceIduUtilDownloadInstallPkg);
FUNC(sceIduUtilEnablePriorityDownloads);
FUNC(sceIduUtilGetAppVersion);
FUNC(sceIduUtilGetBgftProgress);
FUNC(sceIduUtilGetCompilationDiscInfo);
FUNC(sceIduUtilGetCompilationDiscTitleInfo);
FUNC(sceIduUtilGetDiscInfo);
FUNC(sceIduUtilGetDiskSpaceStats);
FUNC(sceIduUtilGetDownloadInstallProgress);
FUNC(sceIduUtilGetDownloadState);
FUNC(sceIduUtilGetEnvironment);
FUNC(sceIduUtilGetInstalledApp);
FUNC(sceIduUtilGetInstalledAppWithOffset);
FUNC(sceIduUtilGetMasterVersion);
FUNC(sceIduUtilGetNumInstalledApps);
FUNC(sceIduUtilGetNumSchedules);
FUNC(sceIduUtilGetOpenPsId);
FUNC(sceIduUtilGetSchedule);
FUNC(sceIduUtilGetSettingBin);
FUNC(sceIduUtilGetSettingInt);
FUNC(sceIduUtilGetSettingStr);
FUNC(sceIduUtilHideOverlay);
FUNC(sceIduUtilInitialize);
FUNC(sceIduUtilIsAppInstalled);
FUNC(sceIduUtilIsDiscCompilationDisc);
FUNC(sceIduUtilIsDiscInserted);
FUNC(sceIduUtilIsInitialised);
FUNC(sceIduUtilIsRifInstalled);
FUNC(sceIduUtilIsStaffMode);
FUNC(sceIduUtilLaunchTitle);
FUNC(sceIduUtilLaunchTitleV2);
FUNC(sceIduUtilPauseAllDownloads);
FUNC(sceIduUtilReboot);
FUNC(sceIduUtilRegisterFlag);
FUNC(sceIduUtilRegisterOverlayMsg);
FUNC(sceIduUtilResumeAllDownloads);
FUNC(sceIduUtilSetMoveMode);
FUNC(sceIduUtilSetPupVersion);
FUNC(sceIduUtilSetSchedule);
FUNC(sceIduUtilSetSettingBin);
FUNC(sceIduUtilSetSettingInt);
FUNC(sceIduUtilSetSettingStr);
FUNC(sceIduUtilSetSysLanguage);
FUNC(sceIduUtilShowOverlay);
FUNC(sceIduUtilTerminate);
FUNC(sceIduUtilUninstallApp);
FUNC(sceIduUtilUpdateSelf);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
