/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpSessionSignalingActivateSession);
FUNC(sceNpSessionSignalingActivateUser);
FUNC(sceNpSessionSignalingCreateContext);
FUNC(sceNpSessionSignalingCreateContext2);
FUNC(sceNpSessionSignalingCreateJoinActivate);
FUNC(sceNpSessionSignalingDeactivate);
FUNC(sceNpSessionSignalingDestroyContext);
FUNC(sceNpSessionSignalingGetConnectionFromNetAddress);
FUNC(sceNpSessionSignalingGetConnectionFromNetAddress2);
FUNC(sceNpSessionSignalingGetConnectionFromPeerAddress);
FUNC(sceNpSessionSignalingGetConnectionFromPeerAddress2);
FUNC(sceNpSessionSignalingGetConnectionInfo);
FUNC(sceNpSessionSignalingGetConnectionStatistics);
FUNC(sceNpSessionSignalingGetConnectionStatus);
FUNC(sceNpSessionSignalingGetCustomProperty);
FUNC(sceNpSessionSignalingGetGroupFromPeerAddress);
FUNC(sceNpSessionSignalingGetGroupFromSessionId);
FUNC(sceNpSessionSignalingGetGroupInfo);
FUNC(sceNpSessionSignalingGetLocalNetInfo);
FUNC(sceNpSessionSignalingGetMemoryInfo);
FUNC(sceNpSessionSignalingInitialize);
FUNC(sceNpSessionSignalingInitializeWithPort);
FUNC(sceNpSessionSignalingJoinActivate);
FUNC(sceNpSessionSignalingManualUdpAbortConnection);
FUNC(sceNpSessionSignalingManualUdpCreateJoin);
FUNC(sceNpSessionSignalingManualUdpEstablishConnection);
FUNC(sceNpSessionSignalingManualUdpJoin);
FUNC(sceNpSessionSignalingRequestPrepare);
FUNC(sceNpSessionSignalingSetCustomProperty);
FUNC(sceNpSessionSignalingTerminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
