/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceClAudiodecCreateDecoder);
FUNC(sceClAudiodecDecode);
FUNC(sceClAudiodecDeleteDecoder);
FUNC(sceClAudiodecInitLibrary);
FUNC(sceClAudiodecTermLibrary);
FUNC(sceClHttpAbortRequest);
FUNC(sceClHttpAddRequestHeader);
FUNC(sceClHttpCreateConnectionWithURL);
FUNC(sceClHttpCreateEpoll);
FUNC(sceClHttpCreateRequestWithURL);
FUNC(sceClHttpCreateTemplate);
FUNC(sceClHttpDeleteConnection);
FUNC(sceClHttpDeleteRequest);
FUNC(sceClHttpDeleteTemplate);
FUNC(sceClHttpDestroyEpoll);
FUNC(sceClHttpGetMemoryPoolStats);
FUNC(sceClHttpInit);
FUNC(sceClHttpReadData);
FUNC(sceClHttpSendRequest);
FUNC(sceClHttpSetAutoRedirect);
FUNC(sceClHttpSetEpoll);
FUNC(sceClHttpSetNonblock);
FUNC(sceClHttpSetRedirectCallback);
FUNC(sceClHttpsSetSslCallback);
FUNC(sceClHttpTerm);
FUNC(sceClHttpUnsetEpoll);
FUNC(sceClHttpWaitRequest);
FUNC(sceClKernelCreateEventFlag);
FUNC(sceClKernelDeleteEventFlag);
FUNC(sceClKernelMapNamedFlexibleMemory);
FUNC(sceClKernelMunmap);
FUNC(sceClKernelNanosleep);
FUNC(sceClKernelReleaseFlexibleMemory);
FUNC(sceClKernelSetEventFlag);
FUNC(sceClKernelUsleep);
FUNC(sceClKernelWaitEventFlag);
FUNC(sceClNetInit);
FUNC(sceClNetPoolCreate);
FUNC(sceClNetPoolDestroy);
FUNC(sceClNetTerm);
FUNC(sceClPthreadAttrDestroy);
FUNC(sceClPthreadAttrInit);
FUNC(sceClPthreadAttrSetdetachstate);
FUNC(sceClPthreadAttrSetinheritsched);
FUNC(sceClPthreadAttrSetschedparam);
FUNC(sceClPthreadAttrSetstacksize);
FUNC(sceClPthreadCondattrDestroy);
FUNC(sceClPthreadCondattrInit);
FUNC(sceClPthreadCondDestroy);
FUNC(sceClPthreadCondInit);
FUNC(sceClPthreadCondSignal);
FUNC(sceClPthreadCondWait);
FUNC(sceClPthreadCreate);
FUNC(sceClPthreadDetach);
FUNC(sceClPthreadExit);
FUNC(sceClPthreadJoin);
FUNC(sceClPthreadMutexattrDestroy);
FUNC(sceClPthreadMutexattrInit);
FUNC(sceClPthreadMutexattrSetprioceiling);
FUNC(sceClPthreadMutexattrSetprotocol);
FUNC(sceClPthreadMutexattrSettype);
FUNC(sceClPthreadMutexDestroy);
FUNC(sceClPthreadMutexInit);
FUNC(sceClPthreadMutexLock);
FUNC(sceClPthreadMutexUnlock);
FUNC(sceClPthreadSetprio);
FUNC(sceClSendSystemNotification);
FUNC(sceClSslGetSerialNumber);
FUNC(sceClSslInit);
FUNC(sceClSslTerm);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
