/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceMoveClose);
FUNC(sceMoveGetBluetoothAddress);
FUNC(sceMoveGetCalibrationInfo);
FUNC(sceMoveGetDeviceId);
FUNC(sceMoveGetDeviceInfo);
FUNC(sceMoveGetExtensionPortInfo);
FUNC(sceMoveInit);
FUNC(sceMoveIsReproductionModel);
FUNC(sceMoveIsValidHandle);
FUNC(sceMoveOpen);
FUNC(sceMoveReadStateLatest);
FUNC(sceMoveReadStateRecent);
FUNC(sceMoveReadStateRecentForTracker);
FUNC(sceMoveResetLightSphere);
FUNC(sceMoveSetCalibrationMode);
FUNC(sceMoveSetExtensionPortOutput);
FUNC(sceMoveSetLightSphere);
FUNC(sceMoveSetLightSphereForTracker);
FUNC(sceMoveSetVibration);
FUNC(sceMoveTerm);
FUNC(sceMoveWriteCalibrationInfo);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
