/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceRazorCpuBeginLogicalFileAccess);
FUNC(sceRazorCpuDisableFiberUserMarkers);
FUNC(sceRazorCpuEndLogicalFileAccess);
FUNC(sceRazorCpuFiberLogNameChange);
FUNC(sceRazorCpuFiberSwitch);
FUNC(sceRazorCpuFlushOccurred);
FUNC(sceRazorCpuGetDataTagStorageSize);
FUNC(sceRazorCpuGpuMarkerSync);
FUNC(sceRazorCpuInitDataTags);
FUNC(sceRazorCpuInitializeGpuMarkerContext);
FUNC(sceRazorCpuInitializeInternal);
FUNC(sceRazorCpuIsCapturing);
FUNC(sceRazorCpuJobManagerDispatch);
FUNC(sceRazorCpuJobManagerJob);
FUNC(sceRazorCpuJobManagerSequence);
FUNC(sceRazorCpuNamedSync);
FUNC(sceRazorCpuPlotValue);
FUNC(sceRazorCpuPopMarker);
FUNC(sceRazorCpuPushMarker);
FUNC(sceRazorCpuPushMarkerStatic);
FUNC(sceRazorCpuResizeTaggedBuffer);
FUNC(sceRazorCpuSetPopMarkerCallback);
FUNC(sceRazorCpuSetPushMarkerCallback);
FUNC(sceRazorCpuSetPushMarkerStaticCallback);
FUNC(sceRazorCpuShutdownDataTags);
FUNC(sceRazorCpuStartCaptureInternal);
FUNC(sceRazorCpuStopCaptureInternal);
FUNC(sceRazorCpuSync);
FUNC(sceRazorCpuTagArray);
FUNC(sceRazorCpuTagBuffer);
FUNC(sceRazorCpuUnTagBuffer);
FUNC(sceRazorCpuWorkloadRunBegin);
FUNC(sceRazorCpuWorkloadRunEnd);
FUNC(sceRazorCpuWorkloadSubmit);
FUNC(sceRazorCpuWriteBookmark);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
