/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceRnpsAppMgrBlockAppInstall);
FUNC(sceRnpsAppMgrCreateUpdateRequest);
FUNC(sceRnpsAppMgrCreateUrlRequest);
FUNC(sceRnpsAppMgrDestroyUpdateRequest);
FUNC(sceRnpsAppMgrFinishUrlRequest);
FUNC(sceRnpsAppMgrGetAppInfo);
FUNC(sceRnpsAppMgrGetAppInfoDebugString);
FUNC(sceRnpsAppMgrGetAppInfoList);
FUNC(sceRnpsAppMgrGetEventForShellUI);
FUNC(sceRnpsAppMgrGetUpdateProgress);
FUNC(sceRnpsAppMgrHasEventForShellUI);
FUNC(sceRnpsAppMgrInitialize);
FUNC(sceRnpsAppMgrPushEventForShellUI);
FUNC(sceRnpsAppMgrRecoverUfsImage);
FUNC(sceRnpsAppMgrRegisterShellUI);
FUNC(sceRnpsAppMgrRemoveApp);
FUNC(sceRnpsAppMgrRemoveAppOnSystemShutdown);
FUNC(sceRnpsAppMgrRemoveUfsImageOnSystemShutdown);
FUNC(sceRnpsAppMgrRequestUpdateCheck);
FUNC(sceRnpsAppMgrSetCrlUrl);
FUNC(sceRnpsAppMgrSetUpdateUrl);
FUNC(sceRnpsAppMgrStartService);
FUNC(sceRnpsAppMgrTerminate);
FUNC(sceRnpsAppMgrUnblockAppInstall);
FUNC(sceRnpsAppMgrUnregisterShellUI);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
