/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(_sceDepthCalcHeteroAdjustParam);
FUNC(_sceDepthHeadCandidateTrackerGetInformation);
FUNC(_sceDepthHeadCandidateTrackerSetInformation);
FUNC(_sceDepthSetCameraFactoryCalibrationData);
FUNC(_sceDepthSetHeteroAdjustParam);
FUNC(_sceDepthSetHeteroMode);
FUNC(sceDepthCalculateRectificationInformation);
FUNC(sceDepthDisableHeteroMode);
FUNC(sceDepthEnableExtendedMode);
FUNC(sceDepthEnableHeteroMode);
FUNC(sceDepthEnableHeteroModeAndGenerateInformation);
FUNC(sceDepthGetCalibrationData);
FUNC(sceDepthGetImage);
FUNC(sceDepthGetRectificationInformation);
FUNC(sceDepthGetSrParameter);
FUNC(sceDepthHandCandidateTrackerGetResult);
FUNC(sceDepthHasCalibrationData);
FUNC(sceDepthHeadCandidateDetectorGetResults);
FUNC(sceDepthHeadCandidateTrackerGetResult);
FUNC(sceDepthHeadCandidateTrackerSetValidationInformation);
FUNC(sceDepthInitialize);
FUNC(sceDepthLoadCalibrationData);
FUNC(sceDepthQueryMemory);
FUNC(sceDepthSaveInternalBuffers);
FUNC(sceDepthSetCalibrationData);
FUNC(sceDepthSetCommands);
FUNC(sceDepthSetPostFilterParameter);
FUNC(sceDepthSetPreFilterParameter);
FUNC(sceDepthSetRectificationInformation);
FUNC(sceDepthSetRoi);
FUNC(sceDepthSetRoiset);
FUNC(sceDepthSetSrParameter);
FUNC(sceDepthSetSrTnrParameter);
FUNC(sceDepthSubmit);
FUNC(sceDepthTerminate);
FUNC(sceDepthUpdate);
FUNC(sceDepthValidateCurrentCalibrationData);
FUNC(sceDepthWaitAndExecutePostProcess);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
