/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceMouseClose);
FUNC(sceMouseConnectPort);
FUNC(sceMouseDebugGetDeviceId);
FUNC(sceMouseDeviceOpen);
FUNC(sceMouseDisconnectDevice);
FUNC(sceMouseDisconnectPort);
FUNC(sceMouseGetDeviceInfo);
FUNC(sceMouseInit);
FUNC(sceMouseMbusInit);
FUNC(sceMouseOpen);
FUNC(sceMouseRead);
FUNC(sceMouseSetHandType);
FUNC(sceMouseSetPointerSpeed);
FUNC(sceMouseSetProcessPrivilege);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
