/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceVdecswAllocateComputeQueue);
FUNC(sceVdecswCreateDecoder);
FUNC(sceVdecswDeleteDecoder);
FUNC(sceVdecswFinalizeDecodeSequence);
FUNC(sceVdecswGetAvcPictureInfo);
FUNC(sceVdecswGetHevcPictureInfo);
FUNC(sceVdecswGetPictureInfo);
FUNC(sceVdecswQueryComputeMemoryInfo);
FUNC(sceVdecswQueryDecoderMemoryInfo);
FUNC(sceVdecswReleaseComputeQueue);
FUNC(sceVdecswResetDecoder);
FUNC(sceVdecswSetDecodeInput);
FUNC(sceVdecswSetDecodeOutput);
FUNC(sceVdecswSyncDecodeInput);
FUNC(sceVdecswSyncDecodeOutput);
FUNC(sceVdecswTrySyncDecodeInput);
FUNC(sceVdecswTrySyncDecodeOutput);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
