/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSystemServiceAcquireFb0);
FUNC(sceSystemServiceAddLocalProcess);
FUNC(sceSystemServiceAddLocalProcessForPsmKit);
FUNC(sceSystemServiceChangeAcpClock);
FUNC(sceSystemServiceChangeCpuClock);
FUNC(sceSystemServiceChangeGpuClock);
FUNC(sceSystemServiceChangeMemoryClock);
FUNC(sceSystemServiceChangeMemoryClockToBaseMode);
FUNC(sceSystemServiceChangeMemoryClockToDefault);
FUNC(sceSystemServiceChangeMemoryClockToMultiMediaMode);
FUNC(sceSystemServiceChangeNumberOfGpuCu);
FUNC(sceSystemServiceChangeSamuClock);
FUNC(sceSystemServiceChangeUvdClock);
FUNC(sceSystemServiceChangeVceClock);
FUNC(sceSystemServiceDisableMusicPlayer);
FUNC(sceSystemServiceDisablePersonalEyeToEyeDistanceSetting);
FUNC(sceSystemServiceDisableSuspendConfirmationDialog);
FUNC(sceSystemServiceEnablePersonalEyeToEyeDistanceSetting);
FUNC(sceSystemServiceEnableSuspendConfirmationDialog);
FUNC(sceSystemServiceGetAppFocusedAppStatus);
FUNC(sceSystemServiceGetAppIdOfBigApp);
FUNC(sceSystemServiceGetAppIdOfMiniApp);
FUNC(sceSystemServiceGetAppStatus);
FUNC(sceSystemServiceGetAppType);
FUNC(sceSystemServiceGetDisplaySafeAreaInfo);
FUNC(sceSystemServiceGetEventForDaemon);
FUNC(sceSystemServiceGetGpuLoadEmulationMode);
FUNC(sceSystemServiceGetHdrToneMapLuminance);
FUNC(sceSystemServiceGetLocalProcessStatusList);
FUNC(sceSystemServiceGetParentSocket);
FUNC(sceSystemServiceGetParentSocketForPsmKit);
FUNC(sceSystemServiceGetPSButtonEvent);
FUNC(sceSystemServiceGetRenderingMode);
FUNC(sceSystemServiceGetStatus);
FUNC(sceSystemServiceGetTitleWorkaroundInfo);
FUNC(sceSystemServiceGetVersionNumberOfCameraCalibrationData);
FUNC(sceSystemServiceHideSplashScreen);
FUNC(sceSystemServiceIsAppSuspended);
FUNC(sceSystemServiceIsBgmPlaying);
FUNC(sceSystemServiceIsEyeToEyeDistanceAdjusted);
FUNC(sceSystemServiceIsScreenSaverOn);
FUNC(sceSystemServiceIsShellUiFgAndGameBgCpuMode);
FUNC(sceSystemServiceKillApp);
FUNC(sceSystemServiceKillLocalProcess);
FUNC(sceSystemServiceKillLocalProcessForPsmKit);
FUNC(sceSystemServiceLaunchApp);
FUNC(sceSystemServiceLaunchEventDetails);
FUNC(sceSystemServiceLaunchTournamentList);
FUNC(sceSystemServiceLaunchTournamentsTeamProfile);
FUNC(sceSystemServiceLaunchWebBrowser);
FUNC(sceSystemServiceLoadExec);
FUNC(sceSystemServiceNavigateToAnotherApp);
FUNC(sceSystemServiceNavigateToGoBack);
FUNC(sceSystemServiceNavigateToGoBackWithValue);
FUNC(sceSystemServiceNavigateToGoHome);
FUNC(sceSystemServiceParamGetInt);
FUNC(sceSystemServiceParamGetString);
FUNC(sceSystemServicePowerTick);
FUNC(sceSystemServiceRaiseExceptionLocalProcess);
FUNC(sceSystemServiceReceiveEvent);
FUNC(sceSystemServiceReenableMusicPlayer);
FUNC(sceSystemServiceRegisterDaemon);
FUNC(sceSystemServiceReleaseFb0);
FUNC(sceSystemServiceReportAbnormalTermination);
FUNC(sceSystemServiceRequestCameraCalibration);
FUNC(sceSystemServiceRequestToChangeRenderingMode);
FUNC(sceSystemServiceResumeLocalProcess);
FUNC(sceSystemServiceSetControllerFocusPermission);
FUNC(sceSystemServiceSetGpuLoadEmulationMode);
FUNC(sceSystemServiceSetOutOfVrPlayAreaFlag);
FUNC(sceSystemServiceSetOutOfVrPlayZoneWarning);
FUNC(sceSystemServiceShowControllerSettings);
FUNC(sceSystemServiceShowDisplaySafeAreaSettings);
FUNC(sceSystemServiceShowEyeToEyeDistanceSetting);
FUNC(sceSystemServiceSuspendBackgroundApp);
FUNC(sceSystemServiceSuspendLocalProcess);
FUNC(sceSystemServiceTickVideoPlayback);
FUNC(sceSystemServiceTurnOffScreenSaver);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
