/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceLncUtilAcquireCpuBudgetOfExtraAudioDevices);
FUNC(sceLncUtilAcquireCpuBudgetOfImeForBigApp);
FUNC(sceLncUtilAcquireCpuBudgetOfInGameStore);
FUNC(sceLncUtilActivateCdlg);
FUNC(sceLncUtilAddLocalProcess);
FUNC(sceLncUtilBlockAppSuspend);
FUNC(sceLncUtilBlockingGetEventForDaemon);
FUNC(sceLncUtilContinueApp);
FUNC(sceLncUtilCrashSyscore);
FUNC(sceLncUtilDeactivateCdlg);
FUNC(sceLncUtilDeclareReadyForSuspend);
FUNC(sceLncUtilDisableSuspendNotification);
FUNC(sceLncUtilEnableSuspendNotification);
FUNC(sceLncUtilFinishSpecialResume);
FUNC(sceLncUtilForceKillApp);
FUNC(sceLncUtilForceKillLocalProcess);
FUNC(sceLncUtilGetApp0DirPath);
FUNC(sceLncUtilGetAppCategory);
FUNC(sceLncUtilGetAppFocusedAppStatus);
FUNC(sceLncUtilGetAppId);
FUNC(sceLncUtilGetAppIdOfBigApp);
FUNC(sceLncUtilGetAppIdOfMiniApp);
FUNC(sceLncUtilGetAppLaunchedUser);
FUNC(sceLncUtilGetAppStatus);
FUNC(sceLncUtilGetAppStatusListForShellUIReboot);
FUNC(sceLncUtilGetAppTitleId);
FUNC(sceLncUtilGetAppType);
FUNC(sceLncUtilGetCdlgExec);
FUNC(sceLncUtilGetCoredumpState);
FUNC(sceLncUtilGetDbgExecutablePath);
FUNC(sceLncUtilGetEventForDaemon);
FUNC(sceLncUtilGetEventForShellUI);
FUNC(sceLncUtilGetGpuCrashFullDumpAppStatus);
FUNC(sceLncUtilGetLocalProcessStatusList);
FUNC(sceLncUtilGetParentSocket);
FUNC(sceLncUtilGetResultKillApp);
FUNC(sceLncUtilGetResultLaunchAppByTitleId);
FUNC(sceLncUtilInitialize);
FUNC(sceLncUtilIsActiveCdlg);
FUNC(sceLncUtilIsAppLaunched);
FUNC(sceLncUtilIsAppSuspended);
FUNC(sceLncUtilIsCpuBudgetOfExtraAudioDevicesAvailable);
FUNC(sceLncUtilIsPs2Emu);
FUNC(sceLncUtilIsShellUiFgAndGameBgCpuMode);
FUNC(sceLncUtilKickCoredumpOnlyProcMem);
FUNC(sceLncUtilKillApp);
FUNC(sceLncUtilKillAppWithReason);
FUNC(sceLncUtilKillLocalProcess);
FUNC(sceLncUtilLaunchApp);
FUNC(sceLncUtilLoadExec);
FUNC(sceLncUtilNotifyCoredumpRequestEnd);
FUNC(sceLncUtilNotifyCoredumpRequestProgress);
FUNC(sceLncUtilNotifyVshReady);
FUNC(sceLncUtilRaiseException);
FUNC(sceLncUtilRaiseExceptionLocalProcess);
FUNC(sceLncUtilRegisterCdlgSharedMemoryName);
FUNC(sceLncUtilRegisterDaemon);
FUNC(sceLncUtilRegisterShellUI);
FUNC(sceLncUtilReleaseCpuBudgetOfExtraAudioDevices);
FUNC(sceLncUtilReleaseCpuBudgetOfImeForBigApp);
FUNC(sceLncUtilReleaseCpuBudgetOfInGameStore);
FUNC(sceLncUtilResumeApp);
FUNC(sceLncUtilResumeLocalProcess);
FUNC(sceLncUtilSetAppFocus);
FUNC(sceLncUtilSetCdlgExec);
FUNC(sceLncUtilSetControllerFocus);
FUNC(sceLncUtilSetControllerFocusPermission);
FUNC(sceLncUtilStartKillApp);
FUNC(sceLncUtilStartLaunchAppByTitleId);
FUNC(sceLncUtilSuspendApp);
FUNC(sceLncUtilSuspendBackgroundApp);
FUNC(sceLncUtilSuspendLocalProcess);
FUNC(sceLncUtilSystemSuspend);
FUNC(sceLncUtilTerminate);
FUNC(sceLncUtilTryBlockAppSuspend);
FUNC(sceLncUtilUnblockAppSuspend);
FUNC(sceLncUtilUnregisterCdlgSharedMemoryName);
FUNC(sceLncUtilUnregisterDaemon);
FUNC(sceLncUtilUnregisterShellUI);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
