/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceAppInstUtilAppAllowDownloadInstall);
FUNC(sceAppInstUtilAppCancelableUnInstall);
FUNC(sceAppInstUtilAppCancelableUnInstallByUser);
FUNC(sceAppInstUtilAppCancelGetAllAppSize);
FUNC(sceAppInstUtilAppCancelGetAppOtherSize);
FUNC(sceAppInstUtilAppCancelMoveApps);
FUNC(sceAppInstUtilAppCancelUnInstall);
FUNC(sceAppInstUtilAppConvertAppDiscToDownload);
FUNC(sceAppInstUtilAppConvertAppDownloadToDisc);
FUNC(sceAppInstUtilAppDestroyMetadata);
FUNC(sceAppInstUtilAppDestroyPkg);
FUNC(sceAppInstUtilAppExists);
FUNC(sceAppInstUtilAppGetAddcontInfo);
FUNC(sceAppInstUtilAppGetAddcontInfoByContentId);
FUNC(sceAppInstUtilAppGetAddcontListTotalSize);
FUNC(sceAppInstUtilAppGetAddcontNum);
FUNC(sceAppInstUtilAppGetAllAppSize);
FUNC(sceAppInstUtilAppGetAppInstallStatus);
FUNC(sceAppInstUtilAppGetAppInstallStatusByAppInfo);
FUNC(sceAppInstUtilAppGetAppOtherSize);
FUNC(sceAppInstUtilAppGetCompilationDiscInfo);
FUNC(sceAppInstUtilAppGetCustomThemeInfo);
FUNC(sceAppInstUtilAppGetInsertedDiscMasterDataId);
FUNC(sceAppInstUtilAppGetInsertedDiscTitleId);
FUNC(sceAppInstUtilAppGetInsertedDiscTitleIdList);
FUNC(sceAppInstUtilAppGetInstallAddcontFromDiscStatus);
FUNC(sceAppInstUtilAppGetIrremovableAppList);
FUNC(sceAppInstUtilAppGetMoveErrorAppList);
FUNC(sceAppInstUtilAppGetNoRelatedAddcontTitleList);
FUNC(sceAppInstUtilAppGetSize);
FUNC(sceAppInstUtilAppGetStoreCompilationDiscInfo);
FUNC(sceAppInstUtilAppInstallAll);
FUNC(sceAppInstUtilAppInstallCloudGame);
FUNC(sceAppInstUtilAppInstallGetLinkState);
FUNC(sceAppInstUtilAppInstallMediaPlayer);
FUNC(sceAppInstUtilAppInstallPkg);
FUNC(sceAppInstUtilAppInstallPs4CloudGame);
FUNC(sceAppInstUtilAppInstallRequestAddcontFromDisc);
FUNC(sceAppInstUtilAppInstallRequestCompilationDiscApp);
FUNC(sceAppInstUtilAppInstallSharePlayLink);
FUNC(sceAppInstUtilAppInstallSharePlayLinkByUser);
FUNC(sceAppInstUtilAppInstallTitleDir);
FUNC(sceAppInstUtilAppIsInInstalling);
FUNC(sceAppInstUtilAppIsInUpdating);
FUNC(sceAppInstUtilAppPrepareOverwritePkg);
FUNC(sceAppInstUtilAppProhibitDownloadInstall);
FUNC(sceAppInstUtilAppRecoverApp);
FUNC(sceAppInstUtilAppRequestMoveApps);
FUNC(sceAppInstUtilAppSetRemasterInstallType);
FUNC(sceAppInstUtilAppSetSavedataUploadStatus);
FUNC(sceAppInstUtilAppStoreCompilationDiscInfo);
FUNC(sceAppInstUtilAppUnInstall);
FUNC(sceAppInstUtilAppUnInstallAddcont);
FUNC(sceAppInstUtilAppUnInstallByUser);
FUNC(sceAppInstUtilAppUnInstallForMultiInstall);
FUNC(sceAppInstUtilAppUnInstallPat);
FUNC(sceAppInstUtilAppUnInstallTheme);
FUNC(sceAppInstUtilAppUnInstallTypes);
FUNC(sceAppInstUtilAppUpdateStartTime);
FUNC(sceAppInstUtilCancelDataDiscCopy);
FUNC(sceAppInstUtilCheckAppSystemVer);
FUNC(sceAppInstUtilDeleteExternalPs5All);
FUNC(sceAppInstUtilGetAddcontInstalledStatus);
FUNC(sceAppInstUtilGetAppEmptySlot);
FUNC(sceAppInstUtilGetAppMoveProgressInfo);
FUNC(sceAppInstUtilGetAppSlotInfoList);
FUNC(sceAppInstUtilGetDataDiscCopyProgress);
FUNC(sceAppInstUtilGetExternalPs5AllSize);
FUNC(sceAppInstUtilGetInsertedDiscRoleType);
FUNC(sceAppInstUtilGetInsertedDiscTotal);
FUNC(sceAppInstUtilGetInstallProgress);
FUNC(sceAppInstUtilGetInstallProgressInfo);
FUNC(sceAppInstUtilGetInstallProgressInfoForMultiDisc);
FUNC(sceAppInstUtilGetMainAppTitleIdForSP);
FUNC(sceAppInstUtilGetPrimaryAppSlot);
FUNC(sceAppInstUtilGetSubAppTitleIdForSP);
FUNC(sceAppInstUtilGetTitleIdFromPkg);
FUNC(sceAppInstUtilInitialize);
FUNC(sceAppInstUtilJson);
FUNC(sceAppInstUtilMountBdEmu);
FUNC(sceAppInstUtilRequestDataDiscCopy);
FUNC(sceAppInstUtilRequestInstallDiscGame);
FUNC(sceAppInstUtilSetPrimaryAppSlot);
FUNC(sceAppInstUtilTerminate);
FUNC(sceAppInstUtilUnmountBdEmu);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
