/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(_sceUltConditionVariableCreate);
FUNC(_sceUltConditionVariableOptParamInitialize);
FUNC(_sceUltMutexCreate);
FUNC(_sceUltMutexOptParamInitialize);
FUNC(_sceUltQueueCreate);
FUNC(_sceUltQueueDataResourcePoolCreate);
FUNC(_sceUltQueueDataResourcePoolOptParamInitialize);
FUNC(_sceUltQueueOptParamInitialize);
FUNC(_sceUltReaderWriterLockCreate);
FUNC(_sceUltReaderWriterLockOptParamInitialize);
FUNC(_sceUltSemaphoreCreate);
FUNC(_sceUltSemaphoreOptParamInitialize);
FUNC(_sceUltUlthreadCreate);
FUNC(_sceUltUlthreadOptParamInitialize);
FUNC(_sceUltUlthreadRuntimeCreate);
FUNC(_sceUltUlthreadRuntimeOptParamInitialize);
FUNC(_sceUltWaitingQueueResourcePoolCreate);
FUNC(_sceUltWaitingQueueResourcePoolOptParamInitialize);
FUNC(sceUltConditionVariableDestroy);
FUNC(sceUltConditionVariableSignal);
FUNC(sceUltConditionVariableSignalAll);
FUNC(sceUltConditionVariableWait);
FUNC(sceUltFinalize);
FUNC(sceUltGetConditionVariableInfo);
FUNC(sceUltGetMutexInfo);
FUNC(sceUltGetQueueDataResourcePoolInfo);
FUNC(sceUltGetQueueInfo);
FUNC(sceUltGetReaderWriterLockInfo);
FUNC(sceUltGetSemaphoreInfo);
FUNC(sceUltGetUlthreadInfo);
FUNC(sceUltGetUlthreadRuntimeInfo);
FUNC(sceUltGetWaitingQueueResourcePoolInfo);
FUNC(sceUltInitialize);
FUNC(sceUltMutexDestroy);
FUNC(sceUltMutexLock);
FUNC(sceUltMutexTryLock);
FUNC(sceUltMutexUnlock);
FUNC(sceUltQueueDataResourcePoolDestroy);
FUNC(sceUltQueueDataResourcePoolGetWorkAreaSize);
FUNC(sceUltQueueDestroy);
FUNC(sceUltQueuePop);
FUNC(sceUltQueuePush);
FUNC(sceUltQueueTryPop);
FUNC(sceUltQueueTryPush);
FUNC(sceUltReaderWriterLockDestroy);
FUNC(sceUltReaderWriterLockLockRead);
FUNC(sceUltReaderWriterLockLockWrite);
FUNC(sceUltReaderWriterLockTryLockRead);
FUNC(sceUltReaderWriterLockTryLockWrite);
FUNC(sceUltReaderWriterLockUnlockRead);
FUNC(sceUltReaderWriterLockUnlockWrite);
FUNC(sceUltSemaphoreAcquire);
FUNC(sceUltSemaphoreDestroy);
FUNC(sceUltSemaphoreRelease);
FUNC(sceUltSemaphoreTryAcquire);
FUNC(sceUltUlthreadExit);
FUNC(sceUltUlthreadGetSelf);
FUNC(sceUltUlthreadJoin);
FUNC(sceUltUlthreadRuntimeDestroy);
FUNC(sceUltUlthreadRuntimeGetWorkAreaSize);
FUNC(sceUltUlthreadTryJoin);
FUNC(sceUltUlthreadYield);
FUNC(sceUltWaitingQueueResourcePoolDestroy);
FUNC(sceUltWaitingQueueResourcePoolGetWorkAreaSize);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
