/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpProfileDialogClose);
FUNC(sceNpProfileDialogGetResult);
FUNC(sceNpProfileDialogGetStatus);
FUNC(sceNpProfileDialogInitialize);
FUNC(sceNpProfileDialogOpen);
FUNC(sceNpProfileDialogOpenA);
FUNC(sceNpProfileDialogTerminate);
FUNC(sceNpProfileDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
