/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(_sceApplicationGetAppId);
FUNC(sceApplicationAddProcess2);
FUNC(sceApplicationBeginSclkChange);
FUNC(sceApplicationBlockingKill2);
FUNC(sceApplicationBlockingKill3);
FUNC(sceApplicationContinue);
FUNC(sceApplicationCrashSyscore);
FUNC(sceApplicationCrashSystemProcess);
FUNC(sceApplicationDebugSpawnAndSetAllFocus);
FUNC(sceApplicationDebugSpawnCommonDialog);
FUNC(sceApplicationDebugSpawnDaemon);
FUNC(sceApplicationEndSclkChange);
FUNC(sceApplicationExitSpawn);
FUNC(sceApplicationExitSpawn2);
FUNC(sceApplicationFinalize);
FUNC(sceApplicationGetAppInfoByAppId);
FUNC(sceApplicationGetAppPackageInfoForCoredump);
FUNC(sceApplicationGetCanvasHandle);
FUNC(sceApplicationGetCanvasHandleByApplicationLocalPid);
FUNC(sceApplicationGetCanvasHandleByPid);
FUNC(sceApplicationGetCompiledSdkVersionByAppId);
FUNC(sceApplicationGetCoredumpDirAndFileName);
FUNC(sceApplicationGetCoredumpState);
FUNC(sceApplicationGetCpuUsage);
FUNC(sceApplicationGetCpuUsage2);
FUNC(sceApplicationGetDbgExecutablePath);
FUNC(sceApplicationGetMode);
FUNC(sceApplicationGetProcs);
FUNC(sceApplicationGetShellCoreAppId);
FUNC(sceApplicationGetStateForDebugger);
FUNC(sceApplicationInitialize);
FUNC(sceApplicationInitializeForShellCore);
FUNC(sceApplicationIsCrashReportBeingProcessed);
FUNC(sceApplicationIsPrimaryProcess);
FUNC(sceApplicationIsResumable);
FUNC(sceApplicationIsSuspendable);
FUNC(sceApplicationKickCoredump);
FUNC(sceApplicationKickCoredump2);
FUNC(sceApplicationKill);
FUNC(sceApplicationLocalProcessKill);
FUNC(sceApplicationLocalProcessKill2);
FUNC(sceApplicationLocalProcessResume);
FUNC(sceApplicationLocalProcessSuspend);
FUNC(sceApplicationNotifyCoredumpRequestEnd);
FUNC(sceApplicationNotifyCoredumpRequestProgress);
FUNC(sceApplicationNotifyPhase);
FUNC(sceApplicationNotifyVshMainOnStandby);
FUNC(sceApplicationNotifyVshReady);
FUNC(sceApplicationOnAllResourceReleased);
FUNC(sceApplicationRaiseException);
FUNC(sceApplicationRaiseExceptionToLocalPid);
FUNC(sceApplicationRaiseExceptionToPid);
FUNC(sceApplicationRequestToChangeRenderingMode);
FUNC(sceApplicationResume);
FUNC(sceApplicationSendDebugSpawnResult2);
FUNC(sceApplicationSendResultOfDebuggerKillRequest);
FUNC(sceApplicationSendResultOfDebuggerResumeRequest);
FUNC(sceApplicationSendResultOfDebuggerSuspendRequest);
FUNC(sceApplicationSendResultOfDebuggerTitleIdLaunchRequest);
FUNC(sceApplicationSetApplicationFocus);
FUNC(sceApplicationSetCanvasHandle);
FUNC(sceApplicationSetControllerFocus);
FUNC(sceApplicationSetControllerFocusPermissionToSubProcess);
FUNC(sceApplicationSetMemoryPstate);
FUNC(sceApplicationSignalShellCoreHeartBeat);
FUNC(sceApplicationSpawnAndSetAllFocus);
FUNC(sceApplicationSpawnCommonDialog);
FUNC(sceApplicationSpawnDaemon);
FUNC(sceApplicationSuspend);
FUNC(sceApplicationSuspendSystemForDebugger);
FUNC(sceApplicationSwitchToBaseMode);
FUNC(sceApplicationSwitchToNeoMode);
FUNC(sceApplicationSwitchToNeoMode2);
FUNC(sceApplicationSystemReboot);
FUNC(sceApplicationSystemShutdown2);
FUNC(sceApplicationSystemSuspend);
FUNC(sceApplictionGetStateForDebugger);
FUNC(sceSysCoreGetEventCount);
FUNC(sceSysCoreReceiveEvent);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
