/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(_sceFiberAttachContextAndRun);
FUNC(_sceFiberAttachContextAndSwitch);
FUNC(_sceFiberGetThreadFramePointerAddress);
FUNC(_sceFiberInitializeImpl);
FUNC(_sceFiberInitializeWithInternalOptionImpl);
FUNC(sceFiberFinalize);
FUNC(sceFiberGetInfo);
FUNC(sceFiberGetSelf);
FUNC(sceFiberOptParamInitialize);
FUNC(sceFiberRename);
FUNC(sceFiberReturnToThread);
FUNC(sceFiberRun);
FUNC(sceFiberStartContextSizeCheck);
FUNC(sceFiberStopContextSizeCheck);
FUNC(sceFiberSwitch);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
