/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceLoginDialogClose);
FUNC(sceLoginDialogGetResult);
FUNC(sceLoginDialogGetStatus);
FUNC(sceLoginDialogInitialize);
FUNC(sceLoginDialogOpen);
FUNC(sceLoginDialogTerminate);
FUNC(sceLoginDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
