/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpTssCreateNpTitleCtx);
FUNC(sceNpTusAddAndGetVariable);
FUNC(sceNpTusAddAndGetVariableAsync);
FUNC(sceNpTusAddAndGetVariableVUser);
FUNC(sceNpTusAddAndGetVariableVUserAsync);
FUNC(sceNpTusCreateNpTitleCtx);
FUNC(sceNpTusDeleteMultiSlotData);
FUNC(sceNpTusDeleteMultiSlotDataAsync);
FUNC(sceNpTusDeleteMultiSlotVariable);
FUNC(sceNpTusDeleteMultiSlotVariableAsync);
FUNC(sceNpTusGetData);
FUNC(sceNpTusGetDataAsync);
FUNC(sceNpTusGetDataVUser);
FUNC(sceNpTusGetDataVUserAsync);
FUNC(sceNpTusGetFriendsDataStatus);
FUNC(sceNpTusGetFriendsDataStatusAsync);
FUNC(sceNpTusGetFriendsVariable);
FUNC(sceNpTusGetFriendsVariableAsync);
FUNC(sceNpTusGetMultiSlotDataStatus);
FUNC(sceNpTusGetMultiSlotDataStatusAsync);
FUNC(sceNpTusGetMultiSlotDataStatusVUser);
FUNC(sceNpTusGetMultiSlotDataStatusVUserAsync);
FUNC(sceNpTusGetMultiSlotVariable);
FUNC(sceNpTusGetMultiSlotVariableAsync);
FUNC(sceNpTusGetMultiSlotVariableVUser);
FUNC(sceNpTusGetMultiSlotVariableVUserAsync);
FUNC(sceNpTusGetMultiUserDataStatus);
FUNC(sceNpTusGetMultiUserDataStatusAsync);
FUNC(sceNpTusGetMultiUserDataStatusVUser);
FUNC(sceNpTusGetMultiUserDataStatusVUserAsync);
FUNC(sceNpTusGetMultiUserVariable);
FUNC(sceNpTusGetMultiUserVariableAsync);
FUNC(sceNpTusGetMultiUserVariableVUser);
FUNC(sceNpTusGetMultiUserVariableVUserAsync);
FUNC(sceNpTusSetData);
FUNC(sceNpTusSetDataAsync);
FUNC(sceNpTusSetDataVUser);
FUNC(sceNpTusSetDataVUserAsync);
FUNC(sceNpTusSetMultiSlotVariable);
FUNC(sceNpTusSetMultiSlotVariableAsync);
FUNC(sceNpTusTryAndSetVariable);
FUNC(sceNpTusTryAndSetVariableAsync);
FUNC(sceNpTusTryAndSetVariableVUser);
FUNC(sceNpTusTryAndSetVariableVUserAsync);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
