/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(_Z5dummyv);
FUNC(sceWkFontConfigGetAttr);
FUNC(sceWkFontConfigGetFont);
FUNC(sceWkFontConfigGetFontFromFontName);
FUNC(sceWkFontConfigGetFontName);
FUNC(sceWkFontConfigGetFontPath);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
