/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSystemServiceActivateMpeg2Abort);
FUNC(sceSystemServiceActivateMpeg2GetStatus);
FUNC(sceSystemServiceActivateMpeg2Init);
FUNC(sceSystemServiceActivateMpeg2IsActivated);
FUNC(sceSystemServiceActivateMpeg2Start);
FUNC(sceSystemServiceActivateMpeg2Term);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
