/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceRudpAccept);
FUNC(sceRudpActivate);
FUNC(sceRudpBind);
FUNC(sceRudpCreateContext);
FUNC(sceRudpEnableInternalIOThread);
FUNC(sceRudpEnableInternalIOThread2);
FUNC(sceRudpEnd);
FUNC(sceRudpFlush);
FUNC(sceRudpGetContextStatus);
FUNC(sceRudpGetLocalInfo);
FUNC(sceRudpGetMaxSegmentSize);
FUNC(sceRudpGetNumberOfPacketsToRead);
FUNC(sceRudpGetOption);
FUNC(sceRudpGetRemoteInfo);
FUNC(sceRudpGetSizeReadable);
FUNC(sceRudpGetSizeWritable);
FUNC(sceRudpGetStatus);
FUNC(sceRudpInit);
FUNC(sceRudpInitiate);
FUNC(sceRudpListen);
FUNC(sceRudpNetFlush);
FUNC(sceRudpNetReceived);
FUNC(sceRudpPollCancel);
FUNC(sceRudpPollControl);
FUNC(sceRudpPollCreate);
FUNC(sceRudpPollDestroy);
FUNC(sceRudpPollWait);
FUNC(sceRudpProcessEvents);
FUNC(sceRudpRead);
FUNC(sceRudpSetEventHandler);
FUNC(sceRudpSetMaxSegmentSize);
FUNC(sceRudpSetOption);
FUNC(sceRudpTerminate);
FUNC(sceRudpWrite);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
