/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceVideoCoreAbortRequest);
FUNC(sceVideoCoreAcquireDecoderResource);
FUNC(sceVideoCoreAcquireDecoderResourceForBeWrapper);
FUNC(sceVideoCoreAddStream);
FUNC(sceVideoCoreAsyncAddStream);
FUNC(sceVideoCoreAsyncSendRequest);
FUNC(sceVideoCoreCancelThumbnail);
FUNC(sceVideoCoreChangeActiveStatus);
FUNC(sceVideoCoreChangeAudioStream);
FUNC(sceVideoCoreChangeDisplaySize);
FUNC(sceVideoCoreChangeHdcpSetting);
FUNC(sceVideoCoreChangeSubtitle);
FUNC(sceVideoCoreDeleteStream);
FUNC(sceVideoCoreGenerateThumbnail);
FUNC(sceVideoCoreGenerateThumbnail2);
FUNC(sceVideoCoreGetCanvasHandle);
FUNC(sceVideoCoreGetPlayStatus);
FUNC(sceVideoCoreGetPlayStatus2);
FUNC(sceVideoCoreGetStreamUid);
FUNC(sceVideoCoreGetThumbnail);
FUNC(sceVideoCoreGetThumbnail2);
FUNC(sceVideoCoreLaunchVideoCore);
FUNC(sceVideoCoreMediaSourceAbortSourceBuffer);
FUNC(sceVideoCoreMediaSourceAddSourceBuffer);
FUNC(sceVideoCoreMediaSourceAppendData);
FUNC(sceVideoCoreMediaSourceEndOfStream);
FUNC(sceVideoCoreMediaSourceGetBufferedTimeRanges);
FUNC(sceVideoCoreMediaSourceGetInputBufferEmptySize);
FUNC(sceVideoCoreMediaSourceGetPlaybackQuality);
FUNC(sceVideoCoreMediaSourceGetSourceBufferEvent);
FUNC(sceVideoCoreMediaSourceRemoveSourceBuffer);
FUNC(sceVideoCoreMediaSourceSetDuration);
FUNC(sceVideoCoreMediaSourceSetTimestampOffset);
FUNC(sceVideoCorePlayControl);
FUNC(sceVideoCoreRegistEventCallback);
FUNC(sceVideoCoreReleaseDecoderResource);
FUNC(sceVideoCoreReleaseDecoderResourceForBeWrapper);
FUNC(sceVideoCoreSetAudioMute);
FUNC(sceVideoCoreSetAudioVolume);
FUNC(sceVideoCoreSetFullScreen);
FUNC(sceVideoCoreSetInitialInfo);
FUNC(sceVideoCoreSetInitializeInfo);
FUNC(sceVideoCoreSetPlaybackRange);
FUNC(sceVideoCoreSetThumbnailInfo);
FUNC(sceVideoCoreSyncAddStream);
FUNC(sceVideoCoreSyncSendRequest);
FUNC(sceVideoCoreUnregistEventCallback);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
