/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(_Z5dummyv);
FUNC(sceHttp2AbortRequest);
FUNC(sceHttp2AddCookie);
FUNC(sceHttp2AddRequestHeader);
FUNC(sceHttp2AuthCacheFlush);
FUNC(sceHttp2CookieExport);
FUNC(sceHttp2CookieFlush);
FUNC(sceHttp2CookieImport);
FUNC(sceHttp2CreateCookieBox);
FUNC(sceHttp2CreateRequestWithURL);
FUNC(sceHttp2CreateTemplate);
FUNC(sceHttp2DeleteCookieBox);
FUNC(sceHttp2DeleteRequest);
FUNC(sceHttp2DeleteTemplate);
FUNC(sceHttp2GetAllResponseHeaders);
FUNC(sceHttp2GetAuthEnabled);
FUNC(sceHttp2GetAutoRedirect);
FUNC(sceHttp2GetCookie);
FUNC(sceHttp2GetCookieBox);
FUNC(sceHttp2GetCookieStats);
FUNC(sceHttp2GetMemoryPoolStats);
FUNC(sceHttp2GetResponseContentLength);
FUNC(sceHttp2GetStatusCode);
FUNC(sceHttp2Init);
FUNC(sceHttp2ReadData);
FUNC(sceHttp2ReadDataAsync);
FUNC(sceHttp2RedirectCacheFlush);
FUNC(sceHttp2RemoveRequestHeader);
FUNC(sceHttp2SendRequest);
FUNC(sceHttp2SendRequestAsync);
FUNC(sceHttp2SetAuthEnabled);
FUNC(sceHttp2SetAuthInfoCallback);
FUNC(sceHttp2SetAutoRedirect);
FUNC(sceHttp2SetConnectionWaitTimeOut);
FUNC(sceHttp2SetConnectTimeOut);
FUNC(sceHttp2SetCookieBox);
FUNC(sceHttp2SetCookieMaxNum);
FUNC(sceHttp2SetCookieMaxNumPerDomain);
FUNC(sceHttp2SetCookieMaxSize);
FUNC(sceHttp2SetCookieRecvCallback);
FUNC(sceHttp2SetCookieSendCallback);
FUNC(sceHttp2SetInflateGZIPEnabled);
FUNC(sceHttp2SetMinSslVersion);
FUNC(sceHttp2SetPreSendCallback);
FUNC(sceHttp2SetRecvTimeOut);
FUNC(sceHttp2SetRedirectCallback);
FUNC(sceHttp2SetRequestContentLength);
FUNC(sceHttp2SetResolveRetry);
FUNC(sceHttp2SetResolveTimeOut);
FUNC(sceHttp2SetSendTimeOut);
FUNC(sceHttp2SetSslCallback);
FUNC(sceHttp2SetTimeOut);
FUNC(sceHttp2SslDisableOption);
FUNC(sceHttp2SslEnableOption);
FUNC(sceHttp2Term);
FUNC(sceHttp2WaitAsync);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
