/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNpSignalingActivateConnection);
FUNC(sceNpSignalingActivateConnectionA);
FUNC(sceNpSignalingCancelPeerNetInfo);
FUNC(sceNpSignalingCreateContext);
FUNC(sceNpSignalingCreateContextA);
FUNC(sceNpSignalingDeactivateConnection);
FUNC(sceNpSignalingDeleteContext);
FUNC(sceNpSignalingGetConnectionFromNpId);
FUNC(sceNpSignalingGetConnectionFromPeerAddress);
FUNC(sceNpSignalingGetConnectionFromPeerAddressA);
FUNC(sceNpSignalingGetConnectionInfo);
FUNC(sceNpSignalingGetConnectionInfoA);
FUNC(sceNpSignalingGetConnectionStatistics);
FUNC(sceNpSignalingGetConnectionStatus);
FUNC(sceNpSignalingGetContextOption);
FUNC(sceNpSignalingGetLocalNetInfo);
FUNC(sceNpSignalingGetMemoryInfo);
FUNC(sceNpSignalingGetPeerNetInfo);
FUNC(sceNpSignalingGetPeerNetInfoA);
FUNC(sceNpSignalingGetPeerNetInfoResult);
FUNC(sceNpSignalingInitialize);
FUNC(sceNpSignalingSetContextOption);
FUNC(sceNpSignalingTerminate);
FUNC(sceNpSignalingTerminateConnection);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
