/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceDataTransferHostAbort);
FUNC(sceDataTransferHostLaunch);
FUNC(sceDataTransferHostNotifyEasySignInReady);
FUNC(sceDataTransferInitialize);
FUNC(sceDataTransferTargetAbortBindSavedata);
FUNC(sceDataTransferTargetAbortDeactivate);
FUNC(sceDataTransferTargetAbortEth0);
FUNC(sceDataTransferTargetAbortGetDeviceInfo);
FUNC(sceDataTransferTargetAbortGetDeviceInfoApplication);
FUNC(sceDataTransferTargetAbortGetTitles);
FUNC(sceDataTransferTargetAbortGetUsers);
FUNC(sceDataTransferTargetAbortLaunch);
FUNC(sceDataTransferTargetAbortPrepareTransfer);
FUNC(sceDataTransferTargetAbortPwrReq);
FUNC(sceDataTransferTargetAbortReboot);
FUNC(sceDataTransferTargetAbortSendSsoNew2Old);
FUNC(sceDataTransferTargetAbortSendSsoOld2New);
FUNC(sceDataTransferTargetAbortTransfer);
FUNC(sceDataTransferTargetAbortTransferSpeed);
FUNC(sceDataTransferTargetEventIsAuthReady);
FUNC(sceDataTransferTargetEventIsIPv6Ready);
FUNC(sceDataTransferTargetEventIsPwrReqReady);
FUNC(sceDataTransferTargetGetFailedUsers);
FUNC(sceDataTransferTargetGetRebootData);
FUNC(sceDataTransferTargetGetTransferProgress);
FUNC(sceDataTransferTargetRequestAbortSearch);
FUNC(sceDataTransferTargetRequestActivate);
FUNC(sceDataTransferTargetRequestAuth);
FUNC(sceDataTransferTargetRequestBindSavedata);
FUNC(sceDataTransferTargetRequestComplete);
FUNC(sceDataTransferTargetRequestCreateRebootData);
FUNC(sceDataTransferTargetRequestDeactivate);
FUNC(sceDataTransferTargetRequestEndTransfer);
FUNC(sceDataTransferTargetRequestGetDeviceInfo);
FUNC(sceDataTransferTargetRequestGetDeviceInfoApplication);
FUNC(sceDataTransferTargetRequestGetTitles);
FUNC(sceDataTransferTargetRequestGetUsers);
FUNC(sceDataTransferTargetRequestLaunch);
FUNC(sceDataTransferTargetRequestPrepareTransfer);
FUNC(sceDataTransferTargetRequestPrepareTransferProgress);
FUNC(sceDataTransferTargetRequestPwrReq);
FUNC(sceDataTransferTargetRequestReboot);
FUNC(sceDataTransferTargetRequestSearch);
FUNC(sceDataTransferTargetRequestSendSsoNew2Old);
FUNC(sceDataTransferTargetRequestSendSsoOld2New);
FUNC(sceDataTransferTargetRequestStartTransfer);
FUNC(sceDataTransferTargetRequestTransferSpeed);
FUNC(sceDataTransferTerminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
