/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceVideodec2AllocateComputeQueue);
FUNC(sceVideodec2CreateDecoder);
FUNC(sceVideodec2CreateHevcDecoder);
FUNC(sceVideodec2Decode);
FUNC(sceVideodec2DeleteDecoder);
FUNC(sceVideodec2Flush);
FUNC(sceVideodec2GetAvcPictureInfo);
FUNC(sceVideodec2GetHevcPictureInfo);
FUNC(sceVideodec2GetPictureInfo);
FUNC(sceVideodec2MapDirectMemory);
FUNC(sceVideodec2QueryComputeMemoryInfo);
FUNC(sceVideodec2QueryDecoderMemoryInfo);
FUNC(sceVideodec2QueryHevcDecoderMemoryInfo);
FUNC(sceVideodec2ReleaseComputeQueue);
FUNC(sceVideodec2Reset);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
