/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceGameLiveStreamingApplySocialFeedbackMessageFilter);
FUNC(sceGameLiveStreamingCheckCallback);
FUNC(sceGameLiveStreamingClearPresetSocialFeedbackCommands);
FUNC(sceGameLiveStreamingClearSocialFeedbackMessages);
FUNC(sceGameLiveStreamingClearSpoilerTag);
FUNC(sceGameLiveStreamingEnableLiveStreaming);
FUNC(sceGameLiveStreamingEnableSocialFeedback);
FUNC(sceGameLiveStreamingGetCurrentBroadcastScreenLayout);
FUNC(sceGameLiveStreamingGetCurrentStatus);
FUNC(sceGameLiveStreamingGetCurrentStatus2);
FUNC(sceGameLiveStreamingGetProgramInfo);
FUNC(sceGameLiveStreamingGetSocialFeedbackMessages);
FUNC(sceGameLiveStreamingGetSocialFeedbackMessagesCount);
FUNC(sceGameLiveStreamingInitialize);
FUNC(sceGameLiveStreamingLaunchLiveViewer);
FUNC(sceGameLiveStreamingLaunchLiveViewerA);
FUNC(sceGameLiveStreamingPermitLiveStreaming);
FUNC(sceGameLiveStreamingPermitServerSideRecording);
FUNC(sceGameLiveStreamingPostSocialMessage);
FUNC(sceGameLiveStreamingRegisterCallback);
FUNC(sceGameLiveStreamingScreenCloseSeparateMode);
FUNC(sceGameLiveStreamingScreenConfigureSeparateMode);
FUNC(sceGameLiveStreamingScreenInitialize);
FUNC(sceGameLiveStreamingScreenInitializeSeparateModeParameter);
FUNC(sceGameLiveStreamingScreenOpenSeparateMode);
FUNC(sceGameLiveStreamingScreenSetMode);
FUNC(sceGameLiveStreamingScreenTerminate);
FUNC(sceGameLiveStreamingSetCameraFrameSetting);
FUNC(sceGameLiveStreamingSetDefaultServiceProviderPermission);
FUNC(sceGameLiveStreamingSetGuardAreas);
FUNC(sceGameLiveStreamingSetInvitationSessionId);
FUNC(sceGameLiveStreamingSetLinkCommentPreset);
FUNC(sceGameLiveStreamingSetMaxBitrate);
FUNC(sceGameLiveStreamingSetMetadata);
FUNC(sceGameLiveStreamingSetPresetSocialFeedbackCommands);
FUNC(sceGameLiveStreamingSetPresetSocialFeedbackCommandsDescription);
FUNC(sceGameLiveStreamingSetServiceProviderPermission);
FUNC(sceGameLiveStreamingSetSpoilerTag);
FUNC(sceGameLiveStreamingSetStandbyScreenResource);
FUNC(sceGameLiveStreamingStartGenerateStandbyScreenResource);
FUNC(sceGameLiveStreamingStartSocialFeedbackMessageFiltering);
FUNC(sceGameLiveStreamingStopGenerateStandbyScreenResource);
FUNC(sceGameLiveStreamingStopSocialFeedbackMessageFiltering);
FUNC(sceGameLiveStreamingTerminate);
FUNC(sceGameLiveStreamingUnregisterCallback);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
