/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceRegMgrBackupNeedMem);
FUNC(sceRegMgrBackupPullData);
FUNC(sceRegMgrBackupPushData);
FUNC(sceRegMgrCheckError);
FUNC(sceRegMgrCntlDeleteReg);
FUNC(sceRegMgrCntlGetFileName);
FUNC(sceRegMgrCntlGetFilesCount);
FUNC(sceRegMgrCntlStart);
FUNC(sceRegMgrCntlStopHdd);
FUNC(sceRegMgrCntSetInitReinst);
FUNC(sceRegMgrDrvDataCheckGet);
FUNC(sceRegMgrDrvDataClose);
FUNC(sceRegMgrDrvDataOpen);
FUNC(sceRegMgrDrvGetEntCnt);
FUNC(sceRegMgrDrvGetUpdateCnt);
FUNC(sceRegMgrEvtGetCnt);
FUNC(sceRegMgrEvtGetRegId);
FUNC(sceRegMgrGetBin);
FUNC(sceRegMgrGetBinInitVal);
FUNC(sceRegMgrGetInt);
FUNC(sceRegMgrGetIntInitVal);
FUNC(sceRegMgrGetStr);
FUNC(sceRegMgrGetStrInitVal);
FUNC(sceRegMgrGetVersion);
FUNC(sceRegMgrIsChange);
FUNC(sceRegMgrIsInitOK);
FUNC(sceRegMgrLogPull);
FUNC(sceRegMgrLogStart);
FUNC(sceRegMgrNonSysCheckError);
FUNC(sceRegMgrNonSysGetBin);
FUNC(sceRegMgrNonSysGetInt);
FUNC(sceRegMgrNonSysGetStr);
FUNC(sceRegMgrNonSysSetBin);
FUNC(sceRegMgrNonSysSetInt);
FUNC(sceRegMgrNonSysSetStr);
FUNC(sceRegMgrPrintInfo);
FUNC(sceRegMgrRecoverRegNvs);
FUNC(sceRegMgrResetVal);
FUNC(sceRegMgrSetBin);
FUNC(sceRegMgrSetInitLevel);
FUNC(sceRegMgrSetInt);
FUNC(sceRegMgrSetStr);
FUNC(sceRegMgrSrvCnvRegionInt);
FUNC(sceRegMgrSrvCnvRegionStr);
FUNC(sceRegMgrSrvGetMachineType);
FUNC(sceRegMgrSrvGetQAFforReg);
FUNC(sceRegMgrSrvGetRealMachineType);
FUNC(sceRegMgrSrvGetRegion);
FUNC(sceRegMgrSrvGetRegionStr);
FUNC(sceRegMgrToolDataCheckGet);
FUNC(sceRegMgrToolGetEntryCnt);
FUNC(sceRegMgrToolGetInfo);
FUNC(sceRegMgrToolGetUpdateCnt);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
