/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceBackupRestoreUtilBackupData);
FUNC(sceBackupRestoreUtilCancelBackupData);
FUNC(sceBackupRestoreUtilCancelGetRequiredSize);
FUNC(sceBackupRestoreUtilCancelGetTitles);
FUNC(sceBackupRestoreUtilCancelRestoreData);
FUNC(sceBackupRestoreUtilDeleteBackupData);
FUNC(sceBackupRestoreUtilGetBackupDataInfo);
FUNC(sceBackupRestoreUtilGetBackupParam);
FUNC(sceBackupRestoreUtilGetBackupProgress);
FUNC(sceBackupRestoreUtilGetRequiredSize);
FUNC(sceBackupRestoreUtilGetRestoreProgress);
FUNC(sceBackupRestoreUtilGetTitles);
FUNC(sceBackupRestoreUtilInitialize);
FUNC(sceBackupRestoreUtilPrepareBackup);
FUNC(sceBackupRestoreUtilRestoreData);
FUNC(sceBackupRestoreUtilTerminate);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
