/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceNetCtlApCheckCallback);
FUNC(sceNetCtlApClearEvent);
FUNC(sceNetCtlApGetConnectInfo);
FUNC(sceNetCtlApGetInfo);
FUNC(sceNetCtlApGetResult);
FUNC(sceNetCtlApGetState);
FUNC(sceNetCtlApInit);
FUNC(sceNetCtlApRegisterCallback);
FUNC(sceNetCtlApStop);
FUNC(sceNetCtlApTerm);
FUNC(sceNetCtlApUnregisterCallback);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
