/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceErrorDialogClose);
FUNC(sceErrorDialogGetStatus);
FUNC(sceErrorDialogInitialize);
FUNC(sceErrorDialogOpen);
FUNC(sceErrorDialogOpenDetail);
FUNC(sceErrorDialogOpenWithReport);
FUNC(sceErrorDialogTerminate);
FUNC(sceErrorDialogUpdateStatus);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
