/* Source generated by crazyvoids source generating tool **/

#define FUNC(func) void __attribute__((visibility("default"))) func(void) { for(;;){} }

FUNC(sceSystemServiceAddLocalProcessForJvm);
FUNC(sceSystemServiceGetParentSocketForJvm);
FUNC(sceSystemServiceKillLocalProcessForJvm);


void __attribute__ ((constructor)) initLibrary(void)
{
}

void __attribute__ ((destructor)) cleanUpLibrary(void)
{
}
